from enum import StrEnum

from .LevelNames import LevelCategory

# up_dash = "Up Dash"
# right_dash = "Right Dash"
# down_dash = "Down Dash"
# left_dash = "Left Dash"
# up_right_dash = "Up-Right Dash"
# up_left_dash = "Up-Left Dash"
# down_right_dash = "Down-Right Dash"
# down_left_dash = "Down-Left Dash"

class ItemName(StrEnum):

    #Mechanics
    DASH_CRYSTALS = "Single Dash Crystals"
    TRAFFIC_BLOCKS = "Normal Traffic Blocks"
    SPRINGS = "Normal Springs"
    BLUE_CASSETTE = "Plain Blue Cassette Blocks"
    PINK_CASSETTE = "Plain Pink Cassette Blocks"
    CRUMBLING_PLATFORM = "Crumbling Platforms",
    TOUCH_SWITCH = "Vanilla Touch Switches",
    DREAM_BLOCK = "Normal Dream Blocks",
    BADELINE_ORB = "Badeline Orbs",
    SINKING_PLATFORM = "Sinking Platforms",
    GREEN_BUBBLES = "Vanilla Blue Bubbles",
    CLOUDS = "Clouds",
    PINK_CLOUDS = "Pink Clouds",
    MOVING_BLOCK = "Vanilla Move Blocks",
    RED_BUBBLES = "Red Bubbles",
    SWAP_BLOCK = "Regular Swap Blocks",
    DASH_SWITCH = "Vanilla Dash Switches",
    FEATHER = "Feathers",
    MOVING_PLATFORM = "Moving Platforms",
    WHITE_BLOCK = "White Block",
    SEEKERS = "Seekers",
    THEO_CRYSTAL = "Theo Crystal",
    KEVIN = "Normal Kevins",
    BUMPER = "Normal Bumpers",
    CORE_BLOCK = "Core Blocks",
    CORE_SWITCH = "Core Switches",
    LAVA_ICE_BALLS = "Fire/Ice Balls",
    BREAKER_BOX = "Breaker Boxes",
    BIRD = "Bird",
    JELLYFISH = "Jellyfish",
    PUFFER_FISH = "Puffer fish",
    DOUBLE_DASH_CRYSTALS = "Double Dash Crystals",
    YELLOW_CASSETTE = "Plain Yellow Cassette Blocks",
    GREEN_CASSETTE = "Plain Green Cassette Blocks",
    LOOP_BLOCK = "Loopy Blocks"
    DREAM_DASH_CRYSTAL = "Dream Dash Crystals",
    INTRO_CRUSHER = "Falling/Moving Ice Blocks",
    DASH_TRAFFIC_BLOCK = "Dash-Activated Zippers",
    BLUE_TRAFFIC_CASSETTE = "Blue Cassette Traffic Blocks",
    PINK_TRAFFIC_CASSETTE = "Pink Cassette Traffic Blocks",
    YELLOW_TRAFFIC_CASSETTE = "Yellow Cassette Traffic Blocks",
    SOAP_BUBBLE = "Blue Dashless Bubbles",
    DASHLESS_SPRING = "Dashless Blue Springs",
    SINGLE_JUMP_REFILL = "Single Jump Refills",
    TRIPLE_JUMP_REFILL = "Triple Jump Refills",
    DOUBLE_DASH_DREAM_BLOCK = "Double Dash Dream Blocks"
    GREEN_SWITCH_BLOCK = "Green Switch Blocks",
    ORANGE_SWITCH_BLOCK = "Orange Switch Blocks",
    SWITCH_BLOCK_SWITCH = "Switch Block Switch",
    GRAVITY_FIELD = "Gravity Fields",
    BLUE_TIME_CRYSTAL = "Blue Time Crystals",
    DASH_CRYSTAL_SHARDS = "Dash Crystal Shards",
    PIPES = "Pipes",
    BIG_YELLOW_BUTTON = "Big Yellow Buttons",
    PUZZLE_KEVIN = "Dropzle Kevins",
    TRIPLE_BOOST_FLOWER = "Triple-Boost Rose",
    BOUNCE_DREAM_BLOCK = "Treehive Dream Blocks",
    ORANGE_LINKED_TRAFFIC_BLOCK = "Orange Linked Zippers",
    BLUE_LINKED_TRAFFIC_BLOCK = "Blue Linked Zippers",
    TOGGLE_SWAP_BLOCK = "Toggle Swap Blocks",
    GREEN_LINKED_TRAFFIC_BLOCK = "Green Linked Zippers",
    STRAWBERRY_JAM = "Strawberry Jam Jar",
    NEON_BLUE_KEVIN = "Neon Blue Kevins",
    NEON_PURPLE_KEVIN = "Neon Purple Kevins",
    PUSH_BLOCK = "Push Blocks",
    VERTIGO_LINKED_TELEPORT = "Vertigo Linked Teleports",
    YELLOW_PORTAL = "Yellow Portals",
    PURPLE_PORTAL = "Purple Portals",
    PUSH_STATION_BLOCK = "Push Station Blocks",
    BLUE_PORTAL = "Blue Portals",
    RED_PORTAL = "Red Portals",
    TIMED_TOUCH_SWITCH = "Timed Touch Switches"
    HONEY_BUBBLES = "Honey Bubbles",
    ZIPLINE = "Ziplines",
    YELLOW_LINKED_TRAFFIC_BLOCK = "Yellow Linked Zippers",
    YELLOW_LASER = "Yellow Activation Lasers",
    TORQUOISE_LASER = "Torquoise Activation Lasers",
    GREEN_LASER = "Green Activation Lasers",
    MAGENTA_LINKED_TRAFFIC_BLOCK = "Magenta Linked Zippers",
    TORQUOISE_LINKED_TRAFFIC_BLOCK = "Torquoise Linked Zippers",
    RED_LINKED_TRAFFIC_BLOCK = "Red Linked Zippers",
    CRYSTAL_BOMB = "Crystal Bombs",
    BOWL_PUFFER = "Pufferfish in a Bowl",
    PURPLE_DASHLESS_BUBBLE = "Purple Dashless Bubbles",
    PULL_STATION_BLOCK = "Pull Station Blocks",
    DASH_SPRING = "Dash Springs",
    TRACK_SWITCH_BOX = "Track Switch Box",
    PURPLE_LINKED_TRAFFIC_BLOCK = "Purple Linked Zippers",
    GRAY_TIME_CRYSTAL = "Gray Time Crystals",
    PURPLE_JELLYFISH = "Purple Jellyfish",
    DASH_REFILL_WALL = "Dash Refill Walls",
    DOUBLE_DASH_REFILL_WALL = "Double Dash Refill Walls",
    GRAY_BUBBLES = "Gray Bubbles",
    SWITCH_CRATE = "Switch Crates",
    GREEN_PORTAL = "Green Portals",
    MOVING_TOUCH_SWITCH = "Moving Touch Switches",
    DREAM_TRAFFIC_BLOCK = "Dream Zippers",
    BOUNCY_SPIKES = "Bouncy Spikes",
    MOMENTUM_SPRING = "Momentum Springs",
    PURPLE_CASSETTE_BLOCK = "Purple Cassette Blocks",
    ORANGE_CASSETTE_BLOCK = "Orange Cassette Blocks",
    RED_CASSETTE_BLOCK = "Red Cassette Blocks",
    GREEN_CASSETTE_TRAFFIC_BLOCK = "Green Cassette Zippers",
    PURPLE_MOVING_CASSETTE_BLOCK = "Purple Moving Cassette blocks",
    BLUE_MOVING_CASSETTE_BLOCK = "Blue Moving Cassette Blocks",
    PURPLE_CASSETTE_SWAP_BLOCK = "Purple Moving Cassette Blocks",
    PINK_CASSETTE_SWAP_BLOCK = "Pink Cassette Swap Blocks",
    RED_CASSETTE_SWAP_BLOCK = "Red Cassette Swap Blocks",
    ORANGE_MOVING_CASSETTE_BLOCK = "Orange Moving Cassette Blocks",
    ORANGE_CASSETTE_TRAFFIC_BLOCK = "Orange Cassette Zippers",
    GREEN_CASSETTE_SWAP_BLOCK = "Green Cassette Swap Blocks",
    RED_CASSETTE_TRAFFIC_BLOCK = "Red Cassette Zippers",
    YELLOW_CASSETTE_SWAP_BLOCK = "Yellow Cassette Swap Blocks",
    PINK_MOVING_CASSETTE_BLOCK = "Pink Moving Cassette Blocks",
    GREEN_MOVING_CASSETTE_BLOCK = "Green Moving Cassette Blocks",
    WORMHOLE_BUBBLE = "Wormhole Bubbles",
    FAKE_CRYSTAL_HEART = "Fake Crystal Hearts",
    MINI_FAKE_CRYSTAL_HEART = "Mini Fake Crystal Hearts",
    THROW_BOX = "Throw Boxes",
    PURPLE_REBOUND_BUBBLE = "Purple Rebound Bubbles",
    GROWTH_POTION = "Growth Potion",
    BLUE_GRAVITY_SPRING = "Blue Gravity Springs",
    RED_GRAVITY_SPRING = "Red Gravity Springs",
    PURPLE_GRAVITY_SPRING = "Purple Gravity Springs",
    YELLOW_MOVING_CASSETTE_BLOCK = "Yellow Moving Cassette Blocks",
    MOVE_BLOCK_ACCELERATOR_FIELD = "Move Block Green Acceleration Fields",
    MOVE_BLOCK_DELETE_FIELD = "Move Block Red Deletion Fields",
    MOVE_BLOCK_DECELERATOR_FIELD = "Move Block Blue Deceleration Fields",
    MOVE_BLOCK_REDIRECT_FIELD = "Move Block Yellow Redirection Fields",
    DREAM_MOVE_BLOCK = "Moving Dream Blocks",
    BATTERY = "Batteries",
    RED_PROPELLER_BLOCK = "Red Propeller Blocks",
    YELLOW_PROPELLER_BLOCK = "Yellow Propeller Blocks",
    DASH_BOOST_FIELD = "Dash Boost Fields",
    FORCE_JUMP_CRYSTAL = "Force Jump Crystals",
    NO_STAMINA_DASH_CRYSTAL = "No-Stamina Dash Crystals",
    SPEED_MUSHROOMS = "Speed Mushrooms",
    SPEED_MUSHROOM_WALL = "Speed Mushroom Refill Walls",
    WHITE_DREAM_BLOCK = "White Dream Blocks",
    RED_SPEED_MOSS = "Red Speed Moss",
    BLUE_BOUNCE_MOSS = "Blue Bounce Moss",
    WHITE_LINKED_TRAFFIC_BLOCK = "White Linked Traffic Blocks",
    SQUARE_BUMPER = "Square Bumpers",
    BLUE_FLOATING_FIELDS = "Blue Float Fields",
    RED_FLOATING_FIELDS = "Red Float Fields",
    PURPLE_FLOATING_FIELDS = "Purple Float Fields",
    BLUE_FLIP_SWITCH = "Blue Toggle Switches",
    GREEN_FLIP_SWITCH = "Green Toggle Switches",
    PURPLE_FLIP_SWITCH = "Purple Toggle Switches",
    PINK_FLIP_SWITCH = "Pink Toggle Switches",
    RED_FLIP_SWITCH = "Red Toggle Switches",
    PINK_SWITCH_BLOCK = "Pink Switch Blocks",
    PURPLE_SWITCH_BLOCK = "Purple Switch Blocks",
    RED_SWITCH_BLOCK = "Red Switch Blocks",
    CLOUD_CRYSTAL = "Cloud Crystals",
    JELLY_CRYSTAL = "Jellyfish Crystals",
    STOPWATCH_CRYSTAL = "Stopwatch Crystals",
    CURVED_TRAFFIC_BLOCK = "Curved Traffic Blocks",
    SKY_LANTERN = "Sky Lantern",
    INFINITE_DASH_MOSAIC_CRYSTAL = "Infinite Dash Mosaic Crystals",
    BLUE_STOPWATCH = "Blue Stopwatches",
    GREEN_STOPWATCH = "Green Stopwatches",
    GRAY_STOPWATCH = "Gray Stopwatches",
    BUBBLE_EMITTER = "Bubble Emitters",
    CANNON_BALL = "Cannon Ball",
    INFINITE_DASH_FIELD = "Infinite Dash Fields",
    JUMP_REFILL_WALL = "Jump Refill Walls",
    ONE_USE_BUMPER = "Single Use Bumpers",
    DOUBLE_DASH_BUMPER = "Double Dash Bumpers",
    MOVING_BUMPER = "Moving Bumpers",
    YELLOW_ROCK = "Yellow Rock",
    BACKGROUND_SWITCH = "Background Toggle Switch",
    RED_DRUM = "Red Drums",
    TOGGLE_DRUM = "Toggle Drums",
    BLUE_FLYING_LANTERN = "Blue Flying Lanterns",
    RED_FLYING_LANTERN = "Red Flying Lanterns",
    SILVER_PORTAL = "Silver Portals",
    NAVY_PORTAL = "Navy Portals"
            
    STRAWBERRY = "Strawberry"
    
    MOON_BERRY = "Moon Berry"
        
    LEVEL_VICTORY = "Win Condition Level Victory"
    
    RASPBERRY = "Raspberry"
    BLUEBERRY = "Blueberry"
    BLACKBERRY = "Blackberry"
    CRANBERRY = "Cranberry"
    ELDERBERRY = "Elderberry"
    HUCKLEBERRY = "Huckleberry"

    #Consolidated Mechanics
    CASSETTE_BLOCKS = "Cassette Blocks"
    BUBBLES = "Bubbles"
    HEAVY_THROWABLE = "Heavy Throwables"
    LIGHT_THROWABLE = "Light Throwables"
    JUMP_REFILL = "Jump Refills"
    SWITCH_BLOCK = "Switch Blocks"
    GRAVITY_MECHANICS = "Gravity Mechanics"
    TIME_MECHANICS = "Time Mechanics"
    PORTALS = "Portals"
    STATION_BLOCKS = "Station Blocks"
    LASER = "Lasers"
    DASH_SPEEDUP_MECHANICS = "Dash Speedup Mechanics"
    FLIP_SWITCH = "Flip Switches"
    GENERIC_DASH_CRYSTAL = "Dash Crystals"
    GENERIC_SPRINGS = "Springs"
    GENERIC_TRAFFIC_BLOCK = "Traffic Blocks"
    GENERIC_DREAM_BLOCK = "Dream Blocks"
    GENERIC_TOUCH_SWITCH = "Touch Switches"
    GENERIC_SWAP_BLOCK = "Swap Blocks"
    GENERIC_MOVE_BLOCK = "Move Blocks"
    GENERIC_KEVIN = "Kevins"
    GENERIC_BUMPER = "Bumpers"
    GENERIC_DASH_SWITCH = "Dash Switches"
    BLUE = "Blue Colored Mechanics"
    ORANGE = "Orange Colored Mechanics"
    RED = "Red Colored Mechanics"
    GREEN = "Green Colored Mechanics"
    YELLOW = "Yellow Colored Mechanics"
    PINK = "Pink Colored Mechanics"
    PURPLE = "Purple Colored Mechanics"
    WHITE = "White Colored Mechanics"
    GENERIC_SHORT_BUBBLES = "Short-Range Bubbles"
    GENERIC_LONG_BUBBLES = "Long-Range Bubbles"
    GENERIC_REBOUND_BUBBLES = "Rebound Bubbles"
    GENERIC_TIME_CRYSTAL = "Time Crystals"
    GENERIC_REFILL_WALL = "Refill Walls"
    GENERIC_MOVE_BLOCK_MODIFIER = "Move Block Fields"
    PROPELLER_BLOCK = "Propeller Blocks"
    MOVEMENT_MOSS = "Movement Moss"
    FLOATING_FIELDS = "Floating Fields"
    LUNAR_PAGODA_STOPWATCH = "Lunar Pagoda Stopwatches"
    NELUMBO_DRUMS = "Nelumbo Drums"
    NELUMBO_LANTERNS = "Nelumbo Lanterns"
    CRYSTAL_PICKUPS = "Refill Pickups"
    SWITCHES = "All Switches"
    PLAYER_THROWERS = "Player Throwers"


filler = {
    ItemName.RASPBERRY: 0, ItemName.BLUEBERRY: 1, ItemName.BLACKBERRY: 2, ItemName.CRANBERRY: 3, ItemName.ELDERBERRY: 4, ItemName.HUCKLEBERRY: 5
}

strawberry = {ItemName.STRAWBERRY: 0}

moon_berry = {ItemName.MOON_BERRY: 0}

level_victory = {ItemName.LEVEL_VICTORY: 0}

mechanic = {
    ItemName.DASH_CRYSTALS: 0,
    ItemName.TRAFFIC_BLOCKS: 1,
    ItemName.SPRINGS: 2,
    ItemName.BLUE_CASSETTE: 3,
    ItemName.PINK_CASSETTE: 4,
    ItemName.CRUMBLING_PLATFORM: 5,
    ItemName.TOUCH_SWITCH: 6,
    ItemName.DREAM_BLOCK: 7,
    ItemName.BADELINE_ORB: 8,
    ItemName.SINKING_PLATFORM: 9,
    ItemName.GREEN_BUBBLES: 10,
    ItemName.CLOUDS: 11,
    ItemName.PINK_CLOUDS: 12,
    ItemName.MOVING_BLOCK: 13,
    ItemName.RED_BUBBLES: 14,
    ItemName.SWAP_BLOCK: 15,
    ItemName.DASH_SWITCH: 16,
    ItemName.FEATHER: 17,
    ItemName.MOVING_PLATFORM: 18,
    ItemName.WHITE_BLOCK: 19,
    ItemName.SEEKERS: 20,
    ItemName.THEO_CRYSTAL: 21,
    ItemName.KEVIN: 22,
    ItemName.BUMPER: 23,
    ItemName.CORE_BLOCK: 24,
    ItemName.CORE_SWITCH: 25,
    ItemName.LAVA_ICE_BALLS: 26,
    ItemName.BREAKER_BOX: 27,
    ItemName.BIRD: 28,
    ItemName.JELLYFISH: 29,
    ItemName.PUFFER_FISH: 30,
    ItemName.DOUBLE_DASH_CRYSTALS: 31,
    ItemName.YELLOW_CASSETTE: 32,
    ItemName.GREEN_CASSETTE: 33,
    ItemName.LOOP_BLOCK: 34,
    ItemName.DREAM_DASH_CRYSTAL: 35,
    ItemName.INTRO_CRUSHER: 36,
    ItemName.DASH_TRAFFIC_BLOCK: 37,
    ItemName.BLUE_TRAFFIC_CASSETTE: 38,
    ItemName.PINK_TRAFFIC_CASSETTE: 39,
    ItemName.YELLOW_TRAFFIC_CASSETTE: 40,
    ItemName.SOAP_BUBBLE: 41,
    ItemName.DASHLESS_SPRING: 42,
    ItemName.SINGLE_JUMP_REFILL: 43,
    ItemName.TRIPLE_JUMP_REFILL: 44,
    ItemName.DOUBLE_DASH_DREAM_BLOCK: 45,
    ItemName.GREEN_SWITCH_BLOCK: 46,
    ItemName.ORANGE_SWITCH_BLOCK: 47,
    ItemName.SWITCH_BLOCK_SWITCH: 48,
    ItemName.GRAVITY_FIELD: 49,
    ItemName.BLUE_TIME_CRYSTAL: 50,
    ItemName.DASH_CRYSTAL_SHARDS: 51,
    ItemName.PIPES: 52,
    ItemName.BIG_YELLOW_BUTTON: 53,
    ItemName.PUZZLE_KEVIN: 54,
    ItemName.TRIPLE_BOOST_FLOWER: 55,
    ItemName.BOUNCE_DREAM_BLOCK: 56,
    ItemName.ORANGE_LINKED_TRAFFIC_BLOCK: 57,
    ItemName.BLUE_LINKED_TRAFFIC_BLOCK: 58,
    ItemName.TOGGLE_SWAP_BLOCK: 59,
    ItemName.GREEN_LINKED_TRAFFIC_BLOCK: 60,
    ItemName.STRAWBERRY_JAM: 61,
    ItemName.NEON_BLUE_KEVIN: 62,
    ItemName.NEON_PURPLE_KEVIN: 63,
    ItemName.PUSH_BLOCK: 64,
    ItemName.VERTIGO_LINKED_TELEPORT: 65,
    ItemName.YELLOW_PORTAL: 66,
    ItemName.PURPLE_PORTAL: 67,
    ItemName.PUSH_STATION_BLOCK: 68,
    ItemName.BLUE_PORTAL: 69,
    ItemName.RED_PORTAL: 70,
    ItemName.TIMED_TOUCH_SWITCH: 71,
    ItemName.HONEY_BUBBLES: 72,
    ItemName.ZIPLINE: 73,
    ItemName.YELLOW_LINKED_TRAFFIC_BLOCK: 74,
    ItemName.YELLOW_LASER: 75,
    ItemName.TORQUOISE_LASER: 76,
    ItemName.GREEN_LASER: 77,
    ItemName.MAGENTA_LINKED_TRAFFIC_BLOCK: 78,
    ItemName.TORQUOISE_LINKED_TRAFFIC_BLOCK: 79,
    ItemName.RED_LINKED_TRAFFIC_BLOCK: 80,
    ItemName.CRYSTAL_BOMB: 81,
    ItemName.BOWL_PUFFER: 82,
    ItemName.PURPLE_DASHLESS_BUBBLE: 83,
    ItemName.PULL_STATION_BLOCK: 84,
    ItemName.DASH_SPRING: 85,
    ItemName.TRACK_SWITCH_BOX: 86,
    ItemName.PURPLE_LINKED_TRAFFIC_BLOCK: 87,
    ItemName.GRAY_TIME_CRYSTAL: 88,
    ItemName.PURPLE_JELLYFISH: 89,
    ItemName.DASH_REFILL_WALL: 90,
    ItemName.DOUBLE_DASH_REFILL_WALL: 91,
    ItemName.GRAY_BUBBLES: 92,
    ItemName.SWITCH_CRATE: 93,
    ItemName.GREEN_PORTAL: 94,
    ItemName.MOVING_TOUCH_SWITCH: 95,
    ItemName.DREAM_TRAFFIC_BLOCK: 96,
    ItemName.BOUNCY_SPIKES: 97,
    ItemName.MOMENTUM_SPRING: 98,
    ItemName.PURPLE_CASSETTE_BLOCK: 99,
    ItemName.ORANGE_CASSETTE_BLOCK: 100,
    ItemName.RED_CASSETTE_BLOCK: 101,
    ItemName.GREEN_CASSETTE_TRAFFIC_BLOCK: 102,
    ItemName.PURPLE_MOVING_CASSETTE_BLOCK: 103,
    ItemName.BLUE_MOVING_CASSETTE_BLOCK: 104,
    ItemName.PURPLE_CASSETTE_SWAP_BLOCK: 105,
    ItemName.PINK_CASSETTE_SWAP_BLOCK: 106,
    ItemName.RED_CASSETTE_SWAP_BLOCK: 107,
    ItemName.ORANGE_MOVING_CASSETTE_BLOCK: 108,
    ItemName.ORANGE_CASSETTE_TRAFFIC_BLOCK: 109,
    ItemName.GREEN_CASSETTE_SWAP_BLOCK: 110,
    ItemName.RED_CASSETTE_TRAFFIC_BLOCK: 111,
    ItemName.YELLOW_CASSETTE_SWAP_BLOCK: 112,
    ItemName.PINK_MOVING_CASSETTE_BLOCK: 113,
    ItemName.GREEN_MOVING_CASSETTE_BLOCK: 114,
    ItemName.WORMHOLE_BUBBLE: 115,
    ItemName.FAKE_CRYSTAL_HEART: 116,
    ItemName.MINI_FAKE_CRYSTAL_HEART: 117,
    ItemName.THROW_BOX: 118,
    ItemName.PURPLE_REBOUND_BUBBLE: 119,
    ItemName.GROWTH_POTION: 120,
    ItemName.BLUE_GRAVITY_SPRING: 121,
    ItemName.RED_GRAVITY_SPRING: 122,
    ItemName.PURPLE_GRAVITY_SPRING: 123,
    ItemName.YELLOW_MOVING_CASSETTE_BLOCK: 124,
    ItemName.MOVE_BLOCK_ACCELERATOR_FIELD: 125,
    ItemName.MOVE_BLOCK_DELETE_FIELD: 126,
    ItemName.MOVE_BLOCK_DECELERATOR_FIELD: 127,
    ItemName.MOVE_BLOCK_REDIRECT_FIELD: 128,
    ItemName.DREAM_MOVE_BLOCK: 129,
    ItemName.BATTERY: 130,
    ItemName.RED_PROPELLER_BLOCK: 131,
    ItemName.YELLOW_PROPELLER_BLOCK: 132,
    ItemName.DASH_BOOST_FIELD: 133,
    ItemName.FORCE_JUMP_CRYSTAL: 134,
    ItemName.NO_STAMINA_DASH_CRYSTAL: 135,
    ItemName.SPEED_MUSHROOMS: 136,
    ItemName.SPEED_MUSHROOM_WALL: 137,
    ItemName.WHITE_DREAM_BLOCK: 138,
    ItemName.RED_SPEED_MOSS: 139,
    ItemName.BLUE_BOUNCE_MOSS: 140,
    ItemName.WHITE_LINKED_TRAFFIC_BLOCK: 141,
    ItemName.SQUARE_BUMPER: 142,
    ItemName.BLUE_FLOATING_FIELDS: 143,
    ItemName.RED_FLOATING_FIELDS: 144,
    ItemName.PURPLE_FLOATING_FIELDS: 145,
    ItemName.BLUE_FLIP_SWITCH: 146,
    ItemName.GREEN_FLIP_SWITCH: 147,
    ItemName.PURPLE_FLIP_SWITCH: 148,
    ItemName.PINK_FLIP_SWITCH: 149,
    ItemName.RED_FLIP_SWITCH: 150,
    ItemName.PINK_SWITCH_BLOCK: 151,
    ItemName.PURPLE_SWITCH_BLOCK: 152,
    ItemName.RED_SWITCH_BLOCK: 153,
    ItemName.CLOUD_CRYSTAL: 154,
    ItemName.JELLY_CRYSTAL: 155,
    ItemName.STOPWATCH_CRYSTAL: 156,
    ItemName.CURVED_TRAFFIC_BLOCK: 157,
    ItemName.SKY_LANTERN: 158,
    ItemName.INFINITE_DASH_MOSAIC_CRYSTAL: 159,
    ItemName.BLUE_STOPWATCH: 160,
    ItemName.GREEN_STOPWATCH: 161,
    ItemName.GRAY_STOPWATCH: 162,
    ItemName.BUBBLE_EMITTER: 163,
    ItemName.CANNON_BALL: 164,
    ItemName.INFINITE_DASH_FIELD: 165,
    ItemName.JUMP_REFILL_WALL: 166,
    ItemName.ONE_USE_BUMPER: 167,
    ItemName.DOUBLE_DASH_BUMPER: 168,
    ItemName.MOVING_BUMPER: 169,
    ItemName.YELLOW_ROCK: 170,
    ItemName.BACKGROUND_SWITCH: 171,
    ItemName.RED_DRUM: 172,
    ItemName.TOGGLE_DRUM: 173,
    ItemName.BLUE_FLYING_LANTERN: 174,
    ItemName.RED_FLYING_LANTERN: 175,
    ItemName.SILVER_PORTAL: 176,
    ItemName.NAVY_PORTAL: 177,


    ItemName.CASSETTE_BLOCKS: 1000,
    ItemName.BUBBLES: 1001,
    ItemName.HEAVY_THROWABLE: 1002,
    ItemName.LIGHT_THROWABLE: 1003,
    ItemName.JUMP_REFILL: 1004,
    ItemName.SWITCH_BLOCK: 1005,
    ItemName.GRAVITY_MECHANICS: 1006,
    ItemName.TIME_MECHANICS: 1007,
    ItemName.PORTALS: 1008,
    ItemName.STATION_BLOCKS: 1009,
    ItemName.LASER: 1010,
    ItemName.DASH_SPEEDUP_MECHANICS: 1011,
    ItemName.FLIP_SWITCH: 1012,
    ItemName.GENERIC_DASH_CRYSTAL: 1013,
    ItemName.GENERIC_SPRINGS: 1014,
    ItemName.GENERIC_TRAFFIC_BLOCK: 1015,
    ItemName.GENERIC_DREAM_BLOCK: 1016,
    ItemName.GENERIC_TOUCH_SWITCH: 1017,
    ItemName.GENERIC_SWAP_BLOCK: 1018,
    ItemName.GENERIC_MOVE_BLOCK: 1019,
    ItemName.GENERIC_KEVIN: 1020,
    ItemName.GENERIC_BUMPER: 1021,
    ItemName.GENERIC_DASH_SWITCH: 1022,
    ItemName.BLUE: 1023,
    ItemName.ORANGE: 1024,
    ItemName.RED: 1025,
    ItemName.GREEN: 1026,
    ItemName.YELLOW: 1027,
    ItemName.PINK: 1028,
    ItemName.PURPLE: 1029,
    ItemName.WHITE: 1030,
    ItemName.GENERIC_SHORT_BUBBLES: 1031,
    ItemName.GENERIC_LONG_BUBBLES: 1032,
    ItemName.GENERIC_REBOUND_BUBBLES: 1033,
    ItemName.GENERIC_TIME_CRYSTAL: 1034,
    ItemName.GENERIC_REFILL_WALL: 1035,
    ItemName.GENERIC_MOVE_BLOCK_MODIFIER: 1036,
    ItemName.PROPELLER_BLOCK: 1037,
    ItemName.MOVEMENT_MOSS: 1038,
    ItemName.FLOATING_FIELDS: 1039,
    ItemName.LUNAR_PAGODA_STOPWATCH: 1040,
    ItemName.NELUMBO_DRUMS: 1041,
    ItemName.NELUMBO_LANTERNS: 1042,
    ItemName.CRYSTAL_PICKUPS: 1043,
    ItemName.SWITCHES: 1044,
    ItemName.PLAYER_THROWERS: 1045
}

no_consolidation = {item: [item] for item in mechanic.keys() if mechanic[item] < 1000}

no_mechanics = {item: [] for item in mechanic.keys() if mechanic[item] < 1000}

consolidated_mechanics = {
    ItemName.DASH_CRYSTALS: [ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.TRAFFIC_BLOCKS: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.SPRINGS: [ItemName.GENERIC_SPRINGS],
    ItemName.BLUE_CASSETTE: [ItemName.CASSETTE_BLOCKS],
    ItemName.PINK_CASSETTE: [ItemName.CASSETTE_BLOCKS],
    ItemName.CRUMBLING_PLATFORM: [ItemName.CRUMBLING_PLATFORM],
    ItemName.TOUCH_SWITCH: [ItemName.GENERIC_TOUCH_SWITCH],
    ItemName.DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK],
    ItemName.BADELINE_ORB: [ItemName.BADELINE_ORB],
    ItemName.SINKING_PLATFORM: [ItemName.SINKING_PLATFORM],
    ItemName.GREEN_BUBBLES: [ItemName.BUBBLES],
    ItemName.CLOUDS: [ItemName.CLOUDS],
    ItemName.PINK_CLOUDS: [ItemName.CLOUDS],
    ItemName.MOVING_BLOCK: [ItemName.GENERIC_MOVE_BLOCK],
    ItemName.RED_BUBBLES: [ItemName.BUBBLES],
    ItemName.SWAP_BLOCK: [ItemName.GENERIC_SWAP_BLOCK],
    ItemName.DASH_SWITCH: [ItemName.GENERIC_DASH_SWITCH],
    ItemName.FEATHER: [ItemName.FEATHER],
    ItemName.MOVING_PLATFORM: [ItemName.MOVING_PLATFORM],
    ItemName.WHITE_BLOCK: [],
    ItemName.SEEKERS: [ItemName.SEEKERS],
    ItemName.THEO_CRYSTAL: [ItemName.HEAVY_THROWABLE],
    ItemName.KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.CORE_BLOCK: [ItemName.CORE_BLOCK],
    ItemName.CORE_SWITCH: [ItemName.FLIP_SWITCH],
    ItemName.LAVA_ICE_BALLS: [ItemName.LAVA_ICE_BALLS],
    ItemName.BREAKER_BOX: [ItemName.BREAKER_BOX],
    ItemName.BIRD: [ItemName.BIRD],
    ItemName.JELLYFISH: [ItemName.LIGHT_THROWABLE],
    ItemName.PUFFER_FISH: [ItemName.PUFFER_FISH],
    ItemName.DOUBLE_DASH_CRYSTALS: [ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.YELLOW_CASSETTE: [ItemName.CASSETTE_BLOCKS],
    ItemName.GREEN_CASSETTE: [ItemName.CASSETTE_BLOCKS],
    ItemName.LOOP_BLOCK: [ItemName.CLOUDS],
    ItemName.DREAM_DASH_CRYSTAL: [ItemName.GENERIC_DREAM_BLOCK, ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.INTRO_CRUSHER: [ItemName.INTRO_CRUSHER],
    ItemName.DASH_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.BLUE_TRAFFIC_CASSETTE: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.PINK_TRAFFIC_CASSETTE: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.YELLOW_TRAFFIC_CASSETTE: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.SOAP_BUBBLE: [ItemName.BUBBLES],
    ItemName.DASHLESS_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.SINGLE_JUMP_REFILL: [ItemName.JUMP_REFILL],
    ItemName.TRIPLE_JUMP_REFILL: [ItemName.JUMP_REFILL],
    ItemName.DOUBLE_DASH_DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK],
    ItemName.GREEN_SWITCH_BLOCK: [ItemName.SWITCH_BLOCK],
    ItemName.ORANGE_SWITCH_BLOCK: [ItemName.SWITCH_BLOCK],
    ItemName.SWITCH_BLOCK_SWITCH: [ItemName.SWITCH_BLOCK],
    ItemName.GRAVITY_FIELD: [ItemName.GRAVITY_MECHANICS],
    ItemName.BLUE_TIME_CRYSTAL: [ItemName.TIME_MECHANICS],
    ItemName.DASH_CRYSTAL_SHARDS: [ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.PIPES: [ItemName.PIPES],
    ItemName.BIG_YELLOW_BUTTON: [ItemName.GENERIC_DASH_SWITCH],
    ItemName.PUZZLE_KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.TRIPLE_BOOST_FLOWER: [ItemName.LIGHT_THROWABLE],
    ItemName.BOUNCE_DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK],
    ItemName.ORANGE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.BLUE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.TOGGLE_SWAP_BLOCK: [ItemName.GENERIC_SWAP_BLOCK],
    ItemName.GREEN_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.STRAWBERRY_JAM: [ItemName.HEAVY_THROWABLE],
    ItemName.NEON_BLUE_KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.NEON_PURPLE_KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.PUSH_BLOCK: [],
    ItemName.VERTIGO_LINKED_TELEPORT: [ItemName.PORTALS],
    ItemName.YELLOW_PORTAL: [ItemName.PORTALS],
    ItemName.PURPLE_PORTAL: [ItemName.PORTALS],
    ItemName.PUSH_STATION_BLOCK: [ItemName.STATION_BLOCKS],
    ItemName.BLUE_PORTAL: [ItemName.PORTALS],
    ItemName.RED_PORTAL: [ItemName.PORTALS],
    ItemName.TIMED_TOUCH_SWITCH: [ItemName.GENERIC_TOUCH_SWITCH],
    ItemName.HONEY_BUBBLES: [ItemName.BUBBLES],
    ItemName.ZIPLINE: [],
    ItemName.YELLOW_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.YELLOW_LASER: [ItemName.LASER],
    ItemName.TORQUOISE_LASER: [ItemName.LASER],
    ItemName.GREEN_LASER: [ItemName.LASER],
    ItemName.MAGENTA_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.TORQUOISE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.RED_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.CRYSTAL_BOMB: [ItemName.HEAVY_THROWABLE],
    ItemName.BOWL_PUFFER: [ItemName.HEAVY_THROWABLE, ItemName.PUFFER_FISH],
    ItemName.PURPLE_DASHLESS_BUBBLE: [ItemName.BUBBLES],
    ItemName.PULL_STATION_BLOCK: [ItemName.STATION_BLOCKS],
    ItemName.DASH_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.TRACK_SWITCH_BOX: [ItemName.STATION_BLOCKS],
    ItemName.PURPLE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.GRAY_TIME_CRYSTAL: [ItemName.TIME_MECHANICS],
    ItemName.PURPLE_JELLYFISH: [ItemName.LIGHT_THROWABLE],
    ItemName.DASH_REFILL_WALL: [ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.DOUBLE_DASH_REFILL_WALL: [ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.GRAY_BUBBLES: [ItemName.BUBBLES],
    ItemName.SWITCH_CRATE: [ItemName.HEAVY_THROWABLE],
    ItemName.GREEN_PORTAL: [ItemName.PORTALS],
    ItemName.MOVING_TOUCH_SWITCH: [ItemName.GENERIC_TOUCH_SWITCH],
    ItemName.DREAM_TRAFFIC_BLOCK: [ItemName.GENERIC_DREAM_BLOCK, ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.BOUNCY_SPIKES: [],
    ItemName.MOMENTUM_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.PURPLE_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS],
    ItemName.ORANGE_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS],
    ItemName.RED_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS],
    ItemName.GREEN_CASSETTE_TRAFFIC_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.PURPLE_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.BLUE_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.PURPLE_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.PINK_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.RED_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.ORANGE_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.ORANGE_CASSETTE_TRAFFIC_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.GREEN_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.RED_CASSETTE_TRAFFIC_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.YELLOW_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.PINK_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.GREEN_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.WORMHOLE_BUBBLE: [ItemName.BUBBLES],
    ItemName.FAKE_CRYSTAL_HEART: [ItemName.FAKE_CRYSTAL_HEART],
    ItemName.MINI_FAKE_CRYSTAL_HEART: [ItemName.FAKE_CRYSTAL_HEART],
    ItemName.THROW_BOX: [ItemName.HEAVY_THROWABLE],
    ItemName.PURPLE_REBOUND_BUBBLE: [ItemName.BUBBLES],
    ItemName.GROWTH_POTION: [ItemName.GENERIC_DASH_SWITCH],
    ItemName.BLUE_GRAVITY_SPRING: [ItemName.GENERIC_SPRINGS, ItemName.GRAVITY_MECHANICS],
    ItemName.RED_GRAVITY_SPRING: [ItemName.GENERIC_SPRINGS, ItemName.GRAVITY_MECHANICS],
    ItemName.PURPLE_GRAVITY_SPRING: [ItemName.GENERIC_SPRINGS, ItemName.GRAVITY_MECHANICS],
    ItemName.YELLOW_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.MOVE_BLOCK_ACCELERATOR_FIELD: [ItemName.GENERIC_MOVE_BLOCK],
    ItemName.MOVE_BLOCK_DELETE_FIELD: [ItemName.GENERIC_MOVE_BLOCK],
    ItemName.MOVE_BLOCK_DECELERATOR_FIELD: [ItemName.GENERIC_MOVE_BLOCK],
    ItemName.MOVE_BLOCK_REDIRECT_FIELD: [ItemName.GENERIC_MOVE_BLOCK],
    ItemName.DREAM_MOVE_BLOCK: [ItemName.GENERIC_MOVE_BLOCK, ItemName.GENERIC_DREAM_BLOCK],
    ItemName.BATTERY: [ItemName.HEAVY_THROWABLE],
    ItemName.RED_PROPELLER_BLOCK: [ItemName.HEAVY_THROWABLE],
    ItemName.YELLOW_PROPELLER_BLOCK: [ItemName.HEAVY_THROWABLE],
    ItemName.DASH_BOOST_FIELD: [ItemName.DASH_SPEEDUP_MECHANICS],
    ItemName.FORCE_JUMP_CRYSTAL: [ItemName.JUMP_REFILL],
    ItemName.NO_STAMINA_DASH_CRYSTAL: [ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.SPEED_MUSHROOMS: [ItemName.GENERIC_DASH_CRYSTAL, ItemName.DASH_SPEEDUP_MECHANICS],
    ItemName.SPEED_MUSHROOM_WALL: [ItemName.GENERIC_DASH_CRYSTAL, ItemName.DASH_SPEEDUP_MECHANICS],
    ItemName.WHITE_DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK],
    ItemName.RED_SPEED_MOSS: [ItemName.DASH_SPEEDUP_MECHANICS],
    ItemName.BLUE_BOUNCE_MOSS: [ItemName.GENERIC_SPRINGS],
    ItemName.WHITE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.SQUARE_BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.BLUE_FLOATING_FIELDS: [ItemName.GRAVITY_MECHANICS],
    ItemName.RED_FLOATING_FIELDS: [ItemName.GRAVITY_MECHANICS],
    ItemName.PURPLE_FLOATING_FIELDS: [ItemName.GRAVITY_MECHANICS],
    ItemName.BLUE_FLIP_SWITCH: [ItemName.FLIP_SWITCH],
    ItemName.GREEN_FLIP_SWITCH: [ItemName.FLIP_SWITCH],
    ItemName.PURPLE_FLIP_SWITCH: [ItemName.FLIP_SWITCH],
    ItemName.PINK_FLIP_SWITCH: [ItemName.FLIP_SWITCH],
    ItemName.RED_FLIP_SWITCH: [ItemName.FLIP_SWITCH],
    ItemName.PINK_SWITCH_BLOCK: [ItemName.SWITCH_BLOCK],
    ItemName.PURPLE_SWITCH_BLOCK: [ItemName.SWITCH_BLOCK],
    ItemName.RED_SWITCH_BLOCK: [ItemName.SWITCH_BLOCK],
    ItemName.CLOUD_CRYSTAL: [ItemName.CLOUDS, ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.JELLY_CRYSTAL: [ItemName.LIGHT_THROWABLE, ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.STOPWATCH_CRYSTAL: [ItemName.TIME_MECHANICS],
    ItemName.CURVED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.SKY_LANTERN: [ItemName.LIGHT_THROWABLE],
    ItemName.INFINITE_DASH_MOSAIC_CRYSTAL: [ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.BLUE_STOPWATCH: [ItemName.TIME_MECHANICS],
    ItemName.GREEN_STOPWATCH: [ItemName.TIME_MECHANICS],
    ItemName.GRAY_STOPWATCH: [ItemName.TIME_MECHANICS],
    ItemName.BUBBLE_EMITTER: [],
    ItemName.CANNON_BALL: [ItemName.HEAVY_THROWABLE],
    ItemName.INFINITE_DASH_FIELD: [],
    ItemName.JUMP_REFILL_WALL: [ItemName.JUMP_REFILL],
    ItemName.ONE_USE_BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.DOUBLE_DASH_BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.MOVING_BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.YELLOW_ROCK: [ItemName.HEAVY_THROWABLE],
    ItemName.BACKGROUND_SWITCH: [ItemName.FLIP_SWITCH],
    ItemName.RED_DRUM: [ItemName.GENERIC_SWAP_BLOCK],
    ItemName.TOGGLE_DRUM: [ItemName.GENERIC_SWAP_BLOCK],
    ItemName.BLUE_FLYING_LANTERN: [ItemName.LIGHT_THROWABLE],
    ItemName.RED_FLYING_LANTERN: [ItemName.LIGHT_THROWABLE],
    ItemName.SILVER_PORTAL: [ItemName.PORTALS],
    ItemName.NAVY_PORTAL: [ItemName.PORTALS]
}

consolidated_mechanics_colors = {
    ItemName.DASH_CRYSTALS: [ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.TRAFFIC_BLOCKS: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.SPRINGS: [ItemName.GENERIC_SPRINGS],
    ItemName.BLUE_CASSETTE: [ItemName.CASSETTE_BLOCKS, ItemName.BLUE],
    ItemName.PINK_CASSETTE: [ItemName.CASSETTE_BLOCKS, ItemName.PINK],
    ItemName.CRUMBLING_PLATFORM: [ItemName.CRUMBLING_PLATFORM],
    ItemName.TOUCH_SWITCH: [ItemName.GENERIC_TOUCH_SWITCH],
    ItemName.DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK],
    ItemName.BADELINE_ORB: [ItemName.BADELINE_ORB],
    ItemName.SINKING_PLATFORM: [ItemName.SINKING_PLATFORM],
    ItemName.GREEN_BUBBLES: [ItemName.BUBBLES],
    ItemName.CLOUDS: [ItemName.CLOUDS],
    ItemName.PINK_CLOUDS: [ItemName.CLOUDS],
    ItemName.MOVING_BLOCK: [ItemName.GENERIC_MOVE_BLOCK],
    ItemName.RED_BUBBLES: [ItemName.BUBBLES],
    ItemName.SWAP_BLOCK: [ItemName.GENERIC_SWAP_BLOCK],
    ItemName.DASH_SWITCH: [ItemName.GENERIC_DASH_SWITCH],
    ItemName.FEATHER: [ItemName.FEATHER],
    ItemName.MOVING_PLATFORM: [ItemName.MOVING_PLATFORM],
    ItemName.WHITE_BLOCK: [],
    ItemName.SEEKERS: [ItemName.SEEKERS],
    ItemName.THEO_CRYSTAL: [ItemName.HEAVY_THROWABLE],
    ItemName.KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.CORE_BLOCK: [ItemName.CORE_BLOCK],
    ItemName.CORE_SWITCH: [ItemName.FLIP_SWITCH],
    ItemName.LAVA_ICE_BALLS: [ItemName.LAVA_ICE_BALLS],
    ItemName.BREAKER_BOX: [ItemName.BREAKER_BOX],
    ItemName.BIRD: [ItemName.BIRD],
    ItemName.JELLYFISH: [ItemName.LIGHT_THROWABLE],
    ItemName.PUFFER_FISH: [ItemName.PUFFER_FISH],
    ItemName.DOUBLE_DASH_CRYSTALS: [ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.YELLOW_CASSETTE: [ItemName.CASSETTE_BLOCKS, ItemName.YELLOW],
    ItemName.GREEN_CASSETTE: [ItemName.CASSETTE_BLOCKS, ItemName.GREEN],
    ItemName.LOOP_BLOCK: [ItemName.CLOUDS],
    ItemName.DREAM_DASH_CRYSTAL: [ItemName.GENERIC_DREAM_BLOCK, ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.INTRO_CRUSHER: [ItemName.INTRO_CRUSHER],
    ItemName.DASH_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.BLUE_TRAFFIC_CASSETTE: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.BLUE],
    ItemName.PINK_TRAFFIC_CASSETTE: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.PINK],
    ItemName.YELLOW_TRAFFIC_CASSETTE: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.YELLOW],
    ItemName.SOAP_BUBBLE: [ItemName.BUBBLES],
    ItemName.DASHLESS_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.SINGLE_JUMP_REFILL: [ItemName.JUMP_REFILL],
    ItemName.TRIPLE_JUMP_REFILL: [ItemName.JUMP_REFILL],
    ItemName.DOUBLE_DASH_DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK],
    ItemName.GREEN_SWITCH_BLOCK: [ItemName.SWITCH_BLOCK, ItemName.GREEN],
    ItemName.ORANGE_SWITCH_BLOCK: [ItemName.SWITCH_BLOCK, ItemName.ORANGE],
    ItemName.SWITCH_BLOCK_SWITCH: [ItemName.SWITCH_BLOCK],
    ItemName.GRAVITY_FIELD: [ItemName.GRAVITY_MECHANICS],
    ItemName.BLUE_TIME_CRYSTAL: [ItemName.TIME_MECHANICS],
    ItemName.DASH_CRYSTAL_SHARDS: [ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.PIPES: [ItemName.PIPES],
    ItemName.BIG_YELLOW_BUTTON: [ItemName.GENERIC_DASH_SWITCH],
    ItemName.PUZZLE_KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.TRIPLE_BOOST_FLOWER: [ItemName.LIGHT_THROWABLE],
    ItemName.BOUNCE_DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK],
    ItemName.ORANGE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.ORANGE],
    ItemName.BLUE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.BLUE],
    ItemName.TOGGLE_SWAP_BLOCK: [ItemName.GENERIC_SWAP_BLOCK],
    ItemName.GREEN_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.GREEN],
    ItemName.STRAWBERRY_JAM: [ItemName.HEAVY_THROWABLE],
    ItemName.NEON_BLUE_KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.NEON_PURPLE_KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.PUSH_BLOCK: [],
    ItemName.VERTIGO_LINKED_TELEPORT: [ItemName.PORTALS],
    ItemName.YELLOW_PORTAL: [ItemName.PORTALS, ItemName.YELLOW],
    ItemName.PURPLE_PORTAL: [ItemName.PORTALS, ItemName.PURPLE],
    ItemName.PUSH_STATION_BLOCK: [ItemName.STATION_BLOCKS],
    ItemName.BLUE_PORTAL: [ItemName.PORTALS, ItemName.BLUE],
    ItemName.RED_PORTAL: [ItemName.PORTALS, ItemName.RED],
    ItemName.TIMED_TOUCH_SWITCH: [ItemName.GENERIC_TOUCH_SWITCH],
    ItemName.HONEY_BUBBLES: [ItemName.BUBBLES],
    ItemName.ZIPLINE: [],
    ItemName.YELLOW_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.YELLOW],
    ItemName.YELLOW_LASER: [ItemName.LASER, ItemName.YELLOW],
    ItemName.TORQUOISE_LASER: [ItemName.LASER, ItemName.BLUE],
    ItemName.GREEN_LASER: [ItemName.LASER, ItemName.GREEN],
    ItemName.MAGENTA_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.PURPLE],
    ItemName.TORQUOISE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.BLUE],
    ItemName.RED_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.RED],
    ItemName.CRYSTAL_BOMB: [ItemName.HEAVY_THROWABLE],
    ItemName.BOWL_PUFFER: [ItemName.HEAVY_THROWABLE, ItemName.PUFFER_FISH],
    ItemName.PURPLE_DASHLESS_BUBBLE: [ItemName.BUBBLES],
    ItemName.PULL_STATION_BLOCK: [ItemName.STATION_BLOCKS],
    ItemName.DASH_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.TRACK_SWITCH_BOX: [ItemName.STATION_BLOCKS],
    ItemName.PURPLE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.PURPLE],
    ItemName.GRAY_TIME_CRYSTAL: [ItemName.TIME_MECHANICS],
    ItemName.PURPLE_JELLYFISH: [ItemName.LIGHT_THROWABLE],
    ItemName.DASH_REFILL_WALL: [ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.DOUBLE_DASH_REFILL_WALL: [ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.GRAY_BUBBLES: [ItemName.BUBBLES],
    ItemName.SWITCH_CRATE: [ItemName.HEAVY_THROWABLE],
    ItemName.GREEN_PORTAL: [ItemName.PORTALS, ItemName.GREEN],
    ItemName.MOVING_TOUCH_SWITCH: [ItemName.GENERIC_TOUCH_SWITCH],
    ItemName.DREAM_TRAFFIC_BLOCK: [ItemName.GENERIC_DREAM_BLOCK, ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.BOUNCY_SPIKES: [],
    ItemName.MOMENTUM_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.PURPLE_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.PURPLE],
    ItemName.ORANGE_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.ORANGE],
    ItemName.RED_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.RED],
    ItemName.GREEN_CASSETTE_TRAFFIC_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.GREEN],
    ItemName.PURPLE_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK, ItemName.PURPLE],
    ItemName.BLUE_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK, ItemName.BLUE],
    ItemName.PURPLE_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK, ItemName.PURPLE],
    ItemName.PINK_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK, ItemName.PINK],
    ItemName.RED_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK, ItemName.RED],
    ItemName.ORANGE_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK, ItemName.ORANGE],
    ItemName.ORANGE_CASSETTE_TRAFFIC_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.ORANGE],
    ItemName.GREEN_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK, ItemName.GREEN],
    ItemName.RED_CASSETTE_TRAFFIC_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.RED],
    ItemName.YELLOW_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK, ItemName.YELLOW],
    ItemName.PINK_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK, ItemName.PINK],
    ItemName.GREEN_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK, ItemName.GREEN],
    ItemName.WORMHOLE_BUBBLE: [ItemName.BUBBLES],
    ItemName.FAKE_CRYSTAL_HEART: [ItemName.FAKE_CRYSTAL_HEART],
    ItemName.MINI_FAKE_CRYSTAL_HEART: [ItemName.FAKE_CRYSTAL_HEART],
    ItemName.THROW_BOX: [ItemName.HEAVY_THROWABLE],
    ItemName.PURPLE_REBOUND_BUBBLE: [ItemName.BUBBLES],
    ItemName.GROWTH_POTION: [ItemName.GENERIC_DASH_SWITCH],
    ItemName.BLUE_GRAVITY_SPRING: [ItemName.GENERIC_SPRINGS, ItemName.GRAVITY_MECHANICS],
    ItemName.RED_GRAVITY_SPRING: [ItemName.GENERIC_SPRINGS, ItemName.GRAVITY_MECHANICS],
    ItemName.PURPLE_GRAVITY_SPRING: [ItemName.GENERIC_SPRINGS, ItemName.GRAVITY_MECHANICS],
    ItemName.YELLOW_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK, ItemName.YELLOW],
    ItemName.MOVE_BLOCK_ACCELERATOR_FIELD: [ItemName.GENERIC_MOVE_BLOCK],
    ItemName.MOVE_BLOCK_DELETE_FIELD: [ItemName.GENERIC_MOVE_BLOCK],
    ItemName.MOVE_BLOCK_DECELERATOR_FIELD: [ItemName.GENERIC_MOVE_BLOCK],
    ItemName.MOVE_BLOCK_REDIRECT_FIELD: [ItemName.GENERIC_MOVE_BLOCK],
    ItemName.DREAM_MOVE_BLOCK: [ItemName.GENERIC_MOVE_BLOCK, ItemName.GENERIC_DREAM_BLOCK],
    ItemName.BATTERY: [ItemName.HEAVY_THROWABLE],
    ItemName.RED_PROPELLER_BLOCK: [ItemName.HEAVY_THROWABLE],
    ItemName.YELLOW_PROPELLER_BLOCK: [ItemName.HEAVY_THROWABLE],
    ItemName.DASH_BOOST_FIELD: [ItemName.DASH_SPEEDUP_MECHANICS],
    ItemName.FORCE_JUMP_CRYSTAL: [ItemName.JUMP_REFILL],
    ItemName.NO_STAMINA_DASH_CRYSTAL: [ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.SPEED_MUSHROOMS: [ItemName.GENERIC_DASH_CRYSTAL, ItemName.DASH_SPEEDUP_MECHANICS],
    ItemName.SPEED_MUSHROOM_WALL: [ItemName.GENERIC_DASH_CRYSTAL, ItemName.DASH_SPEEDUP_MECHANICS],
    ItemName.WHITE_DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK],
    ItemName.RED_SPEED_MOSS: [ItemName.DASH_SPEEDUP_MECHANICS],
    ItemName.BLUE_BOUNCE_MOSS: [ItemName.GENERIC_SPRINGS],
    ItemName.WHITE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.WHITE],
    ItemName.SQUARE_BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.BLUE_FLOATING_FIELDS: [ItemName.GRAVITY_MECHANICS],
    ItemName.RED_FLOATING_FIELDS: [ItemName.GRAVITY_MECHANICS],
    ItemName.PURPLE_FLOATING_FIELDS: [ItemName.GRAVITY_MECHANICS],
    ItemName.BLUE_FLIP_SWITCH: [ItemName.FLIP_SWITCH, ItemName.BLUE],
    ItemName.GREEN_FLIP_SWITCH: [ItemName.FLIP_SWITCH, ItemName.GREEN],
    ItemName.PURPLE_FLIP_SWITCH: [ItemName.FLIP_SWITCH, ItemName.PURPLE],
    ItemName.PINK_FLIP_SWITCH: [ItemName.FLIP_SWITCH, ItemName.PINK],
    ItemName.RED_FLIP_SWITCH: [ItemName.FLIP_SWITCH, ItemName.RED],
    ItemName.PINK_SWITCH_BLOCK: [ItemName.SWITCH_BLOCK, ItemName.PINK],
    ItemName.PURPLE_SWITCH_BLOCK: [ItemName.SWITCH_BLOCK, ItemName.PURPLE],
    ItemName.RED_SWITCH_BLOCK: [ItemName.SWITCH_BLOCK, ItemName.RED],
    ItemName.CLOUD_CRYSTAL: [ItemName.CLOUDS, ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.JELLY_CRYSTAL: [ItemName.LIGHT_THROWABLE, ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.STOPWATCH_CRYSTAL: [ItemName.TIME_MECHANICS],
    ItemName.CURVED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.SKY_LANTERN: [ItemName.LIGHT_THROWABLE],
    ItemName.INFINITE_DASH_MOSAIC_CRYSTAL: [ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.BLUE_STOPWATCH: [ItemName.TIME_MECHANICS],
    ItemName.GREEN_STOPWATCH: [ItemName.TIME_MECHANICS],
    ItemName.GRAY_STOPWATCH: [ItemName.TIME_MECHANICS],
    ItemName.BUBBLE_EMITTER: [],
    ItemName.CANNON_BALL: [ItemName.HEAVY_THROWABLE],
    ItemName.INFINITE_DASH_FIELD: [],
    ItemName.JUMP_REFILL_WALL: [ItemName.JUMP_REFILL],
    ItemName.ONE_USE_BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.DOUBLE_DASH_BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.MOVING_BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.YELLOW_ROCK: [ItemName.HEAVY_THROWABLE],
    ItemName.BACKGROUND_SWITCH: [ItemName.FLIP_SWITCH],
    ItemName.RED_DRUM: [ItemName.GENERIC_SWAP_BLOCK],
    ItemName.TOGGLE_DRUM: [ItemName.GENERIC_SWAP_BLOCK],
    ItemName.BLUE_FLYING_LANTERN: [ItemName.LIGHT_THROWABLE],
    ItemName.RED_FLYING_LANTERN: [ItemName.LIGHT_THROWABLE],
    ItemName.SILVER_PORTAL: [ItemName.PORTALS],
    ItemName.NAVY_PORTAL: [ItemName.PORTALS, ItemName.BLUE]
}

consolidated_mechanics_minimal = {
    ItemName.DASH_CRYSTALS: [ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.TRAFFIC_BLOCKS: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.SPRINGS: [ItemName.GENERIC_SPRINGS],
    ItemName.BLUE_CASSETTE: [ItemName.CASSETTE_BLOCKS],
    ItemName.PINK_CASSETTE: [ItemName.CASSETTE_BLOCKS],
    ItemName.CRUMBLING_PLATFORM: [ItemName.CRUMBLING_PLATFORM],
    ItemName.TOUCH_SWITCH: [ItemName.GENERIC_TOUCH_SWITCH],
    ItemName.DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK],
    ItemName.BADELINE_ORB: [ItemName.BADELINE_ORB],
    ItemName.SINKING_PLATFORM: [ItemName.SINKING_PLATFORM],
    ItemName.GREEN_BUBBLES: [ItemName.GENERIC_SHORT_BUBBLES],
    ItemName.CLOUDS: [ItemName.CLOUDS],
    ItemName.PINK_CLOUDS: [ItemName.CLOUDS],
    ItemName.MOVING_BLOCK: [ItemName.GENERIC_MOVE_BLOCK],
    ItemName.RED_BUBBLES: [ItemName.GENERIC_LONG_BUBBLES],
    ItemName.SWAP_BLOCK: [ItemName.GENERIC_SWAP_BLOCK],
    ItemName.DASH_SWITCH: [ItemName.GENERIC_DASH_SWITCH],
    ItemName.FEATHER: [ItemName.FEATHER],
    ItemName.MOVING_PLATFORM: [ItemName.MOVING_PLATFORM],
    ItemName.WHITE_BLOCK: [ItemName.WHITE_BLOCK],
    ItemName.SEEKERS: [ItemName.SEEKERS],
    ItemName.THEO_CRYSTAL: [ItemName.THEO_CRYSTAL],
    ItemName.KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.CORE_BLOCK: [ItemName.CORE_BLOCK],
    ItemName.CORE_SWITCH: [ItemName.CORE_SWITCH],
    ItemName.LAVA_ICE_BALLS: [ItemName.LAVA_ICE_BALLS],
    ItemName.BREAKER_BOX: [ItemName.BREAKER_BOX],
    ItemName.BIRD: [ItemName.BIRD],
    ItemName.JELLYFISH: [ItemName.JELLYFISH],
    ItemName.PUFFER_FISH: [ItemName.PUFFER_FISH],
    ItemName.DOUBLE_DASH_CRYSTALS: [ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.YELLOW_CASSETTE: [ItemName.CASSETTE_BLOCKS],
    ItemName.GREEN_CASSETTE: [ItemName.CASSETTE_BLOCKS],
    ItemName.LOOP_BLOCK: [ItemName.LOOP_BLOCK],
    ItemName.DREAM_DASH_CRYSTAL: [ItemName.GENERIC_DREAM_BLOCK, ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.INTRO_CRUSHER: [ItemName.INTRO_CRUSHER],
    ItemName.DASH_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.BLUE_TRAFFIC_CASSETTE: [ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.CASSETTE_BLOCKS],
    ItemName.PINK_TRAFFIC_CASSETTE: [ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.CASSETTE_BLOCKS],
    ItemName.YELLOW_TRAFFIC_CASSETTE: [ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.CASSETTE_BLOCKS],
    ItemName.SOAP_BUBBLE: [ItemName.GENERIC_SHORT_BUBBLES],
    ItemName.DASHLESS_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.SINGLE_JUMP_REFILL: [ItemName.JUMP_REFILL],
    ItemName.TRIPLE_JUMP_REFILL: [ItemName.JUMP_REFILL],
    ItemName.DOUBLE_DASH_DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK],
    ItemName.GREEN_SWITCH_BLOCK: [ItemName.SWITCH_BLOCK],
    ItemName.ORANGE_SWITCH_BLOCK: [ItemName.SWITCH_BLOCK],
    ItemName.SWITCH_BLOCK_SWITCH: [ItemName.SWITCH_BLOCK],
    ItemName.GRAVITY_FIELD: [ItemName.GRAVITY_FIELD],
    ItemName.BLUE_TIME_CRYSTAL: [ItemName.GENERIC_TIME_CRYSTAL],
    ItemName.DASH_CRYSTAL_SHARDS: [ItemName.DASH_CRYSTAL_SHARDS],
    ItemName.PIPES: [ItemName.PIPES],
    ItemName.BIG_YELLOW_BUTTON: [ItemName.BIG_YELLOW_BUTTON],
    ItemName.PUZZLE_KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.TRIPLE_BOOST_FLOWER: [ItemName.TRIPLE_BOOST_FLOWER],
    ItemName.BOUNCE_DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK],
    ItemName.ORANGE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.BLUE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.TOGGLE_SWAP_BLOCK: [ItemName.SWAP_BLOCK],
    ItemName.GREEN_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.STRAWBERRY_JAM: [ItemName.STRAWBERRY_JAM],
    ItemName.NEON_BLUE_KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.NEON_PURPLE_KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.PUSH_BLOCK: [ItemName.PUSH_BLOCK],
    ItemName.VERTIGO_LINKED_TELEPORT: [ItemName.VERTIGO_LINKED_TELEPORT],
    ItemName.YELLOW_PORTAL: [ItemName.PORTALS],
    ItemName.PURPLE_PORTAL: [ItemName.PORTALS],
    ItemName.PUSH_STATION_BLOCK: [ItemName.STATION_BLOCKS],
    ItemName.BLUE_PORTAL: [ItemName.PORTALS],
    ItemName.RED_PORTAL: [ItemName.PORTALS],
    ItemName.TIMED_TOUCH_SWITCH: [ItemName.TOUCH_SWITCH],
    ItemName.HONEY_BUBBLES: [ItemName.GENERIC_LONG_BUBBLES],
    ItemName.ZIPLINE: [ItemName.ZIPLINE],
    ItemName.YELLOW_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.YELLOW_LASER: [ItemName.LASER],
    ItemName.TORQUOISE_LASER: [ItemName.LASER],
    ItemName.GREEN_LASER: [ItemName.LASER],
    ItemName.MAGENTA_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.TORQUOISE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.RED_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.CRYSTAL_BOMB: [ItemName.CRYSTAL_BOMB],
    ItemName.BOWL_PUFFER: [ItemName.BOWL_PUFFER],
    ItemName.PURPLE_DASHLESS_BUBBLE: [ItemName.GENERIC_LONG_BUBBLES],
    ItemName.PULL_STATION_BLOCK: [ItemName.STATION_BLOCKS],
    ItemName.DASH_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.TRACK_SWITCH_BOX: [ItemName.TRACK_SWITCH_BOX],
    ItemName.PURPLE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.GRAY_TIME_CRYSTAL: [ItemName.GENERIC_TIME_CRYSTAL],
    ItemName.PURPLE_JELLYFISH: [ItemName.JELLYFISH],
    ItemName.DASH_REFILL_WALL: [ItemName.GENERIC_REFILL_WALL, ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.DOUBLE_DASH_REFILL_WALL: [ItemName.GENERIC_REFILL_WALL, ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.GRAY_BUBBLES: [ItemName.GENERIC_SHORT_BUBBLES],
    ItemName.SWITCH_CRATE: [ItemName.SWITCH_CRATE],
    ItemName.GREEN_PORTAL: [ItemName.PORTALS],
    ItemName.MOVING_TOUCH_SWITCH: [ItemName.TOUCH_SWITCH],
    ItemName.DREAM_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.GENERIC_DREAM_BLOCK],
    ItemName.BOUNCY_SPIKES: [ItemName.BOUNCY_SPIKES],
    ItemName.MOMENTUM_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.PURPLE_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS],
    ItemName.ORANGE_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS],
    ItemName.RED_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS],
    ItemName.GREEN_CASSETTE_TRAFFIC_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.PURPLE_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.BLUE_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.PURPLE_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.PINK_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.RED_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.ORANGE_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.ORANGE_CASSETTE_TRAFFIC_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.GREEN_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.RED_CASSETTE_TRAFFIC_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.YELLOW_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.PINK_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.GREEN_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.WORMHOLE_BUBBLE: [ItemName.GENERIC_SHORT_BUBBLES],
    ItemName.FAKE_CRYSTAL_HEART: [ItemName.FAKE_CRYSTAL_HEART],
    ItemName.MINI_FAKE_CRYSTAL_HEART: [ItemName.FAKE_CRYSTAL_HEART],
    ItemName.THROW_BOX: [ItemName.THROW_BOX],
    ItemName.PURPLE_REBOUND_BUBBLE: [ItemName.GENERIC_REBOUND_BUBBLES],
    ItemName.GROWTH_POTION: [ItemName.GROWTH_POTION],
    ItemName.BLUE_GRAVITY_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.RED_GRAVITY_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.PURPLE_GRAVITY_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.YELLOW_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.MOVE_BLOCK_ACCELERATOR_FIELD: [ItemName.GENERIC_MOVE_BLOCK_MODIFIER],
    ItemName.MOVE_BLOCK_DELETE_FIELD: [ItemName.GENERIC_MOVE_BLOCK_MODIFIER],
    ItemName.MOVE_BLOCK_DECELERATOR_FIELD: [ItemName.GENERIC_MOVE_BLOCK_MODIFIER],
    ItemName.MOVE_BLOCK_REDIRECT_FIELD: [ItemName.GENERIC_MOVE_BLOCK_MODIFIER],
    ItemName.DREAM_MOVE_BLOCK: [ItemName.GENERIC_MOVE_BLOCK, ItemName.GENERIC_DREAM_BLOCK],
    ItemName.BATTERY: [ItemName.BATTERY],
    ItemName.RED_PROPELLER_BLOCK: [ItemName.PROPELLER_BLOCK],
    ItemName.YELLOW_PROPELLER_BLOCK: [ItemName.PROPELLER_BLOCK],
    ItemName.DASH_BOOST_FIELD: [ItemName.DASH_BOOST_FIELD],
    ItemName.FORCE_JUMP_CRYSTAL: [ItemName.FORCE_JUMP_CRYSTAL],
    ItemName.NO_STAMINA_DASH_CRYSTAL: [ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.SPEED_MUSHROOMS: [ItemName.SPEED_MUSHROOMS],
    ItemName.SPEED_MUSHROOM_WALL: [ItemName.SPEED_MUSHROOMS, ItemName.GENERIC_REFILL_WALL],
    ItemName.WHITE_DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK],
    ItemName.RED_SPEED_MOSS: [ItemName.MOVEMENT_MOSS],
    ItemName.BLUE_BOUNCE_MOSS: [ItemName.MOVEMENT_MOSS],
    ItemName.WHITE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.SQUARE_BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.BLUE_FLOATING_FIELDS: [ItemName.FLOATING_FIELDS],
    ItemName.RED_FLOATING_FIELDS: [ItemName.FLOATING_FIELDS],
    ItemName.PURPLE_FLOATING_FIELDS: [ItemName.FLOATING_FIELDS],
    ItemName.BLUE_FLIP_SWITCH: [ItemName.FLIP_SWITCH],
    ItemName.GREEN_FLIP_SWITCH: [ItemName.FLIP_SWITCH],
    ItemName.PURPLE_FLIP_SWITCH: [ItemName.FLIP_SWITCH],
    ItemName.PINK_FLIP_SWITCH: [ItemName.FLIP_SWITCH],
    ItemName.RED_FLIP_SWITCH: [ItemName.FLIP_SWITCH],
    ItemName.PINK_SWITCH_BLOCK: [ItemName.SWITCH_BLOCK],
    ItemName.PURPLE_SWITCH_BLOCK: [ItemName.SWITCH_BLOCK],
    ItemName.RED_SWITCH_BLOCK: [ItemName.SWITCH_BLOCK],
    ItemName.CLOUD_CRYSTAL: [ItemName.CLOUDS],
    ItemName.JELLY_CRYSTAL: [ItemName.JELLYFISH],
    ItemName.STOPWATCH_CRYSTAL: [ItemName.STOPWATCH_CRYSTAL],
    ItemName.CURVED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.SKY_LANTERN: [ItemName.SKY_LANTERN],
    ItemName.INFINITE_DASH_MOSAIC_CRYSTAL: [ItemName.GENERIC_DASH_CRYSTAL],
    ItemName.BLUE_STOPWATCH: [ItemName.LUNAR_PAGODA_STOPWATCH],
    ItemName.GREEN_STOPWATCH: [ItemName.LUNAR_PAGODA_STOPWATCH],
    ItemName.GRAY_STOPWATCH: [ItemName.LUNAR_PAGODA_STOPWATCH],
    ItemName.BUBBLE_EMITTER: [ItemName.BUBBLE_EMITTER],
    ItemName.CANNON_BALL: [ItemName.CANNON_BALL],
    ItemName.INFINITE_DASH_FIELD: [ItemName.INFINITE_DASH_FIELD],
    ItemName.JUMP_REFILL_WALL: [ItemName.JUMP_REFILL, ItemName.GENERIC_REFILL_WALL],
    ItemName.ONE_USE_BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.DOUBLE_DASH_BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.MOVING_BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.YELLOW_ROCK: [ItemName.YELLOW_ROCK],
    ItemName.BACKGROUND_SWITCH: [ItemName.BACKGROUND_SWITCH],
    ItemName.RED_DRUM: [ItemName.NELUMBO_DRUMS],
    ItemName.TOGGLE_DRUM: [ItemName.NELUMBO_DRUMS],
    ItemName.BLUE_FLYING_LANTERN: [ItemName.NELUMBO_LANTERNS],
    ItemName.RED_FLYING_LANTERN: [ItemName.NELUMBO_LANTERNS],
    ItemName.SILVER_PORTAL: [ItemName.PORTALS],
    ItemName.NAVY_PORTAL: [ItemName.PORTALS]
}

extreme_consolidation = {
    ItemName.DASH_CRYSTALS: [ItemName.CRYSTAL_PICKUPS],
    ItemName.TRAFFIC_BLOCKS: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.SPRINGS: [ItemName.GENERIC_SPRINGS],
    ItemName.BLUE_CASSETTE: [ItemName.CASSETTE_BLOCKS],
    ItemName.PINK_CASSETTE: [ItemName.CASSETTE_BLOCKS],
    ItemName.CRUMBLING_PLATFORM: [],
    ItemName.TOUCH_SWITCH: [ItemName.SWITCHES],
    ItemName.DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK],
    ItemName.BADELINE_ORB: [ItemName.PLAYER_THROWERS],
    ItemName.SINKING_PLATFORM: [ItemName.MOVING_PLATFORM],
    ItemName.GREEN_BUBBLES: [ItemName.BUBBLES],
    ItemName.CLOUDS: [ItemName.CLOUDS],
    ItemName.PINK_CLOUDS: [ItemName.CLOUDS],
    ItemName.MOVING_BLOCK: [ItemName.GENERIC_MOVE_BLOCK],
    ItemName.RED_BUBBLES: [ItemName.BUBBLES],
    ItemName.SWAP_BLOCK: [ItemName.GENERIC_SWAP_BLOCK],
    ItemName.DASH_SWITCH: [ItemName.SWITCHES],
    ItemName.FEATHER: [ItemName.FEATHER],
    ItemName.MOVING_PLATFORM: [ItemName.MOVING_PLATFORM],
    ItemName.WHITE_BLOCK: [],
    ItemName.SEEKERS: [],
    ItemName.THEO_CRYSTAL: [],
    ItemName.KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.CORE_BLOCK: [ItemName.CORE_BLOCK],
    ItemName.CORE_SWITCH: [],
    ItemName.LAVA_ICE_BALLS: [],
    ItemName.BREAKER_BOX: [],
    ItemName.BIRD: [ItemName.PLAYER_THROWERS],
    ItemName.JELLYFISH: [],
    ItemName.PUFFER_FISH: [ItemName.PUFFER_FISH],
    ItemName.DOUBLE_DASH_CRYSTALS: [ItemName.CRYSTAL_PICKUPS],
    ItemName.YELLOW_CASSETTE: [ItemName.CASSETTE_BLOCKS],
    ItemName.GREEN_CASSETTE: [ItemName.CASSETTE_BLOCKS],
    ItemName.LOOP_BLOCK: [],
    ItemName.DREAM_DASH_CRYSTAL: [ItemName.CRYSTAL_PICKUPS],
    ItemName.INTRO_CRUSHER: [],
    ItemName.DASH_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.BLUE_TRAFFIC_CASSETTE: [ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.CASSETTE_BLOCKS],
    ItemName.PINK_TRAFFIC_CASSETTE: [ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.CASSETTE_BLOCKS],
    ItemName.YELLOW_TRAFFIC_CASSETTE: [ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.CASSETTE_BLOCKS],
    ItemName.SOAP_BUBBLE: [ItemName.BUBBLES],
    ItemName.DASHLESS_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.SINGLE_JUMP_REFILL: [ItemName.CRYSTAL_PICKUPS],
    ItemName.TRIPLE_JUMP_REFILL: [ItemName.CRYSTAL_PICKUPS],
    ItemName.DOUBLE_DASH_DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK],
    ItemName.GREEN_SWITCH_BLOCK: [ItemName.CASSETTE_BLOCKS],
    ItemName.ORANGE_SWITCH_BLOCK: [ItemName.CASSETTE_BLOCKS],
    ItemName.SWITCH_BLOCK_SWITCH: [],
    ItemName.GRAVITY_FIELD: [],
    ItemName.BLUE_TIME_CRYSTAL: [ItemName.CRYSTAL_PICKUPS],
    ItemName.DASH_CRYSTAL_SHARDS: [ItemName.CRYSTAL_PICKUPS],
    ItemName.PIPES: [],
    ItemName.BIG_YELLOW_BUTTON: [ItemName.SWITCHES],
    ItemName.PUZZLE_KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.TRIPLE_BOOST_FLOWER: [],
    ItemName.BOUNCE_DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK],
    ItemName.ORANGE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.BLUE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.TOGGLE_SWAP_BLOCK: [ItemName.GENERIC_SWAP_BLOCK],
    ItemName.GREEN_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.STRAWBERRY_JAM: [],
    ItemName.NEON_BLUE_KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.NEON_PURPLE_KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.PUSH_BLOCK: [],
    ItemName.VERTIGO_LINKED_TELEPORT: [],
    ItemName.YELLOW_PORTAL: [ItemName.PORTALS],
    ItemName.PURPLE_PORTAL: [ItemName.PORTALS],
    ItemName.PUSH_STATION_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.BLUE_PORTAL: [ItemName.PORTALS],
    ItemName.RED_PORTAL: [ItemName.PORTALS],
    ItemName.TIMED_TOUCH_SWITCH: [ItemName.SWITCHES],
    ItemName.HONEY_BUBBLES: [ItemName.BUBBLES],
    ItemName.ZIPLINE: [],
    ItemName.YELLOW_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.YELLOW_LASER: [],
    ItemName.TORQUOISE_LASER: [],
    ItemName.GREEN_LASER: [],
    ItemName.MAGENTA_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.TORQUOISE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.RED_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.CRYSTAL_BOMB: [],
    ItemName.BOWL_PUFFER: [ItemName.PUFFER_FISH],
    ItemName.PURPLE_DASHLESS_BUBBLE: [ItemName.BUBBLES],
    ItemName.PULL_STATION_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.DASH_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.TRACK_SWITCH_BOX: [],
    ItemName.PURPLE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.GRAY_TIME_CRYSTAL: [ItemName.CRYSTAL_PICKUPS],
    ItemName.PURPLE_JELLYFISH: [],
    ItemName.DASH_REFILL_WALL: [ItemName.CRYSTAL_PICKUPS],
    ItemName.DOUBLE_DASH_REFILL_WALL: [ItemName.CRYSTAL_PICKUPS],
    ItemName.GRAY_BUBBLES: [ItemName.BUBBLES],
    ItemName.SWITCH_CRATE: [],
    ItemName.GREEN_PORTAL: [ItemName.PORTALS],
    ItemName.MOVING_TOUCH_SWITCH: [ItemName.SWITCHES],
    ItemName.DREAM_TRAFFIC_BLOCK: [ItemName.GENERIC_DREAM_BLOCK, ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.BOUNCY_SPIKES: [],
    ItemName.MOMENTUM_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.PURPLE_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS],
    ItemName.ORANGE_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS],
    ItemName.RED_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS],
    ItemName.GREEN_CASSETTE_TRAFFIC_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.PURPLE_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.BLUE_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.PURPLE_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.PINK_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.RED_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.ORANGE_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.ORANGE_CASSETTE_TRAFFIC_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.GREEN_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.RED_CASSETTE_TRAFFIC_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.YELLOW_CASSETTE_SWAP_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.PINK_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.GREEN_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.WORMHOLE_BUBBLE: [ItemName.BUBBLES],
    ItemName.FAKE_CRYSTAL_HEART: [],
    ItemName.MINI_FAKE_CRYSTAL_HEART: [],
    ItemName.THROW_BOX: [],
    ItemName.PURPLE_REBOUND_BUBBLE: [ItemName.BUBBLES],
    ItemName.GROWTH_POTION: [ItemName.SWITCHES],
    ItemName.BLUE_GRAVITY_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.RED_GRAVITY_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.PURPLE_GRAVITY_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.YELLOW_MOVING_CASSETTE_BLOCK: [ItemName.CASSETTE_BLOCKS, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.MOVE_BLOCK_ACCELERATOR_FIELD: [],
    ItemName.MOVE_BLOCK_DELETE_FIELD: [],
    ItemName.MOVE_BLOCK_DECELERATOR_FIELD: [],
    ItemName.MOVE_BLOCK_REDIRECT_FIELD: [],
    ItemName.DREAM_MOVE_BLOCK: [ItemName.GENERIC_DREAM_BLOCK, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.BATTERY: [],
    ItemName.RED_PROPELLER_BLOCK: [],
    ItemName.YELLOW_PROPELLER_BLOCK: [],
    ItemName.DASH_BOOST_FIELD: [],
    ItemName.FORCE_JUMP_CRYSTAL: [ItemName.CRYSTAL_PICKUPS],
    ItemName.NO_STAMINA_DASH_CRYSTAL: [ItemName.CRYSTAL_PICKUPS],
    ItemName.SPEED_MUSHROOMS: [ItemName.CRYSTAL_PICKUPS],
    ItemName.SPEED_MUSHROOM_WALL: [ItemName.CRYSTAL_PICKUPS],
    ItemName.WHITE_DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK],
    ItemName.RED_SPEED_MOSS: [],
    ItemName.BLUE_BOUNCE_MOSS: [],
    ItemName.WHITE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.SQUARE_BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.BLUE_FLOATING_FIELDS: [],
    ItemName.RED_FLOATING_FIELDS: [],
    ItemName.PURPLE_FLOATING_FIELDS: [],
    ItemName.BLUE_FLIP_SWITCH: [],
    ItemName.GREEN_FLIP_SWITCH: [],
    ItemName.PURPLE_FLIP_SWITCH: [],
    ItemName.PINK_FLIP_SWITCH: [],
    ItemName.RED_FLIP_SWITCH: [],
    ItemName.PINK_SWITCH_BLOCK: [ItemName.CASSETTE_BLOCKS],
    ItemName.PURPLE_SWITCH_BLOCK: [ItemName.CASSETTE_BLOCKS],
    ItemName.RED_SWITCH_BLOCK: [ItemName.CASSETTE_BLOCKS],
    ItemName.CLOUD_CRYSTAL: [ItemName.CRYSTAL_PICKUPS, ItemName.CLOUDS],
    ItemName.JELLY_CRYSTAL: [ItemName.CRYSTAL_PICKUPS],
    ItemName.STOPWATCH_CRYSTAL: [ItemName.CRYSTAL_PICKUPS],
    ItemName.CURVED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.SKY_LANTERN: [],
    ItemName.INFINITE_DASH_MOSAIC_CRYSTAL: [ItemName.CRYSTAL_PICKUPS],
    ItemName.BLUE_STOPWATCH: [ItemName.CRYSTAL_PICKUPS],
    ItemName.GREEN_STOPWATCH: [ItemName.CRYSTAL_PICKUPS],
    ItemName.GRAY_STOPWATCH: [ItemName.CRYSTAL_PICKUPS],
    ItemName.BUBBLE_EMITTER: [],
    ItemName.CANNON_BALL: [],
    ItemName.INFINITE_DASH_FIELD: [],
    ItemName.JUMP_REFILL_WALL: [ItemName.CRYSTAL_PICKUPS],
    ItemName.ONE_USE_BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.DOUBLE_DASH_BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.MOVING_BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.YELLOW_ROCK: [],
    ItemName.BACKGROUND_SWITCH: [],
    ItemName.RED_DRUM: [ItemName.GENERIC_SWAP_BLOCK],
    ItemName.TOGGLE_DRUM: [ItemName.GENERIC_SWAP_BLOCK],
    ItemName.BLUE_FLYING_LANTERN: [],
    ItemName.RED_FLYING_LANTERN: [],
    ItemName.SILVER_PORTAL: [ItemName.PORTALS],
    ItemName.NAVY_PORTAL: [ItemName.PORTALS]
}

vanilla_consolidation = {
    ItemName.DASH_CRYSTALS: [ItemName.DASH_CRYSTALS],
    ItemName.TRAFFIC_BLOCKS: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.SPRINGS: [ItemName.GENERIC_SPRINGS],
    ItemName.BLUE_CASSETTE: [ItemName.BLUE_CASSETTE],
    ItemName.PINK_CASSETTE: [ItemName.PINK_CASSETTE],
    ItemName.CRUMBLING_PLATFORM: [ItemName.CRUMBLING_PLATFORM],
    ItemName.TOUCH_SWITCH: [ItemName.GENERIC_TOUCH_SWITCH],
    ItemName.DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK],
    ItemName.BADELINE_ORB: [ItemName.BADELINE_ORB],
    ItemName.SINKING_PLATFORM: [ItemName.SINKING_PLATFORM],
    ItemName.GREEN_BUBBLES: [ItemName.GENERIC_SHORT_BUBBLES],
    ItemName.CLOUDS: [ItemName.CLOUDS],
    ItemName.PINK_CLOUDS: [ItemName.PINK_CLOUDS],
    ItemName.MOVING_BLOCK: [ItemName.GENERIC_MOVE_BLOCK],
    ItemName.RED_BUBBLES: [ItemName.GENERIC_LONG_BUBBLES],
    ItemName.SWAP_BLOCK: [ItemName.GENERIC_SWAP_BLOCK],
    ItemName.DASH_SWITCH: [ItemName.GENERIC_DASH_SWITCH],
    ItemName.FEATHER: [ItemName.FEATHER],
    ItemName.MOVING_PLATFORM: [ItemName.MOVING_PLATFORM],
    ItemName.WHITE_BLOCK: [ItemName.WHITE_BLOCK],
    ItemName.SEEKERS: [ItemName.SEEKERS],
    ItemName.THEO_CRYSTAL: [ItemName.THEO_CRYSTAL],
    ItemName.KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.CORE_BLOCK: [ItemName.CORE_BLOCK],
    ItemName.CORE_SWITCH: [ItemName.CORE_SWITCH],
    ItemName.LAVA_ICE_BALLS: [ItemName.LAVA_ICE_BALLS],
    ItemName.BREAKER_BOX: [ItemName.BREAKER_BOX],
    ItemName.BIRD: [ItemName.BIRD],
    ItemName.JELLYFISH: [ItemName.JELLYFISH],
    ItemName.PUFFER_FISH: [ItemName.PUFFER_FISH],
    ItemName.DOUBLE_DASH_CRYSTALS: [ItemName.DOUBLE_DASH_CRYSTALS],
    ItemName.YELLOW_CASSETTE: [ItemName.YELLOW_CASSETTE],
    ItemName.GREEN_CASSETTE: [ItemName.GREEN_CASSETTE],
    ItemName.LOOP_BLOCK: [],
    ItemName.DREAM_DASH_CRYSTAL: [ItemName.DASH_CRYSTALS, ItemName.GENERIC_DREAM_BLOCK],
    ItemName.INTRO_CRUSHER: [ItemName.INTRO_CRUSHER],
    ItemName.DASH_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.BLUE_TRAFFIC_CASSETTE: [ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.BLUE_CASSETTE],
    ItemName.PINK_TRAFFIC_CASSETTE: [ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.PINK_CASSETTE],
    ItemName.YELLOW_TRAFFIC_CASSETTE: [ItemName.GENERIC_TRAFFIC_BLOCK, ItemName.YELLOW_CASSETTE],
    ItemName.SOAP_BUBBLE: [ItemName.GENERIC_SHORT_BUBBLES],
    ItemName.DASHLESS_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.SINGLE_JUMP_REFILL: [ItemName.DASH_CRYSTALS],
    ItemName.TRIPLE_JUMP_REFILL: [ItemName.DOUBLE_DASH_CRYSTALS],
    ItemName.DOUBLE_DASH_DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK, ItemName.DOUBLE_DASH_CRYSTALS],
    ItemName.GREEN_SWITCH_BLOCK: [ItemName.GREEN_CASSETTE],
    ItemName.ORANGE_SWITCH_BLOCK: [ItemName.YELLOW_CASSETTE],
    ItemName.SWITCH_BLOCK_SWITCH: [],
    ItemName.GRAVITY_FIELD: [],
    ItemName.BLUE_TIME_CRYSTAL: [ItemName.DASH_CRYSTALS],
    ItemName.DASH_CRYSTAL_SHARDS: [ItemName.DASH_CRYSTALS],
    ItemName.PIPES: [],
    ItemName.BIG_YELLOW_BUTTON: [ItemName.GENERIC_DASH_SWITCH],
    ItemName.PUZZLE_KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.TRIPLE_BOOST_FLOWER: [ItemName.JELLYFISH],
    ItemName.BOUNCE_DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK],
    ItemName.ORANGE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.BLUE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.TOGGLE_SWAP_BLOCK: [ItemName.GENERIC_SWAP_BLOCK],
    ItemName.GREEN_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.STRAWBERRY_JAM: [ItemName.THEO_CRYSTAL],
    ItemName.NEON_BLUE_KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.NEON_PURPLE_KEVIN: [ItemName.GENERIC_KEVIN],
    ItemName.PUSH_BLOCK: [],
    ItemName.VERTIGO_LINKED_TELEPORT: [],
    ItemName.YELLOW_PORTAL: [],
    ItemName.PURPLE_PORTAL: [],
    ItemName.PUSH_STATION_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.BLUE_PORTAL: [],
    ItemName.RED_PORTAL: [],
    ItemName.TIMED_TOUCH_SWITCH: [ItemName.GENERIC_TOUCH_SWITCH],
    ItemName.HONEY_BUBBLES: [ItemName.GENERIC_SHORT_BUBBLES],
    ItemName.ZIPLINE: [],
    ItemName.YELLOW_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.YELLOW_LASER: [],
    ItemName.TORQUOISE_LASER: [],
    ItemName.GREEN_LASER: [],
    ItemName.MAGENTA_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.TORQUOISE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.RED_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.CRYSTAL_BOMB: [ItemName.THEO_CRYSTAL],
    ItemName.BOWL_PUFFER: [ItemName.PUFFER_FISH],
    ItemName.PURPLE_DASHLESS_BUBBLE: [ItemName.GENERIC_LONG_BUBBLES],
    ItemName.PULL_STATION_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.DASH_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.TRACK_SWITCH_BOX: [],
    ItemName.PURPLE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.GRAY_TIME_CRYSTAL: [ItemName.DASH_CRYSTALS],
    ItemName.PURPLE_JELLYFISH: [ItemName.JELLYFISH],
    ItemName.DASH_REFILL_WALL: [ItemName.DASH_CRYSTALS],
    ItemName.DOUBLE_DASH_REFILL_WALL: [ItemName.DOUBLE_DASH_CRYSTALS],
    ItemName.GRAY_BUBBLES: [ItemName.GENERIC_SHORT_BUBBLES],
    ItemName.SWITCH_CRATE: [ItemName.THEO_CRYSTAL],
    ItemName.GREEN_PORTAL: [],
    ItemName.MOVING_TOUCH_SWITCH: [ItemName.GENERIC_TOUCH_SWITCH],
    ItemName.DREAM_TRAFFIC_BLOCK: [ItemName.GENERIC_DREAM_BLOCK, ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.BOUNCY_SPIKES: [],
    ItemName.MOMENTUM_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.PURPLE_CASSETTE_BLOCK: [ItemName.PINK_CASSETTE],
    ItemName.ORANGE_CASSETTE_BLOCK: [ItemName.YELLOW_CASSETTE],
    ItemName.RED_CASSETTE_BLOCK: [ItemName.PINK_CASSETTE],
    ItemName.GREEN_CASSETTE_TRAFFIC_BLOCK: [ItemName.GREEN_CASSETTE, ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.PURPLE_MOVING_CASSETTE_BLOCK: [ItemName.PINK_CASSETTE, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.BLUE_MOVING_CASSETTE_BLOCK: [ItemName.BLUE_CASSETTE, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.PURPLE_CASSETTE_SWAP_BLOCK: [ItemName.PINK_CASSETTE, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.PINK_CASSETTE_SWAP_BLOCK: [ItemName.PINK_CASSETTE, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.RED_CASSETTE_SWAP_BLOCK: [ItemName.PINK_CASSETTE, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.ORANGE_MOVING_CASSETTE_BLOCK: [ItemName.YELLOW_CASSETTE, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.ORANGE_CASSETTE_TRAFFIC_BLOCK: [ItemName.YELLOW_CASSETTE, ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.GREEN_CASSETTE_SWAP_BLOCK: [ItemName.GREEN_CASSETTE, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.RED_CASSETTE_TRAFFIC_BLOCK: [ItemName.PINK_CASSETTE, ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.YELLOW_CASSETTE_SWAP_BLOCK: [ItemName.YELLOW_CASSETTE, ItemName.GENERIC_SWAP_BLOCK],
    ItemName.PINK_MOVING_CASSETTE_BLOCK: [ItemName.PINK_CASSETTE, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.GREEN_MOVING_CASSETTE_BLOCK: [ItemName.GREEN_CASSETTE, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.WORMHOLE_BUBBLE: [ItemName.GENERIC_SHORT_BUBBLES],
    ItemName.FAKE_CRYSTAL_HEART: [],
    ItemName.MINI_FAKE_CRYSTAL_HEART: [],
    ItemName.THROW_BOX: [ItemName.THEO_CRYSTAL],
    ItemName.PURPLE_REBOUND_BUBBLE: [ItemName.GENERIC_SHORT_BUBBLES],
    ItemName.GROWTH_POTION: [ItemName.GENERIC_DASH_SWITCH],
    ItemName.BLUE_GRAVITY_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.RED_GRAVITY_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.PURPLE_GRAVITY_SPRING: [ItemName.GENERIC_SPRINGS],
    ItemName.YELLOW_MOVING_CASSETTE_BLOCK: [ItemName.YELLOW_CASSETTE, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.MOVE_BLOCK_ACCELERATOR_FIELD: [],
    ItemName.MOVE_BLOCK_DELETE_FIELD: [],
    ItemName.MOVE_BLOCK_DECELERATOR_FIELD: [],
    ItemName.MOVE_BLOCK_REDIRECT_FIELD: [],
    ItemName.DREAM_MOVE_BLOCK: [ItemName.GENERIC_DREAM_BLOCK, ItemName.GENERIC_MOVE_BLOCK],
    ItemName.BATTERY: [ItemName.THEO_CRYSTAL],
    ItemName.RED_PROPELLER_BLOCK: [ItemName.THEO_CRYSTAL, ItemName.JELLYFISH],
    ItemName.YELLOW_PROPELLER_BLOCK: [ItemName.THEO_CRYSTAL, ItemName.JELLYFISH],
    ItemName.DASH_BOOST_FIELD: [],
    ItemName.FORCE_JUMP_CRYSTAL: [ItemName.DASH_CRYSTALS],
    ItemName.NO_STAMINA_DASH_CRYSTAL: [ItemName.DASH_CRYSTALS],
    ItemName.SPEED_MUSHROOMS: [ItemName.DASH_CRYSTALS],
    ItemName.SPEED_MUSHROOM_WALL: [ItemName.DASH_CRYSTALS],
    ItemName.WHITE_DREAM_BLOCK: [ItemName.GENERIC_DREAM_BLOCK],
    ItemName.RED_SPEED_MOSS: [],
    ItemName.BLUE_BOUNCE_MOSS: [],
    ItemName.WHITE_LINKED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.SQUARE_BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.BLUE_FLOATING_FIELDS: [],
    ItemName.RED_FLOATING_FIELDS: [],
    ItemName.PURPLE_FLOATING_FIELDS: [],
    ItemName.BLUE_FLIP_SWITCH: [ItemName.CORE_SWITCH],
    ItemName.GREEN_FLIP_SWITCH: [ItemName.CORE_SWITCH],
    ItemName.PURPLE_FLIP_SWITCH: [ItemName.CORE_SWITCH],
    ItemName.PINK_FLIP_SWITCH: [ItemName.CORE_SWITCH],
    ItemName.RED_FLIP_SWITCH: [ItemName.CORE_SWITCH],
    ItemName.PINK_SWITCH_BLOCK: [ItemName.PINK_CASSETTE],
    ItemName.PURPLE_SWITCH_BLOCK: [ItemName.PINK_CASSETTE],
    ItemName.RED_SWITCH_BLOCK: [ItemName.PINK_CASSETTE],
    ItemName.CLOUD_CRYSTAL: [ItemName.DASH_CRYSTALS, ItemName.CLOUDS],
    ItemName.JELLY_CRYSTAL: [ItemName.DASH_CRYSTALS, ItemName.JELLYFISH],
    ItemName.STOPWATCH_CRYSTAL: [ItemName.DASH_CRYSTALS],
    ItemName.CURVED_TRAFFIC_BLOCK: [ItemName.GENERIC_TRAFFIC_BLOCK],
    ItemName.SKY_LANTERN: [ItemName.JELLYFISH],
    ItemName.INFINITE_DASH_MOSAIC_CRYSTAL: [ItemName.DASH_CRYSTALS],
    ItemName.BLUE_STOPWATCH: [ItemName.DASH_CRYSTALS],
    ItemName.GREEN_STOPWATCH: [ItemName.DASH_CRYSTALS],
    ItemName.GRAY_STOPWATCH: [ItemName.DASH_CRYSTALS],
    ItemName.BUBBLE_EMITTER: [],
    ItemName.CANNON_BALL: [ItemName.THEO_CRYSTAL],
    ItemName.INFINITE_DASH_FIELD: [],
    ItemName.JUMP_REFILL_WALL: [ItemName.DASH_CRYSTALS],
    ItemName.ONE_USE_BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.DOUBLE_DASH_BUMPER: [ItemName.GENERIC_BUMPER, ItemName.DOUBLE_DASH_CRYSTALS],
    ItemName.MOVING_BUMPER: [ItemName.GENERIC_BUMPER],
    ItemName.YELLOW_ROCK: [ItemName.THEO_CRYSTAL],
    ItemName.BACKGROUND_SWITCH: [ItemName.CORE_SWITCH],
    ItemName.RED_DRUM: [ItemName.GENERIC_SWAP_BLOCK],
    ItemName.TOGGLE_DRUM: [ItemName.GENERIC_SWAP_BLOCK],
    ItemName.BLUE_FLYING_LANTERN: [ItemName.JELLYFISH],
    ItemName.RED_FLYING_LANTERN: [ItemName.JELLYFISH],
    ItemName.SILVER_PORTAL: [],
    ItemName.NAVY_PORTAL: []
}