from enum import StrEnum

from worlds.celeste_modded.constants.LevelNames import LevelCategory

# up_dash = "Up Dash"
# right_dash = "Right Dash"
# down_dash = "Down Dash"
# left_dash = "Left Dash"
# up_right_dash = "Up-Right Dash"
# up_left_dash = "Up-Left Dash"
# down_right_dash = "Down-Right Dash"
# down_left_dash = "Down-Left Dash"

class ItemName(StrEnum):
    
    DASH_CRYSTALS = "Single Dash Crystals"
    TRAFFIC_BLOCKS = "Normal Traffic Blocks"
    SPRINGS = "Normal Springs"
    BLUE_CASSETTE = "Plain Blue Cassette Blocks"
    PINK_CASSETTE = "Plain Pink Cassette Blocks"
    CRUMBLING_PLATFORM = "Crumbling Platforms",
    TOUCH_SWITCH = "Regular Touch Switches",
    DREAM_BLOCK = "Normal Dream Blocks",
    BADELINE_ORB = "Badeline Orbs",
    SINKING_PLATFORM = "Sinking Platforms",
    GREEN_BUBBLES = "Vanilla Blue Bubbles",
    CLOUDS = "Clouds",
    PINK_CLOUDS = "Pink Clouds",
    MOVING_BLOCK = "Vanilla Move Blocks",
    RED_BUBBLES = "Red Bubbles",
    SWAP_BLOCK = "Regular Swap Blocks",
    DASH_SWITCH = "Vanilla Dash Switches",
    FEATHER = "Feathers",
    MOVING_PLATFORM = "Moving Platforms",
    WHITE_BLOCK = "White Block",
    SEEKERS = "Seekers",
    THEO_CRYSTAL = "Theo Crystal",
    KEVIN = "Normal Kevins",
    BUMPER = "Normal Bumpers",
    CORE_BLOCK = "Core Blocks",
    CORE_SWITCH = "Core Switches",
    LAVA_ICE_BALLS = "Fire/Ice Balls",
    BREAKER_BOX = "Breaker Boxes",
    BIRD = "Bird",
    JELLYFISH = "Jellyfish",
    PUFFER_FISH = "Puffer fish",
    DOUBLE_DASH_CRYSTALS = "Double Dash Crystals",
    YELLOW_CASSETTE = "Plain Yellow Cassette Blocks",
    GREEN_CASSETTE = "Plain Green Cassette Blocks",
    LOOP_BLOCK = "Loopy Blocks (Loopy Lagoon)"
    DREAM_DASH_CRYSTAL = "Dream Dash Crystals",
    INTRO_CRUSHER = "Falling/Moving Ice Blocks",
    DASH_TRAFFIC_BLOCK = "Dash-Activated Zippers",
    BLUE_TRAFFIC_CASSETTE = "Blue Cassette Traffic Blocks",
    PINK_TRAFFIC_CASSETTE = "Pink Cassette Traffic Blocks",
    YELLOW_TRAFFIC_CASSETTE = "Yellow Cassette Traffic Blocks",
    SOAP_BUBBLE = "Blue Dashless Bubbles",
    DASHLESS_SPRING = "Dashless Blue Springs",
    SINGLE_JUMP_REFILL = "Single Jump Refills",
    TRIPLE_JUMP_REFILL = "Triple Jump Refills",
    DOUBLE_DASH_DREAM_BLOCK = "Double Dash Dream Blocks"
    GREEN_SWITCH_BLOCK = "Green Switch Blocks",
    ORANGE_SWITCH_BLOCK = "Orange Switch Blocks",
    SWITCH_BLOCK_SWITCH = "Switch Block Switch (Switchtube Vista)",
    GRAVITY_FIELD = "Gravity Fields",
    BLUE_TIME_CRYSTAL = "Blue Time Crystals",
    DASH_CRYSTAL_SHARDS = "Dash Crystal Shards",
    PIPES = "Pipes",
    BIG_YELLOW_BUTTON = "Big Yellow Buttons",
    PUZZLE_KEVIN = "Dropzle Kevins",
    TRIPLE_BOOST_FLOWER = "Triple-Boost Rose",
    BOUNCE_DREAM_BLOCK = "Treehive Dream Blocks",
    ORANGE_LINKED_TRAFFIC_BLOCK = "Orange Linked Zippers",
    BLUE_LINKED_TRAFFIC_BLOCK = "Blue Linked Zippers",
    TOGGLE_SWAP_BLOCK = "Toggle Swap Blocks",
    GREEN_LINKED_TRAFFIC_BLOCK = "Green Linked Zippers",
    STRAWBERRY_JAM = "Strawberry Jam Jar",
    NEON_BLUE_KEVIN = "Neon Blue Kevins",
    NEON_PURPLE_KEVIN = "Neon Purple Kevins",
    PUSH_BLOCK = "Push Blocks",
    VERTIGO_LINKED_TELEPORT = "Vertigo Linked Teleports",
    YELLOW_PORTAL = "Yellow Portals",
    PURPLE_PORTAL = "Purple Portals",
    PUSH_STATION_BLOCK = "Push Station Blocks",
    BLUE_PORTAL = "Blue Portals",
    RED_PORTAL = "Red Portals",
    TIMED_TOUCH_SWITCH = "Timed Touch Switches"
    HONEY_BUBBLES = "Honey Bubbles",
    ZIPLINE = "Ziplines",
    YELLOW_LINKED_TRAFFIC_BLOCK = "Yellow Linked Zippers",
    YELLOW_LASER = "Yellow Activation Lasers",
    TORQUOISE_LASER = "Torquoise Activation Lasers",
    GREEN_LASER = "Green Activation Lasers",
    MAGENTA_LINKED_TRAFFIC_BLOCK = "Magenta Linked Zippers",
    TORQUOISE_LINKED_TRAFFIC_BLOCK = "Torquoise Linked Zippers",
    RED_LINKED_TRAFFIC_BLOCK = "Red Linked Zippers",
    CRYSTAL_BOMB = "Crystal Bombs",
    BOWL_PUFFER = "Pufferfish in a Bowl",
    PURPLE_DASHLESS_BUBBLE = "Purple Dashless Bubbles",
    PULL_STATION_BLOCK = "Pull Station Blocks",
    DASH_SPRING = "Dash Springs",
    TRACK_SWITCH_BOX = "Track Switch Box",
    PURPLE_LINKED_TRAFFIC_BLOCK = "Purple Linked Zippers",
    GRAY_TIME_CRYSTAL = "Gray Time Crystals",
    PURPLE_JELLYFISH = "Purple Jellyfish",
    DASH_REFILL_WALL = "Dash Refill Walls",
    DOUBLE_DASH_REFILL_WALL = "Double Dash Refill Walls",
    GRAY_BUBBLES = "Gray Bubbles",
    SWITCH_CRATE = "Switch Crates",
    GREEN_PORTAL = "Green Portals",
    MOVING_TOUCH_SWITCH = "Moving Touch Switches",
    DREAM_TRAFFIC_BLOCK = "Dream Zippers",
    BOUNCY_SPIKES = "Bouncy Spikes",
    MOMENTUM_SPRING = "Momentum Springs",
    PURPLE_CASSETTE_BLOCK = "Purple Cassette Blocks",
    ORANGE_CASSETTE_BLOCK = "Orange Cassette Blocks",
    RED_CASSETTE_BLOCK = "Red Cassette Blocks",
    GREEN_CASSETTE_TRAFFIC_BLOCK = "Green Cassette Zippers",
    PURPLE_MOVING_CASSETTE_BLOCK = "Purple Moving Cassette blocks",
    BLUE_MOVING_CASSETTE_BLOCK = "Blue Moving Cassette Blocks",
    PURPLE_CASSETTE_SWAP_BLOCK = "Purple Moving Cassette Blocks",
    PINK_CASSETTE_SWAP_BLOCK = "Pink Cassette Swap Blocks",
    RED_CASSETTE_SWAP_BLOCK = "Red Cassette Swap Blocks",
    ORANGE_MOVING_CASSETTE_BLOCK = "Orange Moving Cassette Blocks",
    ORANGE_CASSETTE_TRAFFIC_BLOCK = "Orange Cassette Zippers",
    GREEN_CASSETTE_SWAP_BLOCK = "Green Cassette Swap Blocks",
    RED_CASSETTE_TRAFFIC_BLOCK = "Red Cassette Zippers",
    YELLOW_CASSETTE_SWAP_BLOCK = "Yellow Cassette Swap Blocks",
    PINK_MOVING_CASSETTE_BLOCK = "Pink Moving Cassette Blocks",
    GREEN_MOVING_CASSETTE_BLOCK = "Green Moving Cassette Blocks",
    WORMHOLE_BUBBLE = "Wormhole Bubbles",
    FAKE_CRYSTAL_HEART = "Fake Crystal Hearts",
    MINI_FAKE_CRYSTAL_HEART = "Mini Fake Crystal Hearts",
    THROW_BOX = "Throw Boxes",
    PURPLE_REBOUND_BUBBLE = "Purple Rebound Bubbles",
    GROWTH_POTION = "Growth Potion",
    BLUE_GRAVITY_SPRING = "Blue Gravity Springs",
    RED_GRAVITY_SPRING = "Red Gravity Springs",
    PURPLE_GRAVITY_SPRING = "Purple Gravity Springs",
    YELLOW_MOVING_CASSETTE_BLOCK = "Yellow Moving Cassette Blocks",
    MOVE_BLOCK_ACCELERATOR_FIELD = "Move Block Green Acceleration Fields",
    MOVE_BLOCK_DELETE_FIELD = "Move Block Red Deletion Fields",
    MOVE_BLOCK_DECELERATOR_FIELD = "Move Block Blue Deceleration Fields",
    MOVE_BLOCK_REDIRECT_FIELD = "Move Block Yellow Redirection Fields",
    DREAM_MOVE_BLOCK = "Moving Dream Blocks",
    BATTERY = "Batteries",
    RED_PROPELLER_BLOCK = "Red Propeller Blocks",
    YELLOW_PROPELLER_BLOCK = "Yellow Propeller Blocks",
    DASH_BOOST_FIELD = "Dash Boost Fields",
    FORCE_JUMP_CRYSTAL = "Force Jump Crystals",
    NO_STAMINA_DASH_CRYSTAL = "No-Stamina Dash Crystals",
    SPEED_MUSHROOMS = "Speed Mushrooms",
    SPEED_MUSHROOM_WALL = "Speed Mushroom Refill Walls",
    WHITE_DREAM_BLOCK = "White Dream Blocks",
    RED_SPEED_MOSS = "Red Speed Moss",
    BLUE_BOUNCE_MOSS = "Blue Bounce Moss",
    WHITE_LINKED_TRAFFIC_BLOCK = "White Linked Traffic Blocks",
    SQUARE_BUMPER = "Square Bumpers",
    BLUE_FLOATING_FIELDS = "Blue Float Fields",
    RED_FLOATING_FIELDS = "Red Float Fields",
    PURPLE_FLOATING_FIELDS = "Purple Float Fields",
    BLUE_FLIP_SWITCH = "Blue Toggle Switches",
    GREEN_FLIP_SWITCH = "Green Toggle Switches",
    PURPLE_FLIP_SWITCH = "Purple Toggle Switches",
    PINK_FLIP_SWITCH = "Pink Toggle Switches",
    RED_FLIP_SWITCH = "Red Toggle Switches",
    PINK_SWITCH_BLOCK = "Pink Switch Blocks",
    PURPLE_SWITCH_BLOCK = "Purple Switch Blocks",
    RED_SWITCH_BLOCK = "Red Switch Blocks",
    CLOUD_CRYSTAL = "Cloud Crystals",
    JELLY_CRYSTAL = "Jellyfish Crystals",
    STOPWATCH_CRYSTAL = "Stopwatch Crystals",
    CURVED_TRAFFIC_BLOCK = "Curved Traffic Blocks",
    SKY_LANTERN = "Sky Lantern",
    INFINITE_DASH_MOSAIC_CRYSTAL = "Infinite Dash Mosaic Crystals",
    BLUE_STOPWATCH = "Blue Stopwatches",
    GREEN_STOPWATCH = "Green Stopwatches",
    GRAY_STOPWATCH = "Gray Stopwatches",
    BUBBLE_EMITTER = "Bubble Emitters",
    CANNON_BALL = "Cannon Ball",
    INFINITE_DASH_FIELD = "Infinite Dash Fields",
    JUMP_REFILL_WALL = "Jump Refill Walls",
    ONE_USE_BUMPER = "Single Use Bumpers",
    DOUBLE_DASH_BUMPER = "Double Dash Bumpers",
    MOVING_BUMPER = "Moving Bumpers",
    YELLOW_ROCK = "Yellow Rock",
    BACKGROUND_SWITCH = "Background Toggle Switch",
    RED_DRUM = "Red Drums",
    TOGGLE_DRUM = "Toggle Drums",
    BLUE_FLYING_LANTERN = "Blue Flying Lanterns",
    RED_FLYING_LANTERN = "Red Flying Lanterns",
    SILVER_PORTAL = "Silver Portals",
    NAVY_PORTAL = "Navy Portals"
            
    STRAWBERRY = "Strawberry"
    
    MOON_BERRY = "Moon Berry"
        
    LEVEL_VICTORY = "Win Condition Level Victory"
    
    RASPBERRY = "Raspberry"
    BLUEBERRY = "Blueberry"
    BLACKBERRY = "Blackberry"
    CRANBERRY = "Cranberry"
    ELDERBERRY = "Elderberry"
    HUCKLEBERRY = "Huckleberry"


filler = {
    ItemName.RASPBERRY: 0, ItemName.BLUEBERRY: 1, ItemName.BLACKBERRY: 2, ItemName.CRANBERRY: 3, ItemName.ELDERBERRY: 4, ItemName.HUCKLEBERRY: 5
}

strawberry = {ItemName.STRAWBERRY: 0}

moon_berry = {ItemName.MOON_BERRY: 0}

level_victory = {ItemName.LEVEL_VICTORY: 0}

mechanic = {
    ItemName.DASH_CRYSTALS: 0,
    ItemName.TRAFFIC_BLOCKS: 1,
    ItemName.SPRINGS: 2,
    ItemName.BLUE_CASSETTE: 3,
    ItemName.PINK_CASSETTE: 4,
    ItemName.CRUMBLING_PLATFORM: 5,
    ItemName.TOUCH_SWITCH: 6,
    ItemName.DREAM_BLOCK: 7,
    ItemName.BADELINE_ORB: 8,
    ItemName.SINKING_PLATFORM: 9,
    ItemName.GREEN_BUBBLES: 10,
    ItemName.CLOUDS: 11,
    ItemName.PINK_CLOUDS: 12,
    ItemName.MOVING_BLOCK: 13,
    ItemName.RED_BUBBLES: 14,
    ItemName.SWAP_BLOCK: 15,
    ItemName.DASH_SWITCH: 16,
    ItemName.FEATHER: 17,
    ItemName.MOVING_PLATFORM: 18,
    ItemName.WHITE_BLOCK: 19,
    ItemName.SEEKERS: 20,
    ItemName.THEO_CRYSTAL: 21,
    ItemName.KEVIN: 22,
    ItemName.BUMPER: 23,
    ItemName.CORE_BLOCK: 24,
    ItemName.CORE_SWITCH: 25,
    ItemName.LAVA_ICE_BALLS: 26,
    ItemName.BREAKER_BOX: 27,
    ItemName.BIRD: 28,
    ItemName.JELLYFISH: 29,
    ItemName.PUFFER_FISH: 30,
    ItemName.DOUBLE_DASH_CRYSTALS: 31,
    ItemName.YELLOW_CASSETTE: 32,
    ItemName.GREEN_CASSETTE: 33,
    ItemName.LOOP_BLOCK: 34,
    ItemName.DREAM_DASH_CRYSTAL: 35,
    ItemName.INTRO_CRUSHER: 36,
    ItemName.DASH_TRAFFIC_BLOCK: 37,
    ItemName.BLUE_TRAFFIC_CASSETTE: 38,
    ItemName.PINK_TRAFFIC_CASSETTE: 39,
    ItemName.YELLOW_TRAFFIC_CASSETTE: 40,
    ItemName.SOAP_BUBBLE: 41,
    ItemName.DASHLESS_SPRING: 42,
    ItemName.SINGLE_JUMP_REFILL: 43,
    ItemName.TRIPLE_JUMP_REFILL: 44,
    ItemName.DOUBLE_DASH_DREAM_BLOCK: 45,
    ItemName.GREEN_SWITCH_BLOCK: 46,
    ItemName.ORANGE_SWITCH_BLOCK: 47,
    ItemName.SWITCH_BLOCK_SWITCH: 48,
    ItemName.GRAVITY_FIELD: 49,
    ItemName.BLUE_TIME_CRYSTAL: 50,
    ItemName.DASH_CRYSTAL_SHARDS: 51,
    ItemName.PIPES: 52,
    ItemName.BIG_YELLOW_BUTTON: 53,
    ItemName.PUZZLE_KEVIN: 54,
    ItemName.TRIPLE_BOOST_FLOWER: 55,
    ItemName.BOUNCE_DREAM_BLOCK: 56,
    ItemName.ORANGE_LINKED_TRAFFIC_BLOCK: 57,
    ItemName.BLUE_LINKED_TRAFFIC_BLOCK: 58,
    ItemName.TOGGLE_SWAP_BLOCK: 59,
    ItemName.GREEN_LINKED_TRAFFIC_BLOCK: 60,
    ItemName.STRAWBERRY_JAM: 61,
    ItemName.NEON_BLUE_KEVIN: 62,
    ItemName.NEON_PURPLE_KEVIN: 63,
    ItemName.PUSH_BLOCK: 64,
    ItemName.VERTIGO_LINKED_TELEPORT: 65,
    ItemName.YELLOW_PORTAL: 66,
    ItemName.PURPLE_PORTAL: 67,
    ItemName.PUSH_STATION_BLOCK: 68,
    ItemName.BLUE_PORTAL: 69,
    ItemName.RED_PORTAL: 70,
    ItemName.TIMED_TOUCH_SWITCH: 71,
    ItemName.HONEY_BUBBLES: 72,
    ItemName.ZIPLINE: 73,
    ItemName.YELLOW_LINKED_TRAFFIC_BLOCK: 74,
    ItemName.YELLOW_LASER: 75,
    ItemName.TORQUOISE_LASER: 76,
    ItemName.GREEN_LASER: 77,
    ItemName.MAGENTA_LINKED_TRAFFIC_BLOCK: 78,
    ItemName.TORQUOISE_LINKED_TRAFFIC_BLOCK: 79,
    ItemName.RED_LINKED_TRAFFIC_BLOCK: 80,
    ItemName.CRYSTAL_BOMB: 81,
    ItemName.BOWL_PUFFER: 82,
    ItemName.PURPLE_DASHLESS_BUBBLE: 83,
    ItemName.PULL_STATION_BLOCK: 84,
    ItemName.DASH_SPRING: 85,
    ItemName.TRACK_SWITCH_BOX: 86,
    ItemName.PURPLE_LINKED_TRAFFIC_BLOCK: 87,
    ItemName.GRAY_TIME_CRYSTAL: 88,
    ItemName.PURPLE_JELLYFISH: 89,
    ItemName.DASH_REFILL_WALL: 90,
    ItemName.DOUBLE_DASH_REFILL_WALL: 91,
    ItemName.GRAY_BUBBLES: 92,
    ItemName.SWITCH_CRATE: 93,
    ItemName.GREEN_PORTAL: 94,
    ItemName.MOVING_TOUCH_SWITCH: 95,
    ItemName.DREAM_TRAFFIC_BLOCK: 96,
    ItemName.BOUNCY_SPIKES: 97,
    ItemName.MOMENTUM_SPRING: 98,
    ItemName.PURPLE_CASSETTE_BLOCK: 99,
    ItemName.ORANGE_CASSETTE_BLOCK: 100,
    ItemName.RED_CASSETTE_BLOCK: 101,
    ItemName.GREEN_CASSETTE_TRAFFIC_BLOCK: 102,
    ItemName.PURPLE_MOVING_CASSETTE_BLOCK: 103,
    ItemName.BLUE_MOVING_CASSETTE_BLOCK: 104,
    ItemName.PURPLE_CASSETTE_SWAP_BLOCK: 105,
    ItemName.PINK_CASSETTE_SWAP_BLOCK: 106,
    ItemName.RED_CASSETTE_SWAP_BLOCK: 107,
    ItemName.ORANGE_MOVING_CASSETTE_BLOCK: 108,
    ItemName.ORANGE_CASSETTE_TRAFFIC_BLOCK: 109,
    ItemName.GREEN_CASSETTE_SWAP_BLOCK: 110,
    ItemName.RED_CASSETTE_TRAFFIC_BLOCK: 111,
    ItemName.YELLOW_CASSETTE_SWAP_BLOCK: 112,
    ItemName.PINK_MOVING_CASSETTE_BLOCK: 113,
    ItemName.GREEN_MOVING_CASSETTE_BLOCK: 114,
    ItemName.WORMHOLE_BUBBLE: 115,
    ItemName.FAKE_CRYSTAL_HEART: 116,
    ItemName.MINI_FAKE_CRYSTAL_HEART: 117,
    ItemName.THROW_BOX: 118,
    ItemName.PURPLE_REBOUND_BUBBLE: 119,
    ItemName.GROWTH_POTION: 120,
    ItemName.BLUE_GRAVITY_SPRING: 121,
    ItemName.RED_GRAVITY_SPRING: 122,
    ItemName.PURPLE_GRAVITY_SPRING: 123,
    ItemName.YELLOW_MOVING_CASSETTE_BLOCK: 124,
    ItemName.MOVE_BLOCK_ACCELERATOR_FIELD: 125,
    ItemName.MOVE_BLOCK_DELETE_FIELD: 126,
    ItemName.MOVE_BLOCK_DECELERATOR_FIELD: 127,
    ItemName.MOVE_BLOCK_REDIRECT_FIELD: 128,
    ItemName.DREAM_MOVE_BLOCK: 129,
    ItemName.BATTERY: 130,
    ItemName.RED_PROPELLER_BLOCK: 131,
    ItemName.YELLOW_PROPELLER_BLOCK: 132,
    ItemName.DASH_BOOST_FIELD: 133,
    ItemName.FORCE_JUMP_CRYSTAL: 134,
    ItemName.NO_STAMINA_DASH_CRYSTAL: 135,
    ItemName.SPEED_MUSHROOMS: 136,
    ItemName.SPEED_MUSHROOM_WALL: 137,
    ItemName.WHITE_DREAM_BLOCK: 138,
    ItemName.RED_SPEED_MOSS: 139,
    ItemName.BLUE_BOUNCE_MOSS: 140,
    ItemName.WHITE_LINKED_TRAFFIC_BLOCK: 141,
    ItemName.SQUARE_BUMPER: 142,
    ItemName.BLUE_FLOATING_FIELDS: 143,
    ItemName.RED_FLOATING_FIELDS: 144,
    ItemName.PURPLE_FLOATING_FIELDS: 145,
    ItemName.BLUE_FLIP_SWITCH: 146,
    ItemName.GREEN_FLIP_SWITCH: 147,
    ItemName.PURPLE_FLIP_SWITCH: 148,
    ItemName.PINK_FLIP_SWITCH: 149,
    ItemName.RED_FLIP_SWITCH: 150,
    ItemName.PINK_SWITCH_BLOCK: 151,
    ItemName.PURPLE_SWITCH_BLOCK: 152,
    ItemName.RED_SWITCH_BLOCK: 153,
    ItemName.CLOUD_CRYSTAL: 154,
    ItemName.JELLY_CRYSTAL: 155,
    ItemName.STOPWATCH_CRYSTAL: 156,
    ItemName.CURVED_TRAFFIC_BLOCK: 157,
    ItemName.SKY_LANTERN: 158,
    ItemName.INFINITE_DASH_MOSAIC_CRYSTAL: 159,
    ItemName.BLUE_STOPWATCH: 160,
    ItemName.GREEN_STOPWATCH: 161,
    ItemName.GRAY_STOPWATCH: 162,
    ItemName.BUBBLE_EMITTER: 163,
    ItemName.CANNON_BALL: 164,
    ItemName.INFINITE_DASH_FIELD: 165,
    ItemName.JUMP_REFILL_WALL: 166,
    ItemName.ONE_USE_BUMPER: 167,
    ItemName.DOUBLE_DASH_BUMPER: 168,
    ItemName.MOVING_BUMPER: 169,
    ItemName.YELLOW_ROCK: 170,
    ItemName.BACKGROUND_SWITCH: 171,
    ItemName.RED_DRUM: 172,
    ItemName.TOGGLE_DRUM: 173,
    ItemName.BLUE_FLYING_LANTERN: 174,
    ItemName.RED_FLYING_LANTERN: 175,
    ItemName.SILVER_PORTAL: 176,
    ItemName.NAVY_PORTAL: 177
}