from enum import StrEnum

class LevelName(StrEnum):
    PROLOGUE = "Prologue"
    FORSAKEN_CITY_A = "Forsaken City A-Side"
    FORSAKEN_CITY_B = "Forsaken City A-Side"
    FORSAKEN_CITY_C = "Forsaken City A-Side"
    OLD_SITE_A = "Old Site A-Side"
    OLD_SITE_B = "Old Site B-Side"
    OLD_SITE_C = "Old Site C-Side"
    CELESTIAL_RESORT_A = "Celestial Resort A-Side"
    CELESTIAL_RESORT_B = "Celestial Resort B-Side"
    CELESTIAL_RESORT_C = "Celestial Resort C-Side"
    GOLDEN_RIDGE_A = "Golden Ridge A-Side"
    GOLDEN_RIDGE_B = "Golden Ridge B-Side"
    GOLDEN_RIDGE_C = "Golden Ridge C-Side"
    MIRROR_TEMPLE_A = "Mirror Temple A-Side"
    MIRROR_TEMPLE_B = "Mirror Temple B-Side"
    MIRROR_TEMPLE_C = "Mirror Temple C-Side"
    REFLECTION_A = "Reflection A-Side"
    REFLECTION_B = "Reflection B-Side"
    REFLECTION_C = "Reflection C-Side"
    SUMMIT_A = "Summit A-Side"
    SUMMIT_B = "Summit B-Side"
    SUMMIT_C = "Summit C-Side"
    EPILOGUE = "Epilogue"
    CORE_A = "Core A-Side"
    CORE_B = "Core B-Side"
    CORE_C = "Core C-Side"
    FAREWELL = "Farewell"
    
    BLUEBERRY_BAY = "Blueberry Bay"
    RASPBERRY_ROOTS = "Raspberry Roots"
    MANGO_MESA = "Mango Mesa"
    STARFRUIT_SUPERNOVA = "Starfruit Supernova"
    PASSIONFRUIT_PANTHEON = "Passionfruit Pantheon"
    
class LevelCategory(StrEnum):
    A_SIDE = "A-Side"
    B_SIDE = "B-Side"
    C_SIDE = "C-Side"
    FAREWELL = "Farewell"
    BEGINNER = "SJ Beginner"
    INTERMEDIATE = "SJ Intermediate"
    ADVANCED = "SJ Advanced"
    EXPERT = "SJ Expert"
    GRANDMASTER = "SJ Grandmaster"
    CRACKED_GRANDMASTER = "SJ Cracked GM"
    BEGINNER_HEARTSIDE = "Beginner Heartside"
    INTERMEDIATE_HEARTSIDE = "Intermediate Heartside"
    ADVANCED_HEARTSIDE = "Advanced Heartside"
    EXPERT_HEARTSIDE = "Expert Heartside"
    GRANDMASTER_HEARTSIDE = "Grandmaster Heartside"