from ..Naming import getKeyDoorName, getLocationName
from ..constants.ItemNames import ItemName
from ..constants.LevelNames import LevelCategory, LevelName
from .LogicalObjects import Level, Room, Transition, Location, CHearts
from ..constants.LocationTypes import LocationType

farewell_final_room_reqs = [[ItemName.PUFFER_FISH, ItemName.JELLYFISH, ItemName.BADELINE_ORB, ItemName.BIRD, ItemName.SPRINGS, ItemName.DASH_CRYSTALS, ItemName.DOUBLE_DASH_CRYSTALS, ItemName.TOUCH_SWITCH, ItemName.FEATHER, ItemName.BREAKER_BOX]]

vanilla_post_game_levels : dict[LevelName, Level] = {
    LevelName.CORE_A:
    Level(
        {
            "00": Room(0, [Transition("01"), Transition("0x")], start_room=True),
            "0x": Room(1, [Transition("00")]),
            "01": Room(2, [Transition("02"), Transition("00")]),
            "02": Room(3, [Transition("a-00", [[CHearts(4)]]), Transition("01")]),
            "a-00": Room(4, [Transition("a-01", [[ItemName.DASH_CRYSTALS]])], [Location(LocationType.GOLDEN_BERRY, 19, [[ItemName.BUMPER, ItemName.FEATHER, ItemName.BLUE_CASSETTE, ItemName.PINK_CASSETTE, ItemName.TOUCH_SWITCH, ItemName.CORE_BLOCK, ItemName.CORE_SWITCH, ItemName.LAVA_ICE_BALLS, ItemName.DASH_CRYSTALS]])], checkpoint="Into the Core"),
            "a-01": Room(5, [Transition("a-02")]),
            "a-02": Room(6, [Transition("a-03", [[ItemName.CORE_BLOCK]])]),
            "a-03": Room(7, [Transition("b-00")]),
            "b-00": Room(8, [Transition("b-07b", [[ItemName.CORE_SWITCH, ItemName.TOUCH_SWITCH, ItemName.LAVA_ICE_BALLS]]), Transition("b-06"), Transition("b-01")]),
            "b-06": Room(9, [Transition("b-00")], [Location(LocationType.STRAWBERRY, 174, [[ItemName.CORE_SWITCH, ItemName.TOUCH_SWITCH, ItemName.LAVA_ICE_BALLS]])]),
            "b-07b": Room(10, [Transition("b-07")]),
            "b-07": Room(11, [Transition("c-00")]),
            "c-00": Room(12, [Transition("c-01", [[ItemName.CORE_BLOCK, ItemName.CORE_SWITCH]]), Transition("c-00b")], checkpoint="Hot and Cold"),
            "c-00b": Room(13, [Transition("c-00", [[ItemName.CORE_BLOCK, ItemName.CORE_SWITCH, ItemName.LAVA_ICE_BALLS, ItemName.DASH_CRYSTALS]])], [Location(LocationType.STRAWBERRY, 211, [[ItemName.BUMPER]])]),
            "c-01": Room(14, [Transition("c-02", [[ItemName.LAVA_ICE_BALLS, ItemName.DASH_CRYSTALS]]), Transition("c-00")]),
            "c-02": Room(15, [Transition("c-03")], [Location(LocationType.STRAWBERRY, 248, [[ItemName.BUMPER]])]),
            "c-03": Room(16, [Transition("c-04"), Transition("c-03b")]),
            "c-03b": Room(17, [Transition("c-03")], [Location(LocationType.STRAWBERRY, 276)]),
            "c-04": Room(18, [Transition("d-00")]),
            "d-00": Room(19, [Transition("d-01")], checkpoint="Heart of the Mountain"),
            "d-01": Room(20, [Transition("d-02")]),
            "d-02": Room(21, [Transition("d-03", [[ItemName.CORE_SWITCH]])]),
            "d-03": Room(22, [Transition("d-04")]),
            "d-04": Room(23, [Transition("d-05", [[ItemName.DASH_CRYSTALS]])]),
            "d-05": Room(24, [Transition("d-06", [[ItemName.LAVA_ICE_BALLS]])]),
            "d-06": Room(25, [Transition("d-07", [[ItemName.CORE_BLOCK]])], [Location(LocationType.STRAWBERRY, 130, [[ItemName.CORE_BLOCK]])]),
            "d-07": Room(26, [Transition("d-08")]),
            "d-08": Room(27, [Transition("d-09")]),
            "d-09": Room(28, [Transition("d-10")]),
            "d-10": Room(29, [Transition("d-10b")]),
            "d-10b": Room(30, [Transition("d-10c", [[ItemName.BUMPER]])]),
            "d-10c": Room(31, [Transition("d-11", [[ItemName.FEATHER]])]),
            "d-11": Room(32, [Transition("space", [[ItemName.BLUE_CASSETTE, ItemName.PINK_CASSETTE]])], [Location(LocationType.CASSETTE, access_rule=[[ItemName.BLUE_CASSETTE, ItemName.PINK_CASSETTE]])]),
            "space": Room(33, [], [Location(LocationType.CRYSTAL_HEART)]),
            "b-02": Room(35, [Transition("b-01"), Transition("b-03")]),
            "b-01": Room(36, [Transition("b-02"), Transition("b-00")]),
            "b-03": Room(37, [Transition("b-02"), Transition("b-04")]),
            "b-04": Room(38, [Transition("b-05", [[ItemName.CORE_SWITCH]]), Transition("b-03")]),
            "b-05": Room(39, [Transition("b-04")])
        }, LevelCategory.A_SIDE, 22
    ),
    LevelName.CORE_B:
    Level(
        {
            "00": Room(0, [Transition("01")], start_room=True),
            "01": Room(1, [Transition("a-00", [[CHearts(15)]])]),
            "a-00": Room(2, [Transition("a-01", [[ItemName.CRUMBLING_PLATFORM, ItemName.DASH_CRYSTALS]])], [Location(LocationType.GOLDEN_BERRY, 22, [[ItemName.BLUE_CASSETTE, ItemName.PINK_CASSETTE, ItemName.CRUMBLING_PLATFORM, ItemName.LAVA_ICE_BALLS, ItemName.BUMPER, ItemName.DASH_CRYSTALS, ItemName.CORE_BLOCK, ItemName.CORE_SWITCH, ItemName.SPRINGS, ItemName.TRAFFIC_BLOCKS, ItemName.DREAM_BLOCK, ItemName.MOVING_PLATFORM, ItemName.CLOUDS, ItemName.SWAP_BLOCK, ItemName.KEVIN, ItemName.BADELINE_ORB]])], checkpoint="Into the Core"),
            "a-01": Room(3, [Transition("a-02", [[ItemName.CORE_BLOCK]])]),
            "a-02": Room(4, [Transition("a-03", [[ItemName.CORE_SWITCH]])]),
            "a-03": Room(5, [Transition("a-04", [[ItemName.LAVA_ICE_BALLS]])]),
            "a-04": Room(6, [Transition("a-05")]),
            "a-05": Room(7, [Transition("b-00", [[ItemName.BUMPER]])]),
            "b-00": Room(8, [Transition("b-01")], checkpoint="Burning or Freezing"),
            "b-01": Room(9, [Transition("b-02", [[ItemName.CORE_BLOCK, ItemName.BUMPER, ItemName.CORE_SWITCH]])]),
            "b-02": Room(10, [Transition("b-03", [[ItemName.DASH_CRYSTALS, ItemName.LAVA_ICE_BALLS, ItemName.TOUCH_SWITCH]])]),
            "b-03": Room(11, [Transition("b-04")]),
            "b-04": Room(12, [Transition("b-05")]),
            "b-05": Room(13, [Transition("c-00")]),
            "c-00": Room(14, [Transition("c-01", [[ItemName.DASH_CRYSTALS, ItemName.CORE_BLOCK, ItemName.CORE_SWITCH, ItemName.SPRINGS]])], checkpoint="Heartbeat"),
            "c-01": Room(15, [Transition("c-02")]),
            "c-02": Room(16, [Transition("c-03")]),
            "c-03": Room(17, [Transition("c-04", [[ItemName.TRAFFIC_BLOCKS, ItemName.DREAM_BLOCK, ItemName.MOVING_PLATFORM, ItemName.CLOUDS, ItemName.SWAP_BLOCK, ItemName.KEVIN, ItemName.BADELINE_ORB]])]),
            "c-04": Room(18, [Transition("c-05", [[ItemName.BUMPER]])]),
            "c-05": Room(19, [Transition("c-06")]),
            "c-06": Room(20, [Transition("c-08")]),
            "c-08": Room(21, [Transition("c-07")]),
            "c-07": Room(22, [Transition("space")]),
            "space": Room(23, [], [Location(LocationType.CRYSTAL_HEART, access_rule=[[ItemName.BLUE_CASSETTE], [ItemName.PINK_CASSETTE]])])
        }, LevelCategory.B_SIDE, 23
    ),
    LevelName.CORE_C:
    Level(
        {
            "intro": Room(0, [Transition("00", [[CHearts(23)]])], start_room=True),
            "00": Room(1, [Transition("01", [[ItemName.CRUMBLING_PLATFORM, ItemName.DASH_CRYSTALS]])], [Location(LocationType.GOLDEN_BERRY, 93, [[ItemName.CRUMBLING_PLATFORM, ItemName.DASH_CRYSTALS, ItemName.CORE_BLOCK, ItemName.BUMPER, ItemName.CORE_SWITCH, ItemName.TRAFFIC_BLOCKS, ItemName.DREAM_BLOCK, ItemName.PINK_CLOUDS, ItemName.SWAP_BLOCK, ItemName.KEVIN, ItemName.SPRINGS]])]),
            "01": Room(2, [Transition("02", [[ItemName.CORE_BLOCK, ItemName.BUMPER, ItemName.CORE_SWITCH]])]),
            "02": Room(3, [], [Location(LocationType.CRYSTAL_HEART, access_rule=[[ItemName.TRAFFIC_BLOCKS, ItemName.DREAM_BLOCK, ItemName.PINK_CLOUDS, ItemName.SWAP_BLOCK, ItemName.KEVIN, ItemName.SPRINGS]])])
        }, LevelCategory.C_SIDE, 24
    ),
    LevelName.FAREWELL:
    Level(
        {
            "intro-01-future": Room(0, [Transition("intro-02-launch", [[ItemName.BADELINE_ORB]])], start_room=True),
            "intro-02-launch": Room(1, [Transition("intro-03-space", [[ItemName.CLOUDS]])]),
            "intro-03-space": Room(2, [Transition("a-00"), Transition("intro-02-launch")]),
            "a-00": Room(3, [Transition("a-01", [[ItemName.DOUBLE_DASH_CRYSTALS]])], [Location(LocationType.GOLDEN_BERRY, 449, [[ItemName.BLUE_CASSETTE, ItemName.PINK_CASSETTE, ItemName.YELLOW_CASSETTE, ItemName.GREEN_CASSETTE, ItemName.KEVIN, getKeyDoorName(LevelName.FAREWELL, "d-00", 471), getKeyDoorName(LevelName.FAREWELL, "d-00", 145), getKeyDoorName(LevelName.FAREWELL, "d-00", 144), getKeyDoorName(LevelName.FAREWELL, "d-00", 142), getKeyDoorName(LevelName.FAREWELL, "d-00", 197), ItemName.CLOUDS, ItemName.DASH_SWITCH, ItemName.MOVING_BLOCK, ItemName.CORE_BLOCK, ItemName.LAVA_ICE_BALLS, ItemName.RED_BUBBLES, ItemName.GREEN_BUBBLES, ItemName.SWAP_BLOCK, ItemName.DREAM_BLOCK, ItemName.CRUMBLING_PLATFORM, ItemName.PUFFER_FISH, ItemName.JELLYFISH, ItemName.BADELINE_ORB, ItemName.BIRD, ItemName.SPRINGS, ItemName.DASH_CRYSTALS, ItemName.DOUBLE_DASH_CRYSTALS, ItemName.TOUCH_SWITCH, ItemName.FEATHER, ItemName.BREAKER_BOX]])], checkpoint="Singular"),
            "a-01": Room(4, [Transition("a-02", [[ItemName.DASH_CRYSTALS]])]),
            "a-02": Room(5, [Transition("a-03")]),
            "a-03": Room(6, [Transition("a-04", [[ItemName.SWAP_BLOCK]])]),
            "a-04": Room(7, [Transition("a-05", [[ItemName.SPRINGS]])]),
            "a-05": Room(8, [Transition("b-00", [[ItemName.TOUCH_SWITCH]])]),
            "b-00": Room(9, [Transition("b-01", [[ItemName.PUFFER_FISH]])]),
            "b-01": Room(10, [Transition("b-02")]),
            "b-02": Room(11, [Transition("b-03")]),
            "b-03": Room(12, [Transition("b-04", [[ItemName.DREAM_BLOCK]])]),
            "b-04": Room(13, [Transition("b-05", [[ItemName.CRUMBLING_PLATFORM]])]),
            "b-05": Room(14, [Transition("b-06")]),
            "b-06": Room(15, [Transition("b-07")]),
            "b-07": Room(16, [Transition("c-00")]),
            "c-00": Room(17, [Transition("c-00b", [[ItemName.JELLYFISH]]), Transition("c-alt-00", [[ItemName.JELLYFISH, ItemName.DASH_CRYSTALS]])], checkpoint="Power Source"),
            "c-00b": Room(18, [Transition("c-01")]),
            "c-01": Room(19, [Transition("c-02")]),
            "c-02": Room(20, [Transition("c-03")]),
            "c-03": Room(21, [Transition("d-00", [[ItemName.SPRINGS]])]),
            "d-00": Room(22, [Transition("e-00y", [[ItemName.RED_BUBBLES, getKeyDoorName(LevelName.FAREWELL, "d-00", 471), getKeyDoorName(LevelName.FAREWELL, "d-00", 145), getKeyDoorName(LevelName.FAREWELL, "d-00", 144), getKeyDoorName(LevelName.FAREWELL, "d-00", 142), getKeyDoorName(LevelName.FAREWELL, "d-00", 197)]]), Transition("d-01", [[ItemName.RED_BUBBLES, ItemName.DOUBLE_DASH_CRYSTALS, ItemName.DASH_SWITCH, ItemName.SPRINGS, ItemName.JELLYFISH, ItemName.BREAKER_BOX]]), Transition("d-02", [[ItemName.RED_BUBBLES, ItemName.DOUBLE_DASH_CRYSTALS, ItemName.DASH_SWITCH, ItemName.SPRINGS]]), Transition("d-03", [[ItemName.RED_BUBBLES]]), Transition("d-04", [[ItemName.RED_BUBBLES, ItemName.DOUBLE_DASH_CRYSTALS, ItemName.DASH_SWITCH, ItemName.SPRINGS, ItemName.JELLYFISH, ItemName.BREAKER_BOX]]), Transition("d-05", [[ItemName.RED_BUBBLES, ItemName.DOUBLE_DASH_CRYSTALS, ItemName.DASH_SWITCH, ItemName.SPRINGS, ItemName.JELLYFISH, ItemName.BREAKER_BOX]])], key_door_ids=[471, 145, 144, 142, 197]),
            "d-01": Room(23, [Transition("d-00")], [Location(LocationType.KEY, 261, [[ItemName.DASH_CRYSTALS]])]),
            "d-02": Room(24, [Transition("d-00")], [Location(LocationType.KEY, 70, [[ItemName.MOVING_BLOCK, ItemName.JELLYFISH, ItemName.BREAKER_BOX]])]),
            "d-03": Room(25, [Transition("d-00")], [Location(LocationType.KEY, 315, [[ItemName.DOUBLE_DASH_CRYSTALS, ItemName.DASH_SWITCH, ItemName.SPRINGS, ItemName.JELLYFISH, ItemName.BREAKER_BOX]])]),
            "d-04": Room(26, [Transition("d-00")], [Location(LocationType.KEY, 444)]),
            "d-05": Room(27, [Transition("d-00")], [Location(LocationType.KEY, 593, [[ItemName.TOUCH_SWITCH]])]),
            "e-00y": Room(28, [Transition("e-00z"), Transition("e-00yb")]),
            "e-00z": Room(29, [Transition("e-00")], checkpoint="Remembered"),
            "e-00": Room(30, [Transition("e-00b", [[ItemName.CLOUDS, ItemName.PUFFER_FISH, ItemName.TOUCH_SWITCH, ItemName.DOUBLE_DASH_CRYSTALS]])]),
            "e-00b": Room(31, [Transition("e-01", [[ItemName.SPRINGS, ItemName.JELLYFISH]])]),
            "e-01": Room(32, [Transition("e-02", [[ItemName.DASH_CRYSTALS]])]),
            "e-02": Room(33, [Transition("e-03")]),
            "e-03": Room(34, [Transition("e-04")]),
            "e-04": Room(35, [Transition("e-05", [[ItemName.DASH_SWITCH]])]),
            "e-05": Room(36, [Transition("e-05b", [[ItemName.TRAFFIC_BLOCKS]])]),
            "e-05b": Room(37, [Transition("e-05c", [[ItemName.SWAP_BLOCK]])]),
            "e-05c": Room(38, [Transition("e-06")]),
            "e-06": Room(39, [Transition("e-07")]),
            "e-07": Room(40, [Transition("e-08", [[ItemName.MOVING_BLOCK]])]),
            "e-08": Room(41, [Transition("f-door")]),
            "f-door": Room(42, [Transition("f-00", [[CHearts(15)]])], checkpoint="Event Horizon"),
            "f-00": Room(43, [Transition("f-01", [[ItemName.DREAM_BLOCK]])]),
            "f-01": Room(44, [Transition("f-02")]),
            "f-02": Room(45, [Transition("f-03")]),
            "f-03": Room(46, [Transition("f-04", [[ItemName.DOUBLE_DASH_CRYSTALS]])]),
            "f-04": Room(47, [Transition("f-05")]),
            "f-05": Room(48, [Transition("f-06")]),
            "f-06": Room(49, [Transition("f-07", [[ItemName.KEVIN, ItemName.TOUCH_SWITCH]])]),
            "f-07": Room(50, [Transition("f-08", [[ItemName.TRAFFIC_BLOCKS, ItemName.DASH_CRYSTALS]])]),
            "f-08": Room(51, [Transition("f-09", [[ItemName.MOVING_BLOCK]])]),
            "f-09": Room(52, [Transition("g-00")]),
            "g-00": Room(53, [Transition("g-01")]),
            "g-01": Room(54, [Transition("g-03", [[ItemName.GREEN_BUBBLES, ItemName.CRUMBLING_PLATFORM]])]),
            "g-03": Room(55, [Transition("g-02")]),
            "g-02": Room(56, [Transition("g-04")]),
            "g-04": Room(57, [Transition("g-05", [[ItemName.SPRINGS]])]),
            "g-05": Room(58, [Transition("g-06")]),
            "g-06": Room(59, [Transition("h-00b", [[ItemName.FEATHER]])]),
            "h-00b": Room(60, [Transition("h-00", [[ItemName.FEATHER, ItemName.DOUBLE_DASH_CRYSTALS]])], checkpoint="Determination"),
            "h-00": Room(61, [Transition("h-01", [[ItemName.SWAP_BLOCK, ItemName.DASH_CRYSTALS]])]),
            "h-01": Room(62, [Transition("h-02", [[ItemName.MOVING_BLOCK, ItemName.SPRINGS]])]),
            "h-02": Room(63, [Transition("h-03", [[ItemName.RED_BUBBLES]])]),
            "h-03": Room(64, [Transition("h-03b", [[ItemName.TOUCH_SWITCH]])]),
            "h-03b": Room(65, [Transition("h-04", [[ItemName.CORE_BLOCK]])]),
            "h-04": Room(66, [Transition("h-05"), Transition("h-04b")]),
            "h-05": Room(67, [Transition("h-06")]),
            "h-06": Room(68, [Transition("h-06b")]),
            "h-06b": Room(69, [Transition("h-07", [[ItemName.LAVA_ICE_BALLS]])]),
            "h-07": Room(70, [Transition("h-08", [[ItemName.GREEN_BUBBLES]])]),
            "h-08": Room(71, [Transition("h-09")]),
            "h-09": Room(72, [Transition("h-10", [[ItemName.KEVIN]])]),
            "h-10": Room(73, [Transition("i-00", [[ItemName.BADELINE_ORB]])]),
            "i-00": Room(74, [Transition("i-00b", [[ItemName.PINK_CASSETTE, ItemName.YELLOW_CASSETTE, ItemName.GREEN_CASSETTE], [ItemName.PINK_CASSETTE, ItemName.YELLOW_CASSETTE, ItemName.BLUE_CASSETTE]])], checkpoint="Stubbornness"),
            "i-00b": Room(75, [Transition("i-01", [[ItemName.BLUE_CASSETTE, ItemName.PINK_CASSETTE, ItemName.YELLOW_CASSETTE, ItemName.GREEN_CASSETTE, ItemName.DOUBLE_DASH_CRYSTALS, ItemName.DASH_CRYSTALS, ItemName.SPRINGS]])]),
            "i-01": Room(76, [Transition("i-02", [[ItemName.TOUCH_SWITCH]])]),
            "i-02": Room(77, [Transition("i-03")]),
            "i-03": Room(78, [Transition("i-04")]),
            "i-04": Room(79, [Transition("i-05", [[ItemName.RED_BUBBLES]])]),
            "i-05": Room(80, [Transition("j-00")]),
            "j-00": Room(81, [Transition("j-00b", [[ItemName.BREAKER_BOX]])], checkpoint="Reconciliation"),
            "j-00b": Room(82, [Transition("j-01", [[ItemName.BADELINE_ORB, ItemName.JELLYFISH, ItemName.BIRD, ItemName.DOUBLE_DASH_CRYSTALS, ItemName.SPRINGS]])]),
            "j-01": Room(83, [Transition("j-02", [[ItemName.DASH_CRYSTALS]])]),
            "j-02": Room(84, [Transition("j-03")]),
            "j-03": Room(85, [Transition("j-04", [[ItemName.PUFFER_FISH]])]),
            "j-04": Room(86, [Transition("j-05")]),
            "j-05": Room(87, [Transition("j-06", [[ItemName.FEATHER]])]),
            "j-06": Room(88, [Transition("j-07")]),
            "j-07": Room(89, [Transition("j-08")]),
            "j-08": Room(90, [Transition("j-09", [[ItemName.DREAM_BLOCK]])]),
            "j-09": Room(91, [Transition("j-10")]),
            "j-10": Room(92, [Transition("j-11", [[ItemName.SWAP_BLOCK]])]),
            "j-11": Room(93, [Transition("j-12", [[ItemName.MOVING_BLOCK]])]),
            "j-12": Room(94, [Transition("j-13")]),
            "j-13": Room(95, [Transition("j-14")]),
            "j-14": Room(96, [Transition("j-14b", [[ItemName.TRAFFIC_BLOCKS]])]),
            "j-14b": Room(97, [Transition("j-15")]),
            "j-15": Room(98, [Transition("j-16", [[ItemName.KEVIN]])]),
            "j-16": Room(99, [Transition("j-17", farewell_final_room_reqs)], [Location(LocationType.LEVEL_CLEAR, access_rule=farewell_final_room_reqs)], checkpoint="Farewell"),
            "j-17": Room(100, [Transition("j-18")]),
            "j-18": Room(101, [Transition("j-19"), Transition("j-17")]),
            "j-19": Room(102, [], [Location(LocationType.STRAWBERRY, 9)]),
            "c-alt-00": Room(104, [Transition("c-alt-01", [[ItemName.DOUBLE_DASH_CRYSTALS]])], excluded=True),
            "c-alt-01": Room(105, [Transition("c-03")], excluded=True),
            "e-00yb": Room(106, [Transition("e-00y", [[ItemName.DASH_CRYSTALS, ItemName.DOUBLE_DASH_CRYSTALS, ItemName.RED_BUBBLES]])], excluded=True),
            "h-04b": Room(107, [Transition("h-05")])
        }, LevelCategory.FAREWELL, 25
    ),
    LevelName.PROLOGUE:
    Level(
        {
            "01": Room(0, [Transition("1"), Transition("-1"), Transition("0b")], start_room=True),
            "-1": Room(1, [Transition("01")]),
            "0b": Room(2, [Transition("01")]),
            "1": Room(3, [Transition("2"), Transition("01")]),
            "2": Room(4, [Transition("3"), Transition("1")]),
            "3": Room(5, [Transition("2")], [Location(LocationType.LEVEL_CLEAR)])
        }, LevelCategory.A_SIDE, 26
    )
}