from ..Naming import getKeyDoorName, getLocationName
from ..constants.ItemNames import ItemName
from ..constants.LevelNames import LevelCategory, LevelName
from .LogicalObjects import Level, Room, Transition, Location
from ..constants.LocationTypes import LocationType



vanilla_levels : dict[LevelName, Level] = {
    LevelName.FORSAKEN_CITY_A:
    Level(
        {
            "1": Room(1, [Transition("2")], [Location(LocationType.GOLDEN_BERRY, 12, [[ItemName.TRAFFIC_BLOCKS, ItemName.DASH_CRYSTALS]])], start_room=True),
            "2": Room(2, [Transition("3")], [Location(LocationType.STRAWBERRY, 11)]),
            "3": Room(3, [Transition("4")], [Location(LocationType.STRAWBERRY, 9)]),
            "4": Room(4, [Transition("3b")]),
            "3b": Room(0, [Transition("5")], [Location(LocationType.STRAWBERRY, 2)]),
            "5": Room(5, [Transition("5z"), Transition("5a", [[ItemName.TRAFFIC_BLOCKS]]), Transition("6", [[ItemName.TRAFFIC_BLOCKS]])], [Location(LocationType.STRAWBERRY, 21)]),
            "5z": Room(13, [Transition("5")], [Location(LocationType.STRAWBERRY, 10)]),
            "5a": Room(14, [Transition("5")], [Location(LocationType.STRAWBERRY, 2)]),
            "6": Room(6, [Transition("6z"), Transition("6a", [[ItemName.DASH_CRYSTALS]])], [Location(LocationType.STRAWBERRY, 12, [[ItemName.DASH_CRYSTALS]])], checkpoint="Crossing"),
            "6z": Room(15, [Transition("6"), Transition("6zb"), Transition("7zb")]),
            "6zb": Room(16, [Transition("6z")]),
            "7zb": Room(17, [Transition("6z"), Transition("6zb")], [Location(LocationType.STRAWBERRY, 2)]),
            "6a": Room(18, [Transition("6z"), Transition("6b")]),
            "6b": Room(19, [Transition("6a"), Transition("s0"), Transition("6c")]),
            "s0": Room(20, [Transition("6b"), Transition("s1", [[ItemName.TRAFFIC_BLOCKS]])]),
            "s1": Room(21, [Transition("s0")], [Location(LocationType.STRAWBERRY, 9), Location(LocationType.CRYSTAL_HEART)]),
            "6c": Room(22, [Transition("6b"), Transition("7"), Transition("7z")]),
            "7z": Room(23, [Transition("6c"), Transition("8z")], [Location(LocationType.STRAWBERRY, 3, [[ItemName.DASH_CRYSTALS]])]),
            "7": Room(7, [Transition("8")]),
            "8z": Room(24, [Transition("7z"), Transition("8zb")]),
            "8zb": Room(25, [Transition("8z"), Transition("8", [[ItemName.DASH_CRYSTALS]])], [Location(LocationType.STRAWBERRY, 1)]),
            "8": Room(8, [Transition("7a"), Transition("8b"), Transition("9z")]),
            "9z": Room(26, [Transition("8")], [Location(LocationType.STRAWBERRY, 3, [[ItemName.TRAFFIC_BLOCKS]])]),
            "7a": Room(27, [Transition("8")], [Location(LocationType.STRAWBERRY, 12)]),
            "8b": Room(28, [Transition("8"), Transition("9")], [Location(LocationType.STRAWBERRY, 1)]),
            "9": Room(9, [Transition("9b")], [Location(LocationType.STRAWBERRY, 14, [[ItemName.TRAFFIC_BLOCKS]])]),
            "9b": Room(30, [Transition("10", [[ItemName.TRAFFIC_BLOCKS]]), Transition("10a"), Transition("9c")], [Location(LocationType.STRAWBERRY, 9)], checkpoint="Chasm"),
            "10": Room(10, [Transition("10z"), Transition("9b"), Transition("11-bottom", [[ItemName.TRAFFIC_BLOCKS]])]),
            "10z": Room(31, [Transition("10"), Transition("10zb")]),
            "10zb": Room(32, [Transition("10z")], [Location(LocationType.STRAWBERRY, 1)]),
            "11-bottom": Room(33, [Transition("10", [[ItemName.TRAFFIC_BLOCKS]]), Transition("11z", [[ItemName.TRAFFIC_BLOCKS]])], [Location(LocationType.STRAWBERRY, 9, [[ItemName.TRAFFIC_BLOCKS]])], is_subregion_of="11"),
            "11z": Room(34, [Transition("11-bottom")], [Location(LocationType.CASSETTE, access_rule=[[ItemName.BLUE_CASSETTE], [ItemName.PINK_CASSETTE]])]),
            "9c": Room(35, [Transition("9b")], [Location(LocationType.STRAWBERRY, 2, [[ItemName.TRAFFIC_BLOCKS]])]),
            "10a": Room(36, [Transition("9b"), Transition("11")]),
            "11": Room(11, [Transition("10a"), Transition("12")]),
            "12": Room(12, [Transition("12a"), Transition("12z")]),
            "12z": Room(37, [Transition("12")], [Location(LocationType.STRAWBERRY, 8, [[ItemName.DASH_CRYSTALS]])]),
            "12a": Room(38, [Transition("12"), Transition("end", [[ItemName.TRAFFIC_BLOCKS], [ItemName.SPRINGS]])]),
            "end": Room(39, [], [Location(LocationType.LEVEL_CLEAR), Location(LocationType.WINGED_GOLDEN, 4, [[ItemName.TRAFFIC_BLOCKS, ItemName.DASH_CRYSTALS]])])
        }, LevelCategory.A_SIDE, 1
    ),
    LevelName.FORSAKEN_CITY_B:
    Level(
        {
            "00": Room(0, [Transition("01")], [Location(LocationType.GOLDEN_BERRY, 25, [[ItemName.TRAFFIC_BLOCKS, ItemName.DASH_CRYSTALS, ItemName.BLUE_CASSETTE]])], start_room=True),
            "01": Room(1, [Transition("02")]),
            "02": Room(2, [Transition("02b", [[ItemName.TRAFFIC_BLOCKS]])]),
            "02b": Room(3, [Transition("03")]),
            "03": Room(4, [Transition("04", [[ItemName.DASH_CRYSTALS]])]),
            "04": Room(5, [Transition("05", [[ItemName.TRAFFIC_BLOCKS]]), Transition("03")], checkpoint="Contraption"),
            "05": Room(6, [Transition("05b")]),
            "05b": Room(7, [Transition("06", [[ItemName.DASH_CRYSTALS]])]),
            "06": Room(8, [Transition("07")]),
            "07": Room(9, [Transition("08"), Transition("06")]),
            "08": Room(10, [Transition("08b", [[ItemName.TRAFFIC_BLOCKS, ItemName.CRUMBLING_PLATFORM]])], checkpoint="Scrap Pit"),
            "08b": Room(11, [Transition("09")]),
            "09": Room(12, [Transition("10")]),
            "10": Room(13, [Transition("11", [[ItemName.DASH_CRYSTALS]]), Transition("09")]),
            "11": Room(14, [Transition("end", [[ItemName.CRUMBLING_PLATFORM]])]),
            "end": Room(15, [], [Location(LocationType.CRYSTAL_HEART, access_rule=[[ItemName.BLUE_CASSETTE]])])
        }, LevelCategory.B_SIDE, 2
    ),
    LevelName.FORSAKEN_CITY_C:
    Level(
        {
            "00": Room(0, [Transition("01", [[ItemName.DASH_CRYSTALS, ItemName.TRAFFIC_BLOCKS]])], [Location(LocationType.GOLDEN_BERRY, 50)], start_room=True),
            "01": Room(1, [Transition("02")]),
            "02": Room(2, [], [Location(LocationType.CRYSTAL_HEART, access_rule=[[ItemName.TOUCH_SWITCH]])])
        }, LevelCategory.C_SIDE, 3
    ),
    LevelName.OLD_SITE_A:
    Level(
        {
            "start": Room(0, [Transition("0"), Transition("s0")], [Location(LocationType.GOLDEN_BERRY, 5, [[ItemName.DREAM_BLOCK, ItemName.TOUCH_SWITCH]])], start_room=True),
            "s0": Room(1, [Transition("start"), Transition("s1")]),
            "0": Room(2, [Transition("3x", [[ItemName.DREAM_BLOCK]]), Transition("start"), Transition("1", [[ItemName.DREAM_BLOCK]]), Transition("1-bottom")]),
            "1": Room(3, [Transition("0")], [Location(LocationType.STRAWBERRY, 1)]),
            "1-bottom": Room(100, [Transition("0"), Transition("d0"), Transition("2-covered")], is_subregion_of="1"),
            "2-covered": Room(101, [Transition("1-bottom")], is_subregion_of="2"),
            "3x": Room(4, [Transition("3", [[ItemName.DREAM_BLOCK]]), Transition("0")]),
            "3": Room(5, [Transition("4", [[ItemName.DREAM_BLOCK]]), Transition("3x")], checkpoint="Intervention"),
            "4": Room(6, [Transition("5")], [Location(LocationType.STRAWBERRY, 4)]),
            "5": Room(7, [Transition("6")], [Location(LocationType.STRAWBERRY, 15)]),
            "6": Room(8, [Transition("7", [[ItemName.TOUCH_SWITCH]])]),
            "7": Room(9, [Transition("8")]),
            "8": Room(10, [Transition("9")], [Location(LocationType.STRAWBERRY, 18)]),
            "9": Room(11, [Transition("10"), Transition("9b")], [Location(LocationType.STRAWBERRY, 22)]),
            "9b": Room(12, [Transition("9")], [Location(LocationType.STRAWBERRY, 5)]),
            "10": Room(13, [Transition("2")], [Location(LocationType.STRAWBERRY, 27)]),
            "2": Room(14, [Transition("11")]),
            "11": Room(15, [Transition("12b"), Transition("2")]),
            "12b": Room(16, [Transition("12"), Transition("11"), Transition("12c"), Transition("12d")]),
            "12c": Room(17, [Transition("12b")], [Location(LocationType.STRAWBERRY, 7)]),
            "12d": Room(18, [Transition("12b")], [Location(LocationType.STRAWBERRY, 44)]),
            "12": Room(19, [Transition("13"), Transition("12b")]),
            "13": Room(20, [Transition("end_0"), Transition("12")]),
            "end_0": Room(21, [Transition("end_1"), Transition("end_s0")]),
            "end_1": Room(22, [Transition("end_2"), Transition("end_0"), Transition("end_s0")]),
            "end_2": Room(23, [Transition("end_3"), Transition("end_1")]),
            "end_3": Room(24, [Transition("end_4"), Transition("end_2")], checkpoint="Awake"),
            "end_4": Room(25, [Transition("end_3b"), Transition("end_3")]),
            "end_3b": Room(26, [Transition("end_5"), Transition("end_4"), Transition("end_3cb")]),
            "end_5": Room(27, [Transition("end_6"), Transition("end_3b")]),
            "end_6": Room(28, [Transition("end_5")], [Location(LocationType.LEVEL_CLEAR)]),
            "s1": Room(30, [Transition("s2"), Transition("s0")]),
            "s2": Room(31, [Transition("s1")], [Location(LocationType.CRYSTAL_HEART)]),
            "d0": Room(32, [Transition("d1"), Transition("d6"), Transition("d9", [[ItemName.DREAM_BLOCK]]), Transition("d7"), Transition("d2"), Transition("d4")], [Location(LocationType.STRAWBERRY, 6, [[ItemName.DREAM_BLOCK]])]),
            "d1": Room(33, [Transition("d0"), Transition("d6")], [Location(LocationType.STRAWBERRY, 67, [[ItemName.DREAM_BLOCK]])]),
            "d6": Room(34, [Transition("d0"), Transition("d1")], [Location(LocationType.STRAWBERRY, 2)]),
            "d9": Room(35, [Transition("d0", [[ItemName.DREAM_BLOCK]])], [Location(LocationType.CASSETTE, access_rule=[[ItemName.BLUE_CASSETTE, ItemName.PINK_CASSETTE]])]),
            "d7": Room(36, [Transition("d0"), Transition("d8")]),
            "d2": Room(37, [Transition("d0")], [Location(LocationType.STRAWBERRY, 9, [[ItemName.DREAM_BLOCK]])]),
            "d2-berry": Room(102, [Transition("d2")], [Location(LocationType.STRAWBERRY, 31)], is_subregion_of="d2"),
            "d4": Room(38, [Transition("d0"), Transition("d2-berry"), Transition("d5")], [Location(LocationType.STRAWBERRY, 6, [[ItemName.DREAM_BLOCK]])]),
            "d5": Room(39, [Transition("d4")], [Location(LocationType.STRAWBERRY, 12)]),
            "d8": Room(40, [Transition("d3"), Transition("d7"), Transition("d3-berry")]),
            "d3": Room(41, [Transition("d2")]),
            "d3-berry": Room(104, [Transition("d8")], [Location(LocationType.STRAWBERRY, 10)], is_subregion_of="d3"),
            "end_s0": Room(42, [Transition("end_s1"), Transition("end_0"), Transition("end_1")]),
            "end_s1": Room(43, [Transition("end_s0")]),
            "end_3cb": Room(44, [Transition("end_3c"), Transition("end_3b")]),
            "end_3c": Room(45, [Transition("end_3cb")], [Location(LocationType.STRAWBERRY, 13, [[ItemName.SPRINGS, ItemName.CRUMBLING_PLATFORM]])])
        }, LevelCategory.A_SIDE, 4
    ),
    LevelName.OLD_SITE_B:
    Level(
        {
            "start": Room(0, [Transition("00")], [Location(LocationType.GOLDEN_BERRY, 5, [[ItemName.DREAM_BLOCK, ItemName.DASH_CRYSTALS, ItemName.TOUCH_SWITCH, ItemName.BLUE_CASSETTE]])], start_room=True),
            "00": Room(1, [Transition("01", [[ItemName.DREAM_BLOCK]]), Transition("start")]),
            "01": Room(2, [Transition("01b")]),
            "01b": Room(3, [Transition("02b", [[ItemName.DASH_CRYSTALS]])]),
            "02b": Room(4, [Transition("02")]),
            "02": Room(5, [Transition("03")]),
            "03": Room(6, [Transition("04", [[ItemName.TOUCH_SWITCH, ItemName.DREAM_BLOCK]])], checkpoint="Combination Lock"),
            "04": Room(7, [Transition("05", [[ItemName.DASH_CRYSTALS]])]),
            "05": Room(8, [Transition("06")]),
            "06": Room(9, [Transition("07")]),
            "07": Room(10, [Transition("08b")]),
            "08b": Room(11, [Transition("08", [[ItemName.DREAM_BLOCK]])], checkpoint="Dream Altar"),
            "08": Room(12, [Transition("10", [[ItemName.DASH_CRYSTALS]])]),
            "10": Room(13, [Transition("11", [[ItemName.TOUCH_SWITCH]])]),
            "11": Room(14, [Transition("end")]),
            "end": Room(15, [], [Location(LocationType.CRYSTAL_HEART, access_rule=[[ItemName.DASH_CRYSTALS, ItemName.BLUE_CASSETTE]])])
        }, LevelCategory.B_SIDE, 5
    ),
    LevelName.OLD_SITE_C:
    Level(
        {
            "00": Room(0, [Transition("01", [[ItemName.DREAM_BLOCK]])], [Location(LocationType.GOLDEN_BERRY, 6, [[ItemName.DREAM_BLOCK, ItemName.TOUCH_SWITCH, ItemName.DASH_CRYSTALS]])], start_room=True),
            "01": Room(1, [Transition("02", [[ItemName.TOUCH_SWITCH]])]),
            "02": Room(2, [], [Location(LocationType.CRYSTAL_HEART, access_rule=[[ItemName.DASH_CRYSTALS]])])
        }, LevelCategory.C_SIDE, 6
    ),
    LevelName.CELESTIAL_RESORT_A:
    Level(
        {
            "s0": Room(0, [Transition("s1")], [Location(LocationType.GOLDEN_BERRY, 7, [[ItemName.DASH_CRYSTALS, ItemName.TOUCH_SWITCH, ItemName.SPRINGS, getKeyDoorName(LevelName.CELESTIAL_RESORT_A, "02-a", 9), getKeyDoorName(LevelName.CELESTIAL_RESORT_A, "07-a", 11), getKeyDoorName(LevelName.CELESTIAL_RESORT_A, "09-b", 2), getKeyDoorName(LevelName.CELESTIAL_RESORT_A, "04-c", 17)]])], start_room=True),
            "s1": Room(1, [Transition("s2"), Transition("s0")]),
            "s2": Room(2, [Transition("s3"), Transition("s1")], [Location(LocationType.STRAWBERRY, 6), Location(LocationType.STRAWBERRY, 18)]),
            "s3": Room(3, [Transition("0x-a"), Transition("s2")], [Location(LocationType.KEY, 15)]),
            "s3-berry": Room(110, [Transition("0x-b")], [Location(LocationType.STRAWBERRY, 2)], is_subregion_of="s3"),
            "0x-a": Room(4, [Transition("00a"), Transition("s3")]),
            "00a": Room(5, [Transition("02-a"), Transition("0x-a")], [Location(LocationType.STRAWBERRY, 5)]),
            "02-a": Room(6, [Transition("03-a", [[getKeyDoorName(LevelName.CELESTIAL_RESORT_A, "02-a", 9)]]), Transition("02-b")], key_door_ids=[9]),
            "02-b": Room(7, [Transition("02-a"), Transition("01-b")], [Location(LocationType.KEY, 32)]),
            "02-b-corner": Room(104, [Transition("03-b")], is_subregion_of="02-b"),
            "03-a": Room(8, [Transition("05-a"), Transition("02-a"), Transition("04-b", [[ItemName.SINKING_PLATFORM]])]),
            "04-b": Room(9, [Transition("03-a")], [Location(LocationType.STRAWBERRY, 14, [[ItemName.DASH_CRYSTALS]])]),
            "04-b-corner": Room(105, [Transition("03-b")], is_subregion_of="04-b"),
            "05-a": Room(10, [Transition("06-a"), Transition("03-a")]),
            "06-a": Room(11, [Transition("07-a"), Transition("05-a")], [Location(LocationType.STRAWBERRY, 7)]),
            "07-a": Room(12, [Transition("08-a", [[getKeyDoorName(LevelName.CELESTIAL_RESORT_A, "07-a", 11)]]), Transition("07-b")], key_door_ids=[11]),
            "08-a": Room(13, [Transition("09-b"), Transition("08-x", [[ItemName.TOUCH_SWITCH, ItemName.DASH_CRYSTALS]])], checkpoint="Huge Mess"),
            "08-x": Room(14, [Transition("08-a")], [Location(LocationType.STRAWBERRY, 4)]),
            "09-b": Room(15, [Transition("09-d", [[getKeyDoorName(LevelName.CELESTIAL_RESORT_A, "09-b", 2)]]), Transition("08-a"), Transition("10-c"), Transition("11-b"), Transition("11-a"), Transition("10-x-corner")], [Location(LocationType.KEY, 13, [[ItemName.TOUCH_SWITCH, ItemName.DASH_CRYSTALS]])], key_door_ids=[2]),
            "09-d": Room(16, [Transition("08-d")], checkpoint="Elevator Shaft"),
            "08-d": Room(17, [Transition("06-d", [[ItemName.DASH_CRYSTALS, ItemName.TOUCH_SWITCH]])]),
            "06-d": Room(18, [Transition("04-d", [[ItemName.DASH_CRYSTALS]])], [Location(LocationType.STRAWBERRY, 238)]),
            "04-d": Room(19, [Transition("04-c")]),
            "04-c": Room(20, [Transition("02-d", [[getKeyDoorName(LevelName.CELESTIAL_RESORT_A, "04-c", 17)]]), Transition("04-d"), Transition("02-c")], [Location(LocationType.STRAWBERRY, 40)], key_door_ids=[17]),
            "02-d": Room(21, [Transition("00-d", [[ItemName.DASH_CRYSTALS]])]),
            "00-d": Room(22, [Transition("roof00"), Transition("02-d")], checkpoint="Presidential Suite"),
            "roof00": Room(23, [Transition("roof01")]),
            "roof01": Room(24, [Transition("roof02")]),
            "roof02": Room(25, [Transition("roof03")]),
            "roof03": Room(26, [Transition("roof04", [[ItemName.TOUCH_SWITCH]])], [Location(LocationType.STRAWBERRY, 97)]),
            "roof04": Room(27, [Transition("roof05")]),
            "roof05": Room(28, [Transition("roof06b")]),
            "roof06b": Room(29, [Transition("roof06", [[ItemName.DASH_CRYSTALS]])]),
            "roof06": Room(30, [Transition("roof07")], [Location(LocationType.STRAWBERRY, 276), Location(LocationType.STRAWBERRY, 308)]),
            "roof07": Room(31, [], [Location(LocationType.LEVEL_CLEAR)]),
            "01-b": Room(33, [Transition("02-b"), Transition("00-b-hallway"), Transition("00-b")]),
            "00-b": Room(34, [Transition("01-b"), Transition("00-c")], [Location(LocationType.STRAWBERRY, 42)]),
            "00-b-hallway": Room(101, [Transition("01-b"), Transition("0x-b-hallway")], is_subregion_of="00-b"),
            "0x-b-hallway": Room(102, [Transition("0x-b-hallway")], is_subregion_of="0x-b"),
            "00-c": Room(35, [Transition("00-b"), Transition("0x-b", [[ItemName.DASH_CRYSTALS]]), Transition("01-c-corner")]),
            "0x-b": Room(36, [Transition("0x-b-hallway"), Transition("s3-berry")]),
            "07-b": Room(37, [Transition("07-a"), Transition("06-b")]),
            "07-b-berry": Room(106, [Transition("06-c")], [Location(LocationType.STRAWBERRY, 4)], is_subregion_of="07-b"),
            "07-b-key": Room(107, [Transition("08-b"), Transition("07-b")], [Location(LocationType.KEY, 2)], is_subregion_of="07-b"),
            "06-b": Room(38, [Transition("07-b"), Transition("06-c")], [Location(LocationType.STRAWBERRY, 14)]),
            "06-c": Room(39, [Transition("07-b-berry"), Transition("05-c"), Transition("08-c")], [Location(LocationType.STRAWBERRY, 3)]),
            "05-c": Room(40, [Transition("06-c")], [Location(LocationType.STRAWBERRY, 2, [[ItemName.CRUMBLING_PLATFORM]])]),
            "08-c": Room(41, [Transition("08-b", [[ItemName.TOUCH_SWITCH]])]),
            "08-b": Room(42, [Transition("07-b-key", [[ItemName.SINKING_PLATFORM]])]),
            "10-x": Room(43, [Transition("09-b")]),
            "10-x-corner": Room(108, [Transition("09-b"), Transition("11-x")], is_subregion_of="10-x"),
            "11-x": Room(44, [Transition("11-y", [[ItemName.TOUCH_SWITCH]])]),
            "11-y": Room(45, [Transition("12-y"), Transition("11-z")]),
            "12-y": Room(46, [Transition("11-y")], [Location(LocationType.STRAWBERRY, 1)]),
            "11-z": Room(47, [Transition("11-y"), Transition("10-z")]),
            "10-z": Room(48, [Transition("11-z"), Transition("10-y")]),
            "10-y": Room(49, [Transition("10-x")], [Location(LocationType.STRAWBERRY, 2)]),
            "11-b": Room(50, [Transition("12-b"), Transition("11-c-heart")]),
            "12-b": Room(51, [Transition("11-b"), Transition("13-b")]),
            "13-b": Room(52, [Transition("12-b"), Transition("13-a")], [Location(LocationType.STRAWBERRY, 31)]),
            "13-a": Room(53, [Transition("13-b"), Transition("13-x")]),
            "13-x": Room(54, [Transition("12-x"), Transition("13-a")], [Location(LocationType.STRAWBERRY, 13)]),
            "12-x": Room(55, [Transition("11-a"), Transition("13-a")]),
            "11-a": Room(56, [Transition("09-b")]),
            "10-c": Room(57, [Transition("09-b"), Transition("11-c")]),
            "11-c": Room(58, [Transition("10-c"), Transition("12-c"),]),
            "11-c-heart": Room(109, [Transition("11-b")], [Location(LocationType.CRYSTAL_HEART)], is_subregion_of="11-c"),
            "12-c": Room(59, [Transition("11-c"), Transition("12-d")], [Location(LocationType.STRAWBERRY, 1)]),
            "12-d": Room(60, [Transition("11-d")]),
            "11-d": Room(61, [Transition("12-d"), Transition("10-d", [[ItemName.DASH_CRYSTALS]])], [Location(LocationType.STRAWBERRY, 52, [[ItemName.DASH_CRYSTALS]])]),
            "10-d": Room(62, [Transition("09-b")]),
            "03-b": Room(63, [Transition("02-c"), Transition("02-b-corner"), Transition("04-b-corner")], [Location(LocationType.STRAWBERRY, 25), Location(LocationType.STRAWBERRY, 1)]),
            "01-c": Room(64, [Transition("02-c")], [Location(LocationType.CASSETTE, access_rule=[[ItemName.BLUE_CASSETTE, ItemName.PINK_CASSETTE]])]),
            "01-c-corner": Room(103, [Transition("00-c")], is_subregion_of="01-c"),
            "02-c": Room(66, [Transition("04-c"), Transition("03-b"), Transition("01-c", [[ItemName.SINKING_PLATFORM]])], [Location(LocationType.KEY, 1, [[ItemName.SINKING_PLATFORM]])])
        }, LevelCategory.A_SIDE, 7
    ),
    LevelName.CELESTIAL_RESORT_B:
    Level(
        {
            "00": Room(0, [Transition("01"), Transition("back")], [Location(LocationType.GOLDEN_BERRY, 2, [[ItemName.DASH_CRYSTALS, ItemName.TOUCH_SWITCH, ItemName.SINKING_PLATFORM, ItemName.SPRINGS, ItemName.BLUE_CASSETTE, ItemName.PINK_CASSETTE]])], start_room=True),
            "back": Room(1, [Transition("00")]),
            "01": Room(2, [Transition("02", [[ItemName.DASH_CRYSTALS]])]),
            "02": Room(3, [Transition("03")]),
            "03": Room(4, [Transition("04")]),
            "04": Room(5, [Transition("05")]),
            "05": Room(6, [Transition("06", [[ItemName.TOUCH_SWITCH]])]),
            "06": Room(7, [Transition("07", [[ItemName.SINKING_PLATFORM]])], checkpoint="Staff Quarters"),
            "07": Room(8, [Transition("08")]),
            "08": Room(9, [Transition("09", [[ItemName.DASH_CRYSTALS]])]),
            "09": Room(10, [Transition("10")]),
            "10": Room(11, [Transition("11")]),
            "11": Room(12, [Transition("13", [[ItemName.DASH_CRYSTALS]])], checkpoint="Library"),
            "13": Room(13, [Transition("14")]),
            "14": Room(14, [Transition("15")]),
            "15": Room(15, [Transition("12")]),
            "12": Room(16, [Transition("16")]),
            "16": Room(17, [Transition("17")], checkpoint="Rooftop"),
            "17": Room(18, [Transition("18", [[ItemName.DASH_CRYSTALS]])]),
            "18": Room(19, [Transition("19")]),
            "19": Room(20, [Transition("21", [[ItemName.SPRINGS]])]),
            "21": Room(21, [Transition("20")]),
            "20": Room(22, [Transition("end", [[ItemName.TOUCH_SWITCH]])]),
            "end": Room(23, [], [Location(LocationType.CRYSTAL_HEART, access_rule=[[ItemName.BLUE_CASSETTE, ItemName.PINK_CASSETTE]])])
        }, LevelCategory.B_SIDE, 8
    ),
    LevelName.CELESTIAL_RESORT_C:
    Level(
        {
            "00": Room(0, [Transition("01", [[ItemName.DASH_CRYSTALS]])], [Location(LocationType.GOLDEN_BERRY, 86, [[ItemName.DASH_CRYSTALS, ItemName.SINKING_PLATFORM, ItemName.TOUCH_SWITCH]])], start_room=True),
            "01": Room(1, [Transition("02", [[ItemName.SINKING_PLATFORM]])]),
            "02": Room(2, [], [Location(LocationType.CRYSTAL_HEART, access_rule=[[ItemName.TOUCH_SWITCH]])])
        }, LevelCategory.C_SIDE, 9
    ),
    LevelName.GOLDEN_RIDGE_A:
    Level(
        {
            "a-00": Room(0, [Transition("a-01")], [Location(LocationType.GOLDEN_BERRY, 13, [[ItemName.CRUMBLING_PLATFORM, ItemName.MOVING_BLOCK, ItemName.PINK_CLOUDS, ItemName.SPRINGS, ItemName.CLOUDS, ItemName.TOUCH_SWITCH, ItemName.GREEN_BUBBLES]])], start_room=True),
            "a-01": Room(1, [Transition("a-01x", [[ItemName.GREEN_BUBBLES]])]),
            "a-01x": Room(2, [Transition("a-02")], [Location(LocationType.STRAWBERRY, 11)]),
            "a-02": Room(3, [Transition("a-03")], [Location(LocationType.STRAWBERRY, 8)]),
            "a-03": Room(4, [Transition("a-04")], [Location(LocationType.STRAWBERRY, 33)]),
            "a-04": Room(5, [Transition("a-05", [[ItemName.CLOUDS], [ItemName.PINK_CLOUDS]])], [Location(LocationType.STRAWBERRY, 11, [[ItemName.CLOUDS]])]),
            "a-05": Room(6, [Transition("a-06", [[ItemName.MOVING_PLATFORM]])]),
            "a-06": Room(7, [Transition("a-07")], [Location(LocationType.STRAWBERRY, 6)]),
            "a-07": Room(8, [Transition("a-08", [[ItemName.TOUCH_SWITCH]])], [Location(LocationType.STRAWBERRY, 16, [[ItemName.TOUCH_SWITCH]])]),
            "a-08": Room(9, [Transition("a-09", [[ItemName.CLOUDS]]), Transition("a-10", [[ItemName.CLOUDS]])]),
            "a-10": Room(10, [Transition("a-08"), Transition("a-11")], [Location(LocationType.STRAWBERRY, 13, [[ItemName.SPRINGS]])]),
            "a-09": Room(11, [Transition("b-00")], [Location(LocationType.STRAWBERRY, 12)]),
            "b-00": Room(12, [Transition("b-02", [[ItemName.MOVING_BLOCK]]), Transition("b-01"), Transition("b-03"), Transition("b-04"), Transition("b-05-left"), Transition("b-02-bottom")], checkpoint="Shrine"),
            "b-01": Room(13, [Transition("b-00")], [Location(LocationType.STRAWBERRY, 13, [[ItemName.MOVING_BLOCK]]), Location(LocationType.STRAWBERRY, 6, [[ItemName.MOVING_BLOCK]])]),
            "b-03": Room(14, [Transition("b-00")], [Location(LocationType.STRAWBERRY, 5, [[ItemName.MOVING_BLOCK]])]),
            "b-04": Room(15, [Transition("b-00"), Transition("b-06", [[ItemName.MOVING_BLOCK]])]),
            "b-04-berry": Room(102, [Transition("b-04")], [Location(LocationType.STRAWBERRY, 1)]),
            "b-02": Room(16, [Transition("b-05"), Transition("b-sec")], [Location(LocationType.STRAWBERRY, 58)]),
            "b-02-bottom": Room(100, [Transition("b-00")], [Location(LocationType.STRAWBERRY, 20, [[ItemName.MOVING_BLOCK]])], is_subregion_of="b-02"),
            "b-sec": Room(17, [Transition("b-02"), Transition("b-secb")], [Location(LocationType.CRYSTAL_HEART, access_rule=[[ItemName.WHITE_BLOCK]])]),
            "b-05": Room(18, [Transition("b-08b")]),
            "b-05-left": Room(101, [Transition("b-04-berry", [[ItemName.PINK_CLOUDS, ItemName.MOVING_BLOCK]])]),
            "b-08b": Room(19, [Transition("b-08")]),
            "b-08": Room(20, [Transition("c-00")], [Location(LocationType.STRAWBERRY, 11)]),
            "c-00": Room(21, [Transition("c-02", [[ItemName.GREEN_BUBBLES]]), Transition("c-01")], [Location(LocationType.STRAWBERRY, 17)], checkpoint="Old Trail"),
            "c-01": Room(22, [Transition("c-00")], [Location(LocationType.STRAWBERRY, 26)]),
            "c-02": Room(23, [Transition("c-04")]),
            "c-04": Room(24, [Transition("c-05", [[ItemName.GREEN_BUBBLES]])]),
            "c-05": Room(25, [Transition("c-06", [[ItemName.MOVING_BLOCK]])], [Location(LocationType.STRAWBERRY, 21, [[ItemName.MOVING_BLOCK]])]),
            "c-06": Room(26, [Transition("c-09"), Transition("c-06b")], [Location(LocationType.STRAWBERRY, 35, [[ItemName.TOUCH_SWITCH]])]),
            "c-06b": Room(27, [Transition("c-06")], [Location(LocationType.STRAWBERRY, 43, [[ItemName.DASH_CRYSTALS]])]),
            "c-09": Room(28, [Transition("c-07")]),
            "c-07": Room(29, [Transition("c-08")]),
            "c-08": Room(30, [Transition("d-00", [[ItemName.SPRINGS]]), Transition("c-10", [[ItemName.SPRINGS]])], [Location(LocationType.STRAWBERRY, 28, [[ItemName.SPRINGS]])]),
            "c-10": Room(31, [Transition("c-08"), Transition("d-00")], [Location(LocationType.STRAWBERRY, 55)]),
            "d-00": Room(32, [Transition("d-01"), Transition("d-00b")], checkpoint="Cliff Face"),
            "d-00b": Room(33, [Transition("d-00")], [Location(LocationType.STRAWBERRY, 11, [[ItemName.GREEN_BUBBLES, ItemName.MOVING_BLOCK]])]),
            "d-01": Room(34, [Transition("d-02", [[ItemName.CRUMBLING_PLATFORM]])], [Location(LocationType.STRAWBERRY, 7, [[ItemName.CRUMBLING_PLATFORM]])]),
            "d-02": Room(35, [Transition("d-03", [[ItemName.TOUCH_SWITCH, ItemName.PINK_CLOUDS, ItemName.MOVING_BLOCK, ItemName.GREEN_BUBBLES]])]),
            "d-03": Room(36, [Transition("d-04")]),
            "d-04": Room(37, [Transition("d-05")], [Location(LocationType.STRAWBERRY, 88)]),
            "d-05": Room(38, [Transition("d-06", [[ItemName.SPRINGS]])]),
            "d-06": Room(39, [Transition("d-07")]),
            "d-07": Room(40, [Transition("d-08")], [Location(LocationType.STRAWBERRY, 70)]),
            "d-08": Room(41, [Transition("d-09", [[ItemName.CLOUDS]])]),
            "d-09": Room(42, [Transition("d-10")], [Location(LocationType.STRAWBERRY, 18)]),
            "d-10": Room(43, [Transition("d-09")], [Location(LocationType.LEVEL_CLEAR)]),
            "a-11": Room(45, [Transition("a-10")], [Location(LocationType.CASSETTE, access_rule=[[ItemName.BLUE_CASSETTE, ItemName.PINK_CASSETTE]])]),
            "b-06": Room(46, [Transition("b-07", [[ItemName.MOVING_BLOCK, ItemName.GREEN_BUBBLES]]), Transition("b-04")]),
            "b-07": Room(47, [Transition("b-03", [[ItemName.MOVING_BLOCK]])], [Location(LocationType.STRAWBERRY, 15, [[ItemName.MOVING_BLOCK]])]),
            "b-secb": Room(48, [Transition("b-sec")], [Location(LocationType.STRAWBERRY, 9, [[ItemName.MOVING_BLOCK]])])
        }, LevelCategory.A_SIDE, 10
    ),
    LevelName.GOLDEN_RIDGE_B:
    Level(
        {
            "a-00": Room(0, [Transition("a-01", [[ItemName.GREEN_BUBBLES]])], [Location(LocationType.GOLDEN_BERRY, 41, [[ItemName.GREEN_BUBBLES, ItemName.MOVING_PLATFORM, ItemName.MOVING_BLOCK, ItemName.CRUMBLING_PLATFORM, ItemName.CLOUDS, ItemName.PINK_CLOUDS, ItemName.BLUE_CASSETTE, ItemName.PINK_CASSETTE, ItemName.TOUCH_SWITCH, ItemName.DASH_CRYSTALS]])], start_room=True),
            "a-01": Room(1, [Transition("a-02", [[ItemName.MOVING_PLATFORM]])]),
            "a-02": Room(2, [Transition("a-03")]),
            "a-03": Room(3, [Transition("a-04", [[ItemName.MOVING_BLOCK]])]),
            "a-04": Room(4, [Transition("b-00")]),
            "b-00": Room(5, [Transition("b-01", [[ItemName.CRUMBLING_PLATFORM, ItemName.GREEN_BUBBLES]])], checkpoint="Stepping Stones"),
            "b-01": Room(6, [Transition("b-02")]),
            "b-02": Room(7, [Transition("b-03", [[ItemName.MOVING_BLOCK]])]),
            "b-03": Room(8, [Transition("b-04")]),
            "b-04": Room(9, [Transition("c-00")]),
            "c-00": Room(10, [Transition("c-01", [[ItemName.GREEN_BUBBLES]])], checkpoint="Gusty Canyon"),
            "c-01": Room(11, [Transition("c-02", [[ItemName.MOVING_PLATFORM]])]),
            "c-02": Room(12, [Transition("c-03", [[ItemName.MOVING_BLOCK]])]),
            "c-03": Room(13, [Transition("c-04")]),
            "c-04": Room(14, [Transition("d-00")]),
            "d-00": Room(15, [Transition("d-01", [[ItemName.CLOUDS]])], checkpoint="Eye of the Storm"),
            "d-01": Room(16, [Transition("d-02", [[ItemName.PINK_CLOUDS, ItemName.GREEN_BUBBLES]])]),
            "d-02": Room(17, [Transition("d-03", [[ItemName.TOUCH_SWITCH, ItemName.DASH_CRYSTALS]])]),
            "d-03": Room(18, [Transition("end", [[ItemName.CRUMBLING_PLATFORM]])]),
            "end": Room(19, [], [Location(LocationType.CRYSTAL_HEART, access_rule=[[ItemName.BLUE_CASSETTE, ItemName.PINK_CASSETTE]])])
        }, LevelCategory.B_SIDE, 11
    ),
    LevelName.GOLDEN_RIDGE_C:
    Level(
        {
            "00": Room(0, [Transition("01", [[ItemName.GREEN_BUBBLES]])], [Location(LocationType.GOLDEN_BERRY, 1, [[ItemName.GREEN_BUBBLES, ItemName.MOVING_BLOCK, ItemName.DASH_CRYSTALS, ItemName.CRUMBLING_PLATFORM, ItemName.PINK_CLOUDS]])], start_room=True),
            "01": Room(1, [Transition("02", [[ItemName.MOVING_BLOCK, ItemName.DASH_CRYSTALS]])]),
            "02": Room(2, [], [Location(LocationType.CRYSTAL_HEART, access_rule=[[ItemName.CRUMBLING_PLATFORM, ItemName.PINK_CLOUDS]])])
        }, LevelCategory.C_SIDE, 12
    ),
    LevelName.MIRROR_TEMPLE_A:
    Level(
        {
            "a-00x": Room(0, [Transition("a-00b")], [Location(LocationType.STRAWBERRY, 7)], start_room=True),
            "a-00b": Room(1, [Transition("a-00d")], [Location(LocationType.GOLDEN_BERRY, 3, [[ItemName.RED_BUBBLES, ItemName.DASH_SWITCH, ItemName.SWAP_BLOCK, ItemName.TOUCH_SWITCH, ItemName.SEEKERS, ItemName.THEO_CRYSTAL, getKeyDoorName(LevelName.MIRROR_TEMPLE_A, "a-13", 1), getKeyDoorName(LevelName.MIRROR_TEMPLE_A, "d-01", 310), getKeyDoorName(LevelName.MIRROR_TEMPLE_A, "d-01", 301)]])]),
            "a-00d": Room(2, [Transition("a-00c")]),
            "a-00c": Room(3, [Transition("a-00")]),
            "a-00": Room(4, [Transition("a-01", [[ItemName.RED_BUBBLES, ItemName.DASH_SWITCH]])]),
            "a-01": Room(5, [Transition("a-13"), Transition("a-04", [[ItemName.SWAP_BLOCK]]), Transition("a-02", [[ItemName.SWAP_BLOCK]]), Transition("a-08")], [Location(LocationType.STRAWBERRY, 256), Location(LocationType.STRAWBERRY, 164)]),
            "a-04": Room(6, [Transition("a-01"), Transition("a-03"), Transition("a-05")], [Location(LocationType.STRAWBERRY, 2, [[ItemName.SWAP_BLOCK]])]),
            "a-02": Room(7, [Transition("a-01"), Transition("a-03"), Transition("a-05")], [Location(LocationType.STRAWBERRY, 23)]),
            "a-08": Room(8, [Transition("a-01"), Transition("a-14", [[ItemName.SWAP_BLOCK]]), Transition("a-12", [[ItemName.SWAP_BLOCK]]), Transition("a-10")]),
            "a-08-key": Room(100, [Transition("a-08"), Transition("a-12-bottom")], [Location(LocationType.KEY, 55)], is_subregion_of="a-08"),
            "a-13": Room(9, [Transition("b-00", [[getKeyDoorName(LevelName.MIRROR_TEMPLE_A, "a-13", 1)]]), Transition("a-01")], key_door_ids=[1]),
            "b-00": Room(10, [Transition("b-01", [[ItemName.DASH_SWITCH]]), Transition("b-18")], checkpoint="Depths"),
            "b-18": Room(11, [Transition("b-00")], [Location(LocationType.STRAWBERRY, 2, [[ItemName.RED_BUBBLES]])]),
            "b-01": Room(12, [Transition("b-01b"), Transition("b-20"), Transition("b-01c")]),
            "b-20": Room(13, [Transition("b-01"), Transition("b-21")], [Location(LocationType.STRAWBERRY, 189), Location(LocationType.STRAWBERRY, 183, [[ItemName.SWAP_BLOCK]])]),
            "b-01c": Room(14, [Transition("b-01")], [Location(LocationType.STRAWBERRY, 85)]),
            "b-01b": Room(15, [Transition("b-02")]),
            "b-02": Room(16, [Transition("b-06"), Transition("b-03"), Transition("b-05"), Transition("b-04"), Transition("b-10"), Transition("b-11")]),
            "b-03": Room(17, [Transition("b-02")], [Location(LocationType.STRAWBERRY, 24, [[ItemName.RED_BUBBLES]])]),
            "b-05": Room(18, [Transition("b-02")], [Location(LocationType.STRAWBERRY, 23, [[ItemName.RED_BUBBLES, ItemName.DASH_CRYSTALS]])]),
            "b-04": Room(19, [Transition("b-02"), Transition("b-07")]),
            "b-04-key": Room(102, [Transition("b-04")], [Location(LocationType.KEY, 3)], is_subregion_of="b-04"),
            "b-10": Room(20, [Transition("b-02")], [Location(LocationType.STRAWBERRY, 4, [[ItemName.SWAP_BLOCK]])]),
            "b-11": Room(21, [Transition("b-02"), Transition("b-12"), Transition("b-13")]),
            "b-06": Room(22, [Transition("b-19", [[ItemName.RED_BUBBLES]])], key_door_ids=[2]),
            "b-19": Room(23, [Transition("b-14")]),
            "b-14": Room(24, [Transition("b-16"), Transition("b-15")], key_door_ids = [3]),
            "b-15": Room(25, [Transition("b-14")], [Location(LocationType.CRYSTAL_HEART, access_rule=[[ItemName.SWAP_BLOCK]])]),
            "b-16": Room(26, [Transition("c-00")]),
            "c-00": Room(27, [Transition("c-01")], checkpoint="Unravelling"),
            "c-01": Room(28, [Transition("c-01b")]),
            "c-01b": Room(29, [Transition("c-01c", [[ItemName.SWAP_BLOCK, ItemName.DASH_SWITCH]])]),
            "c-01c": Room(30, [Transition("c-08b", [[ItemName.RED_BUBBLES]])]),
            "c-08b": Room(31, [Transition("c-08")]),
            "c-08": Room(32, [Transition("c-10")], [Location(LocationType.STRAWBERRY, 112, [[ItemName.SEEKERS]])]),
            "c-10": Room(33, [Transition("c-12", [[ItemName.TOUCH_SWITCH]])]),
            "c-12": Room(34, [Transition("c-07")]),
            "c-07": Room(35, [Transition("c-11")]),
            "c-11": Room(36, [Transition("c-09")]),
            "c-09": Room(37, [Transition("c-13")]),
            "c-13": Room(38, [Transition("d-00")]),
            "d-00": Room(39, [Transition("d-01", [[ItemName.RED_BUBBLES]])], checkpoint="Search"),
            "d-01": Room(40, [Transition("d-04"), Transition("d-09"), Transition("e-00-early"), Transition("d-15"), Transition("d-05"), Transition("d-07")], key_door_ids = [310, 301]),
            "d-09": Room(41, [Transition("d-01"), Transition("d-04-berry", [[ItemName.SWAP_BLOCK]])]),
            "d-04": Room(42, [Transition("d-01"), Transition("d-19b-early", [[getKeyDoorName(LevelName.MIRROR_TEMPLE_A, "d-01", 310), getKeyDoorName(LevelName.MIRROR_TEMPLE_A, "d-01", 301)]])], [Location(LocationType.STRAWBERRY, 35), Location(LocationType.STRAWBERRY, 126, [[ItemName.SWAP_BLOCK]])]),
            "d-04-key-left": Room(106, [Transition("d-04")], [Location(LocationType.KEY, 39)], is_subregion_of="d-04"),
            "d-04-key-right": Room(107, [Transition("d-04")], [Location(LocationType.KEY, 14)], is_subregion_of="d-04"),
            "d-04-berry": Room(108, [Transition("d-04")], [Location(LocationType.KEY, 35)], is_subregion_of="d-04"),
            "d-19": Room(43, [Transition("d-19b", [[ItemName.SWAP_BLOCK]])], [Location(LocationType.STRAWBERRY, 533, [[getKeyDoorName(LevelName.MIRROR_TEMPLE_A, "d-19", 531)]])], key_door_ids = [531]),
            "d-19b": Room(44, [Transition("d-10")]),
            "d-19b-early": Room(109, [Transition("d-19")], is_subregion_of="d-19b"),
            "d-10": Room(45, [Transition("d-20")]),
            "d-20": Room(46, [Transition("e-00", [[ItemName.SEEKERS, ItemName.TOUCH_SWITCH]])]),
            "e-00": Room(47, [Transition("e-01", [[ItemName.THEO_CRYSTAL]])], checkpoint="Rescue"),
            "e-00-early": Room(104, [Transition("d-01")], is_subregion_of="e-00"),
            "e-01": Room(48, [Transition("e-02", [[ItemName.DASH_SWITCH]])]),
            "e-02": Room(49, [Transition("e-03")]),
            "e-03": Room(50, [Transition("e-04")]),
            "e-04": Room(51, [Transition("e-06", [[ItemName.TOUCH_SWITCH]])]),
            "e-06": Room(52, [Transition("e-05")], [Location(LocationType.STRAWBERRY, 56, [[ItemName.SEEKERS]])]),
            "e-05": Room(53, [Transition("e-07", [[ItemName.SWAP_BLOCK]])]),
            "e-07": Room(54, [Transition("e-08")]),
            "e-08": Room(55, [Transition("e-09")]),
            "e-09": Room(56, [Transition("e-10")]),
            "e-10": Room(57, [Transition("e-11")]),
            "e-11": Room(58, [], [Location(LocationType.LEVEL_CLEAR)]),
            "a-03": Room(60, [Transition("a-02"), Transition("a-04")], [Location(LocationType.STRAWBERRY, 4)]),
            "a-05": Room(61, [Transition("a-06", [[ItemName.SWAP_BLOCK]]), Transition("a-07"), Transition("a-02"), Transition("a-04")], [Location(LocationType.STRAWBERRY, 22)]),
            "a-06": Room(62, [Transition("a-05")], [Location(LocationType.STRAWBERRY, 2)]),
            "a-07": Room(63, [Transition("a-05")], [Location(LocationType.STRAWBERRY, 6)]),
            "a-14": Room(64, [Transition("a-08")], [Location(LocationType.STRAWBERRY, 12, [[ItemName.DASH_CRYSTALS]])]),
            "a-09": Room(65, [Transition("a-10"), Transition("a-11")]),
            "a-10": Room(66, [Transition("a-09"), Transition("a-08")]),
            "a-11": Room(67, [Transition("a-09")], [Location(LocationType.STRAWBERRY, 2, [[ItemName.SWAP_BLOCK]])]),
            "a-12": Room(68, [Transition("a-08-key")]),
            "a-12-bottom": Room(101, [Transition("a-08-key"), Transition("a-15")], is_subregion_of="a-12"),
            "a-15": Room(69, [Transition("a-12-bottom")], [Location(LocationType.STRAWBERRY, 182, [[ItemName.TOUCH_SWITCH]])]),
            "b-21": Room(70, [Transition("b-20")], [Location(LocationType.STRAWBERRY, 99, [[ItemName.RED_BUBBLES]])]),
            "b-08": Room(71, [Transition("b-07"), Transition("b-09")]),
            "b-07": Room(72, [Transition("b-08")]),
            "b-09": Room(73, [Transition("b-04-key", [[ItemName.RED_BUBBLES]])]),
            "b-12": Room(74, [Transition("b-11")], [Location(LocationType.STRAWBERRY, 42)]),
            "b-17": Room(75, [Transition("b-13"), Transition("b-22")], [Location(LocationType.STRAWBERRY, 10, [[ItemName.SPRINGS]])]),
            "b-17-berry": Room(103, [Transition("b-13")], [Location(LocationType.STRAWBERRY, 14)]),
            "b-13": Room(76, [Transition("b-17"), Transition("b-17-berry", [[ItemName.SWAP_BLOCK]])]),
            "b-22": Room(77, [Transition("b-17")], [Location(LocationType.CASSETTE, access_rule=[[ItemName.BLUE_CASSETTE]])]),
            "d-15": Room(78, [Transition("d-13"), Transition("d-01")], [Location(LocationType.STRAWBERRY, 336), Location(LocationType.STRAWBERRY, 217, [[ItemName.SWAP_BLOCK, ItemName.DASH_CRYSTALS]]), Location(LocationType.KEY, 216, [[ItemName.SEEKERS, ItemName.SWAP_BLOCK]])]),
            "d-13": Room(79, [Transition("d-15")], [Location(LocationType.STRAWBERRY, 199)]),
            "d-05": Room(80, [Transition("d-06")]),
            "d-06": Room(81, [Transition("d-04-key-right", [[ItemName.SWAP_BLOCK]])]),
            "d-06-left": Room(105, [Transition("d-04-key-left")], is_subregion_of="d-06"),
            "d-02": Room(82, [Transition("d-03")]),
            "d-03": Room(83, [Transition("d-06-left", [[ItemName.TOUCH_SWITCH]])]),
            "d-07": Room(84, [Transition("d-02", [[ItemName.TOUCH_SWITCH]])])
        }, LevelCategory.A_SIDE, 13
    ),
    LevelName.MIRROR_TEMPLE_B:
    Level(
        {
            "start": Room(0, [Transition("a-00")], [Location(LocationType.GOLDEN_BERRY, 3, [[ItemName.SWAP_BLOCK, ItemName.RED_BUBBLES, ItemName.DASH_SWITCH, ItemName.SPRINGS, getKeyDoorName(LevelName.MIRROR_TEMPLE_B, "b-02", 226), getKeyDoorName(LevelName.MIRROR_TEMPLE_B, "b-00", 145), ItemName.DASH_CRYSTALS, ItemName.SEEKERS, ItemName.SPRINGS, ItemName.PINK_CASSETTE, ItemName.BLUE_CASSETTE, ItemName.THEO_CRYSTAL]])], start_room=True),
            "a-00": Room(1, [Transition("a-01", [[ItemName.RED_BUBBLES, ItemName.DASH_SWITCH]])]),
            "a-01": Room(2, [Transition("a-02")]),
            "a-02": Room(3, [Transition("b-00", [[ItemName.SWAP_BLOCK]])]),
            "b-00": Room(4, [Transition("b-02"), Transition("b-06", [[getKeyDoorName(LevelName.MIRROR_TEMPLE_B, "b-00", 145)]]), Transition("b-01")], checkpoint="Central Chamber", key_door_ids=[145]),
            "b-06": Room(5, [Transition("b-00"), Transition("b-07", [[ItemName.RED_BUBBLES]])]),
            "b-01": Room(6, [Transition("b-00"), Transition("b-04", [[ItemName.SWAP_BLOCK, ItemName.DASH_CRYSTALS]])]),
            "b-02": Room(7, [Transition("b-08"), Transition("b-05")], key_door_ids=[226]),
            "b-02-key-left": Room(100, [Transition("b-02")], [Location(LocationType.KEY, 221)], is_subregion_of="b-02"),
            "b-02-key-right": Room(101, [Transition("b-02")], [Location(LocationType.KEY, 219)], is_subregion_of="b-02"),
            "b-05": Room(8, [Transition("b-02"), Transition("b-02-key-left", [[ItemName.DASH_CRYSTALS, ItemName.TOUCH_SWITCH]])]),
            "b-08": Room(9, [Transition("b-09", [[ItemName.SWAP_BLOCK, ItemName.RED_BUBBLES, ItemName.DASH_SWITCH, ItemName.SPRINGS, getKeyDoorName(LevelName.MIRROR_TEMPLE_B, "b-02", 226), getKeyDoorName(LevelName.MIRROR_TEMPLE_B, "b-00", 145)]])]),
            "b-08-right": Room(102, [Transition("b-08", [[ItemName.SWAP_BLOCK, ItemName.SPRINGS]])], is_subregion_of="b-08"),
            "b-09": Room(10, [Transition("c-00", [[ItemName.CRUMBLING_PLATFORM]])]),
            "c-00": Room(11, [Transition("c-01", [[ItemName.DASH_SWITCH, ItemName.DASH_CRYSTALS]])], checkpoint="Through the Mirror"),
            "c-01": Room(12, [Transition("c-02", [[ItemName.SEEKERS, ItemName.TOUCH_SWITCH]])]),
            "c-02": Room(13, [Transition("c-03")]),
            "c-03": Room(14, [Transition("c-04", [[ItemName.RED_BUBBLES]])]),
            "c-04": Room(15, [Transition("d-00", [[ItemName.CRUMBLING_PLATFORM]])]),
            "d-00": Room(16, [Transition("d-01", [[ItemName.THEO_CRYSTAL]])], checkpoint="Mix Master"),
            "d-01": Room(17, [Transition("d-02", [[ItemName.SPRINGS, ItemName.DASH_SWITCH, ItemName.SEEKERS]])]),
            "d-02": Room(18, [Transition("d-03", [[ItemName.SEEKERS]])]),
            "d-03": Room(19, [Transition("d-04", [[ItemName.TOUCH_SWITCH, ItemName.SWAP_BLOCK]])]),
            "d-04": Room(20, [Transition("d-05", [[ItemName.DASH_CRYSTALS]])]),
            "d-05": Room(21, [], [Location(LocationType.CRYSTAL_HEART, access_rule=[[ItemName.BLUE_CASSETTE, ItemName.PINK_CASSETTE]])]),
            "b-07": Room(23, [Transition("b-03", [[ItemName.SWAP_BLOCK]])]),
            "b-03": Room(24, [Transition("b-08-right", [[ItemName.RED_BUBBLES, ItemName.DASH_SWITCH]]), Transition("b-02", [[ItemName.RED_BUBBLES, ItemName.DASH_SWITCH, getKeyDoorName(LevelName.MIRROR_TEMPLE_B, "b-02", 226)]])]),
            "b-04": Room(25, [Transition("b-02-key-right", [[ItemName.SWAP_BLOCK, ItemName.DASH_CRYSTALS]])])
        }, LevelCategory.B_SIDE, 14
    ),
    LevelName.MIRROR_TEMPLE_C:
    Level(
        {
            "00": Room(0, [Transition("01", [[ItemName.DASH_CRYSTALS, ItemName.SWAP_BLOCK]])], [Location(LocationType.GOLDEN_BERRY, 25, [[ItemName.DASH_CRYSTALS, ItemName.SWAP_BLOCK, ]])], start_room=True),
            "01": Room(1, [Transition("02")]),
            "02": Room(2, [], [Location(LocationType.CRYSTAL_HEART, access_rule=[[ItemName.RED_BUBBLES, ItemName.DASH_SWITCH]])])
        }, LevelCategory.C_SIDE, 15
    ),
    LevelName.REFLECTION_A:
    Level(
        {
            "start": Room(0, [Transition("00", [[ItemName.FEATHER]])], start_room=True),
            "00": Room(1, [Transition("01", [[ItemName.KEVIN]])], [Location(LocationType.GOLDEN_BERRY, 51, [[ItemName.KEVIN, ItemName.BUMPER, ItemName.FEATHER, ItemName.DASH_CRYSTALS, ItemName.BADELINE_ORB]])], checkpoint="Lake"),
            "01": Room(2, [Transition("02", [[ItemName.FEATHER]])]),
            "02": Room(3, [Transition("03")]),
            "03": Room(4, [Transition("02b")]),
            "02b": Room(5, [Transition("04")]),
            "04": Room(6, [Transition("05"), Transition("04e", [[ItemName.KEVIN]]), Transition("04b")], checkpoint="Hollows"),
            "04e": Room(7, [Transition("04")], [Location(LocationType.CASSETTE, access_rule=[[ItemName.BLUE_CASSETTE, ItemName.PINK_CASSETTE]])]),
            "04b": Room(8, [Transition("04"), Transition("04c")]),
            "05": Room(9, [Transition("06", [[ItemName.KEVIN]])]),
            "06": Room(10, [Transition("07", [[ItemName.FEATHER]])]),
            "07": Room(11, [Transition("08a"), Transition("08b")]),
            "08b": Room(12, [Transition("09", [[ItemName.FEATHER]])]),
            "08a": Room(13, [Transition("09", [[ItemName.DASH_CRYSTALS]])]),
            "09": Room(14, [Transition("10a"), Transition("10b")]),
            "10b": Room(15, [Transition("11")]),
            "10a": Room(16, [Transition("11")]),
            "11": Room(17, [Transition("12a", [[ItemName.BUMPER]]), Transition("12b", [[ItemName.BUMPER]])]),
            "12b": Room(18, [Transition("13", [[ItemName.BUMPER]])]),
            "12a": Room(19, [Transition("13")]),
            "13": Room(20, [Transition("14a"), Transition("14b")]),
            "14b": Room(21, [Transition("15", [[ItemName.TOUCH_SWITCH]])]),
            "14a": Room(22, [Transition("15")]),
            "15": Room(23, [Transition("16a"), Transition("16b")]),
            "16b": Room(24, [Transition("17", [[ItemName.DASH_CRYSTALS]])]),
            "16a": Room(25, [Transition("17")]),
            "17": Room(26, [Transition("18a"), Transition("18b")]),
            "18b": Room(27, [Transition("19")]),
            "18a": Room(28, [Transition("19")]),
            "19": Room(29, [Transition("20")]),
            "20": Room(30, [Transition("b-00")]),
            "b-00": Room(31, [Transition("b-01"), Transition("b-00b")], checkpoint="Reflection"),
            "b-01": Room(32, [Transition("b-02")]),
            "b-02": Room(33, [Transition("b-02b", [[ItemName.KEVIN]])]),
            "b-02b": Room(34, [Transition("b-03")]),
            "b-03": Room(35, [Transition("boss-00")]),
            "boss-00": Room(36, [Transition("boss-01"), Transition("b-03")], checkpoint="Rock Bottom"),
            "boss-01": Room(37, [Transition("boss-02")]),
            "boss-02": Room(38, [Transition("boss-03")]),
            "boss-03": Room(39, [Transition("boss-04")]),
            "boss-04": Room(40, [Transition("boss-05")]),
            "boss-05": Room(41, [Transition("boss-06", [[ItemName.DASH_CRYSTALS]])]),
            "boss-06": Room(42, [Transition("boss-07")]),
            "boss-07": Room(43, [Transition("boss-08")]),
            "boss-08": Room(44, [Transition("boss-09")]),
            "boss-09": Room(45, [Transition("boss-10", [[ItemName.FEATHER]])]),
            "boss-10": Room(46, [Transition("boss-11")]),
            "boss-11": Room(47, [Transition("boss-12")]),
            "boss-12": Room(48, [Transition("boss-13")]),
            "boss-13": Room(49, [Transition("boss-14")]),
            "boss-14": Room(50, [Transition("boss-15")]),
            "boss-15": Room(51, [Transition("boss-16")]),
            "boss-16": Room(52, [Transition("boss-17")]),
            "boss-17": Room(53, [Transition("boss-18")]),
            "boss-18": Room(54, [Transition("boss-19", [[ItemName.FEATHER, ItemName.BUMPER]])]),
            "boss-19": Room(55, [Transition("boss-20")]),
            "boss-20": Room(56, [Transition("after-00")]),
            "after-00": Room(57, [Transition("after-01"), Transition("boss-20")], checkpoint="Resolution"),
            "after-01": Room(58, [Transition("after-02", [[ItemName.BADELINE_ORB]])]),
            "after-02": Room(59, [], [Location(LocationType.LEVEL_CLEAR)]),
            "04c": Room(61, [Transition("04b")], [Location(LocationType.CRYSTAL_HEART)]),
            "b-00b": Room(62, [Transition("b-00c"), Transition("b-00")], easter_egg=True),
            "b-00c": Room(63, [Transition("b-00b")], easter_egg=True)
        }, LevelCategory.A_SIDE, 16
    ),
    LevelName.REFLECTION_B:
    Level(
        {
            "a-00": Room(0, [Transition("a-01", [[ItemName.KEVIN]])], [Location(LocationType.GOLDEN_BERRY, 137, [[ItemName.KEVIN, ItemName.BUMPER, ItemName.FEATHER, ItemName.DASH_CRYSTALS, ItemName.CRUMBLING_PLATFORM, ItemName.SPRINGS, ItemName.TOUCH_SWITCH, ItemName.BLUE_CASSETTE]])], start_room=True),
            "a-01": Room(1, [Transition("a-02", [[ItemName.FEATHER, ItemName.DASH_CRYSTALS]])]),
            "a-02": Room(2, [Transition("a-03", [[ItemName.BUMPER]])]),
            "a-03": Room(3, [Transition("a-04", [[ItemName.TOUCH_SWITCH]])]),
            "a-04": Room(4, [Transition("a-05")]),
            "a-05": Room(5, [Transition("a-06", [[ItemName.CRUMBLING_PLATFORM]])]),
            "a-06": Room(6, [Transition("b-00")]),
            "b-00": Room(7, [Transition("b-01")], checkpoint="Reflection"),
            "b-01": Room(8, [Transition("b-02", [[ItemName.DASH_CRYSTALS]])]),
            "b-02": Room(9, [Transition("b-03", [[ItemName.KEVIN]])]),
            "b-03": Room(10, [Transition("b-04", [[ItemName.BUMPER]])]),
            "b-04": Room(11, [Transition("b-05")]),
            "b-05": Room(12, [Transition("b-06")]),
            "b-06": Room(13, [Transition("b-07")]),
            "b-07": Room(14, [Transition("b-08", [[ItemName.FEATHER]])]),
            "b-08": Room(15, [Transition("b-09")]),
            "b-09": Room(16, [Transition("b-10")]),
            "b-10": Room(17, [Transition("c-00")]),
            "c-00": Room(18, [Transition("c-01", [[ItemName.SPRINGS]])], checkpoint="Rock Bottom"),
            "c-01": Room(19, [Transition("c-02", [[ItemName.FEATHER, ItemName.DASH_CRYSTALS]])]),
            "c-02": Room(20, [Transition("c-03")]),
            "c-03": Room(21, [Transition("c-04", [[ItemName.TOUCH_SWITCH]])]),
            "c-04": Room(22, [Transition("d-00", [[ItemName.BUMPER]])]),
            "d-00": Room(23, [Transition("d-01", [[ItemName.KEVIN, ItemName.BUMPER]])], checkpoint="Reprieve"),
            "d-01": Room(24, [Transition("d-02", [[ItemName.CRUMBLING_PLATFORM]])]),
            "d-02": Room(25, [Transition("d-03", [[ItemName.FEATHER, ItemName.TOUCH_SWITCH]])]),
            "d-03": Room(26, [Transition("d-04")]),
            "d-04": Room(27, [Transition("d-05")]),
            "d-05": Room(28, [], [Location(LocationType.CRYSTAL_HEART, access_rule=[[ItemName.BLUE_CASSETTE]])])
        }, LevelCategory.B_SIDE, 17
    ),
    LevelName.REFLECTION_C:
    Level(
        {
            "00": Room(0, [Transition("01", [[ItemName.BUMPER]])], [Location(LocationType.GOLDEN_BERRY, 3, [[ItemName.BUMPER, ItemName.FEATHER, ItemName.DASH_CRYSTALS, ItemName.KEVIN]])], start_room=True),
            "01": Room(1, [Transition("02", [[ItemName.FEATHER, ItemName.DASH_CRYSTALS]])]),
            "02": Room(2, [], [Location(LocationType.CRYSTAL_HEART, access_rule=[[ItemName.KEVIN]])])
        }, LevelCategory.C_SIDE, 18
    ),
    LevelName.SUMMIT_A:
    Level(
        {
            "a-00": Room(0, [Transition("a-01")], [Location(LocationType.GOLDEN_BERRY, 57, [[ItemName.DASH_CRYSTALS, ItemName.TRAFFIC_BLOCKS, ItemName.SPRINGS, ItemName.BADELINE_ORB, ItemName.DREAM_BLOCK, ItemName.TOUCH_SWITCH, ItemName.SINKING_PLATFORM, ItemName.GREEN_BUBBLES, ItemName.RED_BUBBLES, ItemName.MOVING_BLOCK, ItemName.CLOUDS, ItemName.PINK_CLOUDS, ItemName.MOVING_PLATFORM, ItemName.SWAP_BLOCK, ItemName.DASH_SWITCH, ItemName.FEATHER, getKeyDoorName(LevelName.SUMMIT_A, "f-05", 700)]])], start_room=True),
            "a-01": Room(1, [Transition("a-02", [[ItemName.DASH_CRYSTALS]]), Transition("a-00")]),
            "a-02": Room(2, [Transition("a-03"), Transition("a-01"), Transition("a-02b")]),
            "a-02b": Room(3, [Transition("a-02")], [Location(LocationType.STRAWBERRY, 61)]),
            "a-03": Room(4, [Transition("a-04", [[ItemName.SPRINGS]]), Transition("a-02")]),
            "a-04": Room(5, [Transition("a-05"), Transition("a-03"), Transition("a-04b")]),
            "a-04b": Room(6, [Transition("a-04")], [Location(LocationType.STRAWBERRY, 136), Location(LocationType.STRAWBERRY, 85)]),
            "a-05": Room(7, [Transition("a-06"), Transition("a-04")], [Location(LocationType.STRAWBERRY, 54)]),
            "a-06": Room(8, [Transition("b-00", [[ItemName.BADELINE_ORB]]), Transition("a-05")], [Location(LocationType.GEM, 110)]),
            "b-00": Room(9, [Transition("b-01")], checkpoint="500m"),
            "b-01": Room(10, [Transition("b-02", [[ItemName.SPRINGS]])]),
            "b-02": Room(11, [Transition("b-03"), Transition("b-01"), Transition("b-02b", [[ItemName.TRAFFIC_BLOCKS, ItemName.DASH_CRYSTALS]])], [Location(LocationType.STRAWBERRY, 101)]),
            "b-02b": Room(12, [Transition("b-02"), Transition("b-02e"), Transition("b-02c")], [Location(LocationType.STRAWBERRY, 102)]),
            "b-03": Room(13, [Transition("b-05", [[ItemName.TRAFFIC_BLOCKS]]), Transition("b-04")]),
            "b-04": Room(14, [Transition("b-03")], [Location(LocationType.STRAWBERRY, 67)]),
            "b-05": Room(15, [Transition("b-06", [[ItemName.TOUCH_SWITCH]])]),
            "b-06": Room(16, [Transition("b-07"), Transition("b-05")]),
            "b-07": Room(17, [Transition("b-08"), Transition("b-06")]),
            "b-08": Room(18, [Transition("b-09"), Transition("b-07")], [Location(LocationType.STRAWBERRY, 129)]),
            "b-09": Room(19, [Transition("c-00", [[ItemName.TRAFFIC_BLOCKS, ItemName.BADELINE_ORB]]), Transition("b-08")], [Location(LocationType.STRAWBERRY, 167, [[ItemName.TRAFFIC_BLOCKS, ItemName.BADELINE_ORB]])]),
            "c-00": Room(20, [Transition("c-01", [[ItemName.DREAM_BLOCK]])], checkpoint="1000m"),
            "c-01": Room(21, [Transition("c-02")]),
            "c-02": Room(22, [Transition("c-03", [[ItemName.TOUCH_SWITCH]])]),
            "c-03": Room(23, [Transition("c-04"), Transition("c-03b")]),
            "c-03b": Room(24, [Transition("c-03")], [Location(LocationType.STRAWBERRY, 228, [[ItemName.DASH_CRYSTALS]])]),
            "c-04": Room(25, [Transition("c-06b"), Transition("c-05"), Transition("c-06")]),
            "c-05": Room(26, [Transition("c-04")], [Location(LocationType.STRAWBERRY, 248)]),
            "c-06": Room(27, [Transition("c-04"), Transition("c-07"), Transition("c-06b-strawberry-subroom")]),
            "c-06b": Room(28, [Transition("c-07", [[ItemName.CRUMBLING_PLATFORM]]), Transition("c-04"), Transition("c-06c", [[ItemName.CRUMBLING_PLATFORM]])]),
            "c-06b-strawberry-subroom": Room(96, [Transition("c-06b")], [Location(LocationType.STRAWBERRY, 218)], is_subregion_of="c-06b"),
            "c-06c": Room(29, [Transition("c-06b")], [Location(LocationType.GEM, 333, access_rule=[[ItemName.TOUCH_SWITCH]])]),
            "c-07": Room(30, [Transition("c-08"), Transition("c-07b")]),
            "c-07b": Room(31, [Transition("c-07")], [Location(LocationType.STRAWBERRY, 291)]),
            "c-08": Room(32, [Transition("c-09"), Transition("c-07")], [Location(LocationType.STRAWBERRY, 331)]),
            "c-09": Room(33, [Transition("d-00", [[ItemName.BADELINE_ORB]]), Transition("c-08")], [Location(LocationType.STRAWBERRY, 354, [[ItemName.BADELINE_ORB]])]),
            "d-00": Room(34, [Transition("d-01", [[ItemName.DASH_CRYSTALS]])], [Location(LocationType.STRAWBERRY, 43)], checkpoint="1500m"),
            "d-01": Room(35, [Transition("d-01b", [[ItemName.SINKING_PLATFORM]])]),
            "d-01b": Room(36, [Transition("d-02"), Transition("d-01"), Transition("d-01c")]),
            "d-01c": Room(37, [Transition("d-01b"), Transition("d-01d")], [Location(LocationType.STRAWBERRY, 226)]),
            "d-02": Room(38, [Transition("d-03", [[ItemName.TOUCH_SWITCH]]), Transition("d-01b")]),
            "d-03": Room(39, [Transition("d-04"), Transition("d-03b")], [Location(LocationType.STRAWBERRY, 383)]),
            "d-03b": Room(40, [Transition("d-03")], [Location(LocationType.CASSETTE, access_rule=[[ItemName.BLUE_CASSETTE, ItemName.PINK_CASSETTE]])]),
            "d-04": Room(41, [Transition("d-05"), Transition("d-03")], [Location(LocationType.STRAWBERRY, 388)]),
            "d-05": Room(42, [Transition("d-06"), Transition("d-04"), Transition("d-05b")]),
            "d-05b": Room(43, [Transition("d-05")], [Location(LocationType.GEM, 449)]),
            "d-06": Room(44, [Transition("d-09"), Transition("d-05"), Transition("d-07"), Transition("d-08")]),
            "d-07": Room(45, [Transition("d-06")], [Location(LocationType.STRAWBERRY, 484)]),
            "d-08": Room(46, [Transition("d-06"), Transition("d-10")], [Location(LocationType.STRAWBERRY, 527)]),
            "d-09": Room(47, [Transition("d-10"), Transition("d-06")]),
            "d-10": Room(48, [Transition("d-11"), Transition("d-10b")]),
            "d-10b": Room(49, [Transition("d-10")], [Location(LocationType.STRAWBERRY, 682, [[ItemName.SPRINGS]])]),
            "d-11": Room(50, [Transition("e-00b", [[ItemName.BADELINE_ORB]]), Transition("d-10")]),
            "e-00b": Room(51, [Transition("e-00", [[ItemName.GREEN_BUBBLES]])], checkpoint="2000m"),
            "e-00": Room(52, [Transition("e-03", [[ItemName.CLOUDS]]), Transition("e-02"), Transition("e-01")]),
            "e-02": Room(53, [Transition("e-00"), Transition("e-04", [[ItemName.PINK_CLOUDS]])], [Location(LocationType.STRAWBERRY, 7, [[ItemName.PINK_CLOUDS]])]),
            "e-03": Room(54, [Transition("e-04", [[ItemName.MOVING_PLATFORM]]), Transition("e-00")]),
            "e-04": Room(55, [Transition("e-05", [[ItemName.SPRINGS]])]),
            "e-05": Room(56, [Transition("e-06"), Transition("e-04")], [Location(LocationType.STRAWBERRY, 237)]),
            "e-06": Room(57, [Transition("e-07", [[ItemName.MOVING_BLOCK]]), Transition("e-05")]),
            "e-07": Room(58, [Transition("e-08"), Transition("e-06")], [Location(LocationType.STRAWBERRY, 473, [[ItemName.CRUMBLING_PLATFORM, ItemName.DASH_CRYSTALS]])]),
            "e-08": Room(59, [Transition("e-10"), Transition("e-09", [[ItemName.CLOUDS]])]),
            "e-09": Room(60, [Transition("e-08"), Transition("e-11")], [Location(LocationType.STRAWBERRY, 398)]),
            "e-10": Room(61, [Transition("e-10b"), Transition("e-08")], [Location(LocationType.STRAWBERRY, 515)]),
            "e-10b": Room(62, [Transition("e-13"), Transition("e-10")]),
            "e-13": Room(63, [Transition("f-00", [[ItemName.BADELINE_ORB]])], [Location(LocationType.STRAWBERRY, 829, [[ItemName.BADELINE_ORB]])]),
            "f-00": Room(64, [Transition("f-02", [[ItemName.RED_BUBBLES]]), Transition("f-01", [[ItemName.RED_BUBBLES]])], [Location(LocationType.STRAWBERRY, 590, [[ItemName.RED_BUBBLES, ItemName.CRUMBLING_PLATFORM]])], checkpoint="2500m"),
            "f-01": Room(65, [Transition("f-00"), Transition("f-02b")], [Location(LocationType.STRAWBERRY, 639, [[ItemName.SWAP_BLOCK]])]),
            "f-02": Room(66, [Transition("f-04")]),
            "f-02b": Room(67, [Transition("f-02"), Transition("f-07", [[ItemName.DASH_CRYSTALS, ItemName.SWAP_BLOCK, ItemName.DASH_SWITCH]])], [Location(LocationType.GEM, 679, access_rule=[[ItemName.DASH_CRYSTALS, ItemName.SWAP_BLOCK, ItemName.DASH_SWITCH]])]),
            "f-04": Room(68, [Transition("f-03"), Transition("f-02")]),
            "f-03": Room(69, [Transition("f-05")]),
            "f-05": Room(70, [Transition("f-08", [[getKeyDoorName(LevelName.SUMMIT_A, "f-05", 700)]]), Transition("f-07", [[ItemName.RED_BUBBLES]]), Transition("f-06")], key_door_ids=[700]),
            "f-07": Room(71, [Transition("f-05")], [Location(LocationType.STRAWBERRY, 711), Location(LocationType.KEY, 712)]),
            "f-06": Room(72, [Transition("f-05")]),
            "f-08": Room(73, [Transition("f-09"), Transition("f-05"), Transition("f-08b", [[ItemName.RED_BUBBLES]])]),
            "f-08b": Room(74, [Transition("f-08"), Transition("f-08d")], [Location(LocationType.STRAWBERRY, 856)]),
            "f-09": Room(75, [Transition("f-10")]),
            "f-10": Room(76, [Transition("f-10b")]),
            "f-10b": Room(77, [Transition("f-11", [[ItemName.DASH_CRYSTALS, ItemName.DASH_SWITCH]])]),
            "f-11": Room(78, [Transition("g-00", [[ItemName.BADELINE_ORB]])], [Location(LocationType.STRAWBERRY, 1068, [[ItemName.BADELINE_ORB]]), Location(LocationType.STRAWBERRY, 1229, [[ItemName.BADELINE_ORB]]), Location(LocationType.STRAWBERRY, 1238)]),
            "g-00": Room(79, [Transition("g-00b")], checkpoint="3000m"),
            "g-00b": Room(80, [Transition("g-01", [[ItemName.DASH_CRYSTALS, ItemName.CRUMBLING_PLATFORM, ItemName.SPRINGS]])], [Location(LocationType.STRAWBERRY, 37, [[ItemName.DASH_CRYSTALS]]), Location(LocationType.STRAWBERRY, 127, [[ItemName.DASH_CRYSTALS, ItemName.CRUMBLING_PLATFORM]]), Location(LocationType.STRAWBERRY, 114, [[ItemName.DASH_CRYSTALS, ItemName.CRUMBLING_PLATFORM, ItemName.SPRINGS]]), Location(LocationType.CRYSTAL_HEART, access_rule=[[getLocationName(LevelName.SUMMIT_A, "a-06", LocationType.GEM, 110), getLocationName(LevelName.SUMMIT_A, "b-02d", LocationType.GEM, 109), getLocationName(LevelName.SUMMIT_A, "c-06c", LocationType.GEM, 333), getLocationName(LevelName.SUMMIT_A, "d-05b", LocationType.GEM, 449), getLocationName(LevelName.SUMMIT_A, "e-01c", LocationType.GEM, 8), getLocationName(LevelName.SUMMIT_A, "f-02b", LocationType.GEM, 679)]])]),
            "g-01": Room(81, [Transition("g-02", [[ItemName.CLOUDS, ItemName.DASH_CRYSTALS, ItemName.SPRINGS, ItemName.TOUCH_SWITCH]])], [Location(LocationType.STRAWBERRY, 66, [[ItemName.CLOUDS, ItemName.DASH_CRYSTALS]]), Location(LocationType.STRAWBERRY, 279, [[ItemName.CLOUDS, ItemName.DASH_CRYSTALS]]), Location(LocationType.STRAWBERRY, 342, [[ItemName.CLOUDS, ItemName.DASH_CRYSTALS]])]),
            "g-02": Room(82, [Transition("g-03")]),
            "g-03": Room(83, [], [Location(LocationType.STRAWBERRY, 1504, [[ItemName.FEATHER]]), Location(LocationType.LEVEL_CLEAR, access_rule=[[ItemName.FEATHER]])]),
            "b-02e": Room(85, [Transition("b-02b")], [Location(LocationType.STRAWBERRY, 112)]),
            "b-02c": Room(86, [Transition("b-02d", [[ItemName.TRAFFIC_BLOCKS], [ItemName.DASH_CRYSTALS]]), Transition("b-02b"), Transition("b-05", [[ItemName.TRAFFIC_BLOCKS], [ItemName.DASH_CRYSTALS]])]),
            "b-02d": Room(87, [Transition("b-02c"), Transition("b-02")], [Location(LocationType.GEM, 109)]),
            "d-01d": Room(88, [Transition("d-01c")], [Location(LocationType.STRAWBERRY, 282, [[ItemName.DASH_CRYSTALS, ItemName.TOUCH_SWITCH]])]),
            "e-01": Room(89, [Transition("e-01b")]),
            "e-01b": Room(90, [Transition("e-01"), Transition("e-01c")]),
            "e-01c": Room(91, [Transition("e-01")], [Location(LocationType.GEM, 8)]),
            "e-11": Room(92, [Transition("e-12"), Transition("e-10"), Transition("e-09")], [Location(LocationType.STRAWBERRY, 425)]),
            "e-12": Room(93, [Transition("e-11")], [Location(LocationType.STRAWBERRY, 504)]),
            "f-08d": Room(94, [Transition("f-08c", [[ItemName.DASH_SWITCH]])]),
            "f-08c": Room(95, [Transition("f-10", [[ItemName.SWAP_BLOCK, ItemName.DASH_CRYSTALS]])], [Location(LocationType.STRAWBERRY, 759)])
        }, LevelCategory.A_SIDE, 19
    ),
    LevelName.SUMMIT_B:
    Level(
        {
            "a-00": Room(0, [Transition("a-01", [[ItemName.SPRINGS]])], [Location(LocationType.GOLDEN_BERRY, 102, [[ItemName.BLUE_CASSETTE, ItemName.PINK_CASSETTE, ItemName.MOVING_BLOCK, ItemName.SWAP_BLOCK, ItemName.RED_BUBBLES, ItemName.CRUMBLING_PLATFORM, ItemName.PINK_CLOUDS, ItemName.CLOUDS, ItemName.SPRINGS, ItemName.BADELINE_ORB, ItemName.TRAFFIC_BLOCKS, ItemName.DASH_CRYSTALS, ItemName.DREAM_BLOCK, ItemName.TOUCH_SWITCH]])], start_room=True),
            "a-01": Room(1, [Transition("a-02")]),
            "a-02": Room(2, [Transition("a-03")]),
            "a-03": Room(3, [Transition("b-00", [[ItemName.BADELINE_ORB]])]),
            "b-00": Room(4, [Transition("b-01", [[ItemName.TRAFFIC_BLOCKS, ItemName.DASH_CRYSTALS]])], checkpoint="500m"),
            "b-01": Room(5, [Transition("b-02")]),
            "b-02": Room(6, [Transition("b-03", [[ItemName.SPRINGS]])]),
            "b-03": Room(7, [Transition("c-01", [[ItemName.BADELINE_ORB]])]),
            "c-01": Room(8, [Transition("c-00", [[ItemName.DREAM_BLOCK, ItemName.SPRINGS]])], checkpoint="1000m"),
            "c-00": Room(9, [Transition("c-02")]),
            "c-02": Room(10, [Transition("c-03")]),
            "c-03": Room(11, [Transition("d-00", [[ItemName.BADELINE_ORB]])]),
            "d-00": Room(12, [Transition("d-01", [[ItemName.SPRINGS]])], checkpoint="1500m"),
            "d-01": Room(13, [Transition("d-02", [[ItemName.DASH_CRYSTALS]])]),
            "d-02": Room(14, [Transition("d-03", [[ItemName.TOUCH_SWITCH]])]),
            "d-03": Room(15, [Transition("e-00", [[ItemName.BADELINE_ORB]])]),
            "e-00": Room(16, [Transition("e-01", [[ItemName.CLOUDS]])], checkpoint="2000m"),
            "e-01": Room(17, [Transition("e-02", [[ItemName.SPRINGS, ItemName.MOVING_BLOCK]])]),
            "e-02": Room(18, [Transition("e-03")]),
            "e-03": Room(19, [Transition("f-00", [[ItemName.BADELINE_ORB, ItemName.TOUCH_SWITCH]])]),
            "f-00": Room(20, [Transition("f-01", [[ItemName.SWAP_BLOCK]])], checkpoint="2500m"),
            "f-01": Room(21, [Transition("f-02", [[ItemName.RED_BUBBLES]])]),
            "f-02": Room(22, [Transition("f-03", [[ItemName.DASH_CRYSTALS, ItemName.SPRINGS]])]),
            "f-03": Room(23, [Transition("g-00", [[ItemName.BADELINE_ORB]])]),
            "g-00": Room(24, [Transition("g-01", [[ItemName.CRUMBLING_PLATFORM, ItemName.DASH_CRYSTALS, ItemName.SPRINGS, ItemName.BADELINE_ORB]])], checkpoint="3000m"),
            "g-01": Room(25, [Transition("g-02", [[ItemName.PINK_CLOUDS, ItemName.CLOUDS]])]),
            "g-02": Room(26, [Transition("g-03")]),
            "g-03": Room(27, [], [Location(LocationType.CRYSTAL_HEART, access_rule=[[ItemName.BLUE_CASSETTE, ItemName.PINK_CASSETTE]])])
        }, LevelCategory.B_SIDE, 20
    ),
    LevelName.SUMMIT_C:
    Level(
        {
            "00": Room(0, [Transition("01", [[ItemName.DASH_CRYSTALS, ItemName.BADELINE_ORB]])], [Location(LocationType.GOLDEN_BERRY, 334, [[ItemName.DASH_CRYSTALS, ItemName.BADELINE_ORB, ItemName.SPRINGS, ItemName.TOUCH_SWITCH, ItemName.PINK_CLOUDS]])], start_room=True),
            "01": Room(1, [Transition("02", [[ItemName.SPRINGS, ItemName.TOUCH_SWITCH]])]),
            "02": Room(2, [], [Location(LocationType.CRYSTAL_HEART, access_rule=[[ItemName.PINK_CLOUDS]])])
        }, LevelCategory.C_SIDE, 21
    )
}